### ISSUE TITLE
Erro Fatal ao tentar finalizar uma venda

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1009]
Quando o servidor sobrecarrega pode acontecer um erro fatal ao tentar finalizar uma venda... Nesse caso deve ser usado o seguinte comando
    $('#modal_progresso_venda').modal('hide'); $('button').button('reset');

**Comment by filipecoelho** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js
