### ISSUE TITLE
Relatório DRE

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#101]
Desenvolver o relatório do DRE, conforme anexo

**Comment by mtrystao** [comment]
[DRE CNR.xlsx](https://github.com/jheizerwandel/webliniaerp-web/files/93442/DRE.CNR.xlsx)

**Comment by filipecoelho** [comment]
Tempo estimado: 40h

**Comment by rafaelqw** [comment]
Alterações WEB
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/plano_contas-controller.js
- plano_contas.php

Alterações API
- controller/ModeloDREController.php
- controller/PlanoContasController.php
- dao/ModeloDREDao.php
- dao/PlanoContasDao.php

Alterações BD

- ALTER TABLE tbl_plano_conta 
ADD COLUMN flg_tipo_lancamento VARCHAR(100) NULL AFTER id_ref,
ADD COLUMN id_modelo_dre INT NULL AFTER flg_tipo_lancamento;

- Criar Tabela Modelo DRE
CREATE TABLE tbl_modelo_dre (
id INT NOT NULL,
flg_tipo VARCHAR(45) NULL,
descricao VARCHAR(45) NULL,
flg_associativo INT NULL,
dsc_formula VARCHAR(45) NULL,
id_empreendimento INT NULL,
PRIMARY KEY (id));

**Comment by filipecoelho** [comment]
Segue resumo do teste:

- [ ] A coluna TIPO no Relatório DRE não precisa aparecer
- [ ] As linhas dos tipos Resumo (TOP) e Soma (SUM) precisa aparecer em negrito
- [ ] Os valores precisam ter o símbolo da moeda (R$)
- [ ] Os valores do tipo Receita (REVENUE) precisam aparecer em azul
- [ ] Os valores do tipo Despesa (EXPENSE) precisam aparecer em vermelho
- [ ] Os valores dos tipos Resumo (TOP) e Soma (SUM), precisam aparecer:
  - quando for negativo em VERMELHO
  - quando for positivo em VERDE
  - quando for zerado em PRETO
