### ISSUE TITLE
Inserir NCM 61011300

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1011]
POR FAVOR, QUEIRAM INSERIR O NCM 61011300, PRECISO FINALIZAR O CADASTRO DE PRODUTOS DA BODY STYLE E ESSE NCM NAO ESTA DISPONIVEL PARA ASSOCIACAO

**Comment by Kenzo13** [comment]
Eu fiz algumas pesquisas desse NCM em 2018 e ele não foi encontrado. Provavelmente deve ter expirado, então melhor seria usar outro NCM para finalizar o cadastro.
