### ISSUE TITLE
Abrir extrato do cliente pela tela de Clientes & Usuários

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1014]
Incluir opçãp de abrir extrato do cliente ao cliclar no saldo do mesmo na tela: Módulos >> Clientes & Usuários

**Comment by Kenzo13** [comment]
Alterações Web

- clientes.php
- extrato.php
- js/angular-controller/clientes-controller.js
- js/angular-controller/extrato-controller.js
- js/angular-controller/pedido_transferencia-controller.js

**Comment by filipecoelho** [comment]
Qual o problema com esse chamado?

**Comment by Kenzo13** [comment]
O problema foi a falta do CTRL + SHIFT + R
Testado e ok

**Comment by mtrystao** [comment]
o formato da data inicial esta em ingles e da data final esta em brasileiro

**Comment by mtrystao** [comment]
nao esta trazendo nenhuma informacao no relatorio

**Comment by mtrystao** [comment]
testado e ok
