### ISSUE TITLE
Problema na entrada de estoque

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#1016]
Por algum motivo, quando é clicado para selecionar um produto está entrando na validação de vinculação de produto existente e não deveria. Precisamos capturar o motivo do erro para tratarmos.

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/estoque-controller.js

**Comment by LEANDROCOELHO84** [comment]
não esta mais substituindo os produtos ao vincular entrada de nota
