### ISSUE TITLE
Adicionar opção de controlar por validade na entrada de estoque

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#1017]
Precisa adicionar a opção de controlar por validade na entrada de estoque

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/estoque-controller.js
- estoque.php

**Comment by LEANDROCOELHO84** [comment]
ao cadastrar o produto aparece a chave de controlar por validade, salva e aparece na relação dos produtos um botão para configurar a validade e quantidade.
quando e verificado no cadastro do produto na aba estoque o produto esta permanece com a chave de controlar produto desativada... 
porem quando ativa a chave de controlar produto as configurações de entrada retornaram conforme cadastrado na entrada

**Comment by filipecoelho** [comment]
@LEANDROCOELHO84 Leandro não deu pra entender nada!

**Comment by LEANDROCOELHO84** [comment]
ja corrigi o veja se esta melhor para entender
