### ISSUE TITLE
Produtos controlados por validade zerando o valor no pdv

### ISSUE THREAD

**Issue by lukasqw** [WebliniaERP/webliniaerp-web#1026]
Produtos controlados por validade quando são adicionado utilizando o leitor de código de barras ficam com o valor zerado ate que algo atualize o valor total da venda , a mesma coisa ocorre quando quando adicionamos o produto pela pesquisa do produto ao invés de utilizar o modal de pesquisa de produto no PDV

**Comment by filipecoelho** [comment]
resolvido pelo chamado #1043
