### ISSUE TITLE
Erro no relatório Movimentação de Caixa

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1027]
Na garagem, o relatório "movimentação de caixa" o valor dos cartões de crédito e débito está diferente do valor total.

**Comment by Kenzo13** [comment]
No relatório de fechamento de caixa, parece estar acontecendo o mesmo erro, a soma total das vendas não é a soma do dinheiro, CC e CD.

**Comment by lukasqw** [comment]
Foram realizados teste onde foi identificado que o problema na verdade é uma má interpretação do relatório, já que a soma dos valores  em dinheiro, cc , cd possuem a soma de todas as entradas no caixa tanto quanto venda como pagamento avulso, o problema era que o cliente somava todos os valores da forma de pagamento e tentava comparar com o total de vendas , se tiver algum pagamento avulso no caixa terá uma diferença, mas se conferirmos na movimentação de caixa esta batendo todos os valores

**Comment by LEANDROCOELHO84** [comment]
valor do fechamento esta batendo com valor total das vendas

**Comment by mtrystao** [comment]
chamado validado

**Comment by LEANDROCOELHO84** [comment]
relatório esta batendo com os recebimentos
