### ISSUE TITLE
Selecionar forma de pagamento automaticamente ao emitir NF-e

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1029]
Cliente deseja que o campo forma de pagamento seja preenchido automaticamente de acordo com as condições de pagamento da venda.

Ex.: se nos pagamentos da venda houver pagamento parcelado, auto-selecionar a opção "A Prazo", se nos pagamentos da venda houver apenas um pagamento dentro do mês, auto-selecionar a opção "A Vista"

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/nota_fiscal-controller.js
