### ISSUE TITLE
Implementar mecanismo de atualização automática de custo de produtos que utilizam insumos

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1030]
Ao realizar a atualização do preço de custo de produtos que são usados como insumos de produtos compostos, o sistema deve recalcular automaticamente o custo desses produtos compostos, recalculando assim, os valores de venda desses produtos.

Considerações:
- permitir que esse recálculo seja configurável
- também deve ser configurável se o cliente deseja manter fixo o % da margem de lucro do produto sobre o custo ou se deseja manter fixo o valor de venda do produto
  - quando manter fixo o %, o sistema deve recalcular o valor do produto baseado no novo custo sobre o %
  - quando manter fixo o valor de venda do produto, o sistema deve recalcular o % baseado no novo custo sobre o valor de venda

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/produtos-controller.js

Alterações API:
- controller/EstoqueEntradaController.php
- controller/InventarioController.php
- controller/ProdutoController.php
- dao/PrecoProdutoDao.php
- index.php
- controller/PrecoProdutoController.php
