### ISSUE TITLE
Clicar mais de uma vez rapidamente no momento de salvar um sangria duplica ela

### ISSUE THREAD

**Issue by lukasqw** [WebliniaERP/webliniaerp-web#1031]
se o usuário clicar três vezes rapidamente no botão de salvar a sangria ira salvar três iguais

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js
- pdv.php

**Comment by LEANDROCOELHO84** [comment]
o erro ainda ocorre caso o computador do cliente seja muito lento para processar o comando de bloquear o botão
