### ISSUE TITLE
Relatorios de Produtos em Estoque

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1034]
favor inserir no relatorio de produtos em estoque a coluna intermediario 2

**Comment by rafaelqw** [comment]
Alterações WEB:
- rel_total_produto_estoque.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by mtrystao** [comment]
coluna sendo apresentada corretamente no relatorio

**Comment by mtrystao** [comment]
coluna sendo apresentada corretamente, testado e ok

**Comment by mtrystao** [comment]
testado e ok
