### ISSUE TITLE
Problema ao vender produto que esta habilitado controle de validade

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1043]
O Jheizer implementou um chamado que trata a questão de informar a validade no PDV, ativando a configuração no produto Controlar Validade.
No PDV, ao adicionar este produto pelo codigo de barras, não esta abrindo a janela p/ seleção das quantidades, como funciona pela tela de pesquisa.

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js
