### ISSUE TITLE
Implementar validação de lançamentos financeiros usando a nova regra de bordero

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1044]
Foi implementado o Bordero de Conferencia de Caixa.
Quando o empreendimento estiver ativado para usar essa configuração, os valores do caixa fechado não deverão mais ser visualizados no financeiro.

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok funcionando como deveria!
