### ISSUE TITLE
Incrementar timeout da requisição de gravação da venda e todas as outras requisições

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1045]
Hoje o processo de fechamento de venda consulta dados na tabela de movimentação de estoque.
Essa tabela tem milhões de registros e demora para executar a query.
A intenção é aumentar o tempo da requisição para que não ocorra mais o problema de dar 502 GATEWAY TIMEOUT na requisição.

**Comment by rafaelqw** [comment]
Alteração realizada!
