### ISSUE TITLE
Entrada de nota duplica varias vezes

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1046]

**Comment by LEANDROCOELHO84** [comment]
ao lança uma nota de entrada no estoque e não informar o fornecedor o sistema esta salvando a nota e incluindo os produtos no estoque

**Comment by rafaelqw** [comment]
Alterações API:
- controller/EstoqueEntradaController.php

Alterações WEB:
- js/angular-controller/estoque-controller.js

**Comment by LEANDROCOELHO84** [comment]
testado. não esta dando mais para dar entrada na nota sem as informações
e esta indicando onde esta faltando a informação
