### ISSUE TITLE
Botao Salvar e Msg de Aguarde

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1056]
EM todo o sistema onde existir um botao salvar ao clicar nele esse botao devera ser substituido pela mensagem Por favor, aguarde!! essa acao tera como objetivo evitar que processos sejam duplicados em decorrencia de varios cliques ao mesmo tempo que os usuarios estao realizando

**Comment by lukasqw** [comment]
- [] Dashboard 
- [] Produtos
- [] Vitrine
- [] Fabricantes
- [] Fornecedores
- [] Importadores
- [] Categorias
- [] Lançamentos Financeiros
- [] Vendas
- [] Caixas
- [] Clientes/Usuários
- [] Grupos de Comissão
- [] Configurações
- [] Empreendimentos
- [] Depósitos
- [] Contas Bancárias
- [] Maquinetas de Cartão de Crédito
- [] Natureza de Operação
- [] Autorizar descontos
- [] Faixas de Descontos
- [] Mapa de Clientes
- [] Estoque Analítico
- [] Produtos Vencidos
- [] Produtos a Vencer
- [] Produtos em Estoque
- [] Produtos c/ Estoque Min.
- [] Vendas por Categorias
- [] Vendas por Produto
- [] Vendas por Produto por Mês
- [] Vendas por Cliente
- [] Vendas por Vendedor
- [] Fechamento Mensal
- [] Contas a Receber
- [] Contas a Pagar
- [] Resumos de Caixas
- [] Movimentação de Caixa
- [] Pagamentos a Fornecedores
- [] Movimentação de Estoque
- [] Pedidos
- [] Agenda
- [] PDV
- [] Devolução
- [] Notas Fiscais
- [] Desejos
- [] Extrato
- [] Base Tributária
- [] Especialização NCM
- [] Regime Especial
- [] Regra Tributos 
- [] Situação Especial
- [] Zoneamento
- [] Operações
- [] Controle de Estoque
- [] Inventário
- [] Baixa Manual
- [] Transferência
- [] Ordem de Produção
- [] Limpeza de Estoque
- [] Enviar Mercadoria
- [] Pedidos Personalizados
- [] Controle NF-e
- [] Perfil
- [] Vendas Vendendor
- [] Mov. de Caixa
- [] Controle de Mesas
- [] Separar Venda
- [] Controle de Atendimento
- [] Agenda de Atendimento
- [] Controle  de Prótese
- [] Serviços
- [] Diário de Atendimento
- [] Ficha Paciente
- [] Produtos
- [] Vendas por Cliente
- [] Nota Fiscal
- [] Saldo Devedor de Clientes
- [] Regras de Serviço
- [] Ordens de Servicos
- [] Nota Fiscal de Serviços
- [] Mov. de Caixa p/ Periodo
- [] Sangrias
- [] Novo Pedido Personalizado
- [] Vendas por Deposito
- [] Vendas por Dia
- [] Vendas por Vendedor Diário
- [] Vendas por Fabricante
- [] Curva ABC
- [] Pedido de Mesa
- [] Mapa de Visitantes
- [] Clientes
- [] Posição de Estoque
- [] DRE
- [] Planejamento de Plano de Contas
- [] Log
- [] Hora a Hora
- [] Vendas por Vendedor por Periodo
- [] Aniversariantes
- [] Posição de Estoque
- [] Mesas
- [] Relatorio Caixa Borderô
- [] Vendas por Mesa
- [] Compras por Produto
- [] Compras Por Natureza de Produto
- [] Despesas por Plano de Contas
- [] Vendas por vendedor anual
- [] Vendas por cliente anual
- [] Vendas por UF
- [] Vendas com desconto

**Comment by lukasqw** [comment]
Alterações WEB:
 - caixas.php
 - categorias.php
 - clientes.php
 - contas.php
 - controle-mesas.php
 - empreendimento_config.php
 - empreendimentos.php
 - fabricantes.php
 - fornecedores.php
 - grupo_comissao.php
 - importadores.php
 - log.php
 - mesas.php
 - notas-fiscais.php
 - ordem-servico.php
 - pdv.php
 - pedidos_fornecedores.php
 - rel_caixas.php
 - rel_curvas_abc.php
 - rel_fechamento_mensal.php
 - rel_pagamentos.php
 - rel_pagamentos_fornecedor.php
 - rel_posicao_estoque.php
 - rel_produtos_vencer.php
 - rel_saldo_devedor_cliente.php
 - rel_total_vendas_cliente.php
 - rel_vendas_deposito.php
 - rel_vendas_periodo.php
 - rel_vendas_vendedor_dia_dia.php
 - relatorio-compras-consolidado-natureza-produto.php
 - relatorio-compras-consolidado-produto.php
 - relatorio-despesas-plano-contas.php
 - relatorio-total-vendas-cliente-anual.php
 - relatorio-total-vendas-estados-anual.php
 - relatorio-total-vendas-vendedor-anual.php
 - relatorio-vendas-desconto.php
 - relatorio-vendas-mesa.php
 - js/angular-controller/baixa_estoque-controller.js
 - js/angular-controller/base_tributaria-controller.js
 - js/angular-controller/caixas-controller.js
 - js/angular-controller/categorias-controller.js
 - js/angular-controller/clientes-controller.js
 - js/angular-controller/contas-controller.js
 - js/angular-controller/controle-mesas_controller.js
 - js/angular-controller/controle_nfe-controller.js
 - js/angular-controller/dashboard-controller.js
 - js/angular-controller/depositos-controller.js
 - js/angular-controller/devolucao-controller.js
 - js/angular-controller/empreendimento_config-controller.js
 - js/angular-controller/empreendimentos-controller.js
 - js/angular-controller/especializacao_ncm-controller.js
 - js/angular-controller/estoque-controller.js
 - js/angular-controller/extrato-controller.js
 - js/angular-controller/fabricantes-controller.js
 - js/angular-controller/faixa-desconto-controller.js
 - js/angular-controller/fornecedores-controller.js
 - js/angular-controller/grade-controller.js
 - js/angular-controller/grupo-comissao-vendedor-controller.js
 - js/angular-controller/importadores-controller.js
 - js/angular-controller/inventario-controller.js
 - js/angular-controller/lancamentos-controller.js
 - js/angular-controller/log-controller.js
 - js/angular-controller/maquinetas-controller.js
 - js/angular-controller/mesas-controller.js
 - js/angular-controller/notas_fiscais-controller.js
 - js/angular-controller/operacao-controller.js
 - js/angular-controller/ordem_servico-controller.js
 - js/angular-controller/pdv-controller.js
 - js/angular-controller/pedido_transferencia-controller.js
 - js/angular-controller/pedido_transferencia_recebido-controller.js
 - js/angular-controller/pedidos_fornecedores-controller.js
 - js/angular-controller/perfis-controller.js
 - js/angular-controller/planejamento_plano_contas-controller.js
 - js/angular-controller/plano_contas-controller.js
 - js/angular-controller/posicao_estoque-controller.js
 - js/angular-controller/procedimentos-controller.js
 - js/angular-controller/produtos-controller.js
 - js/angular-controller/regime_especial-controller.js
 - js/angular-controller/regra_servico-controller.js
 - js/angular-controller/regra_tributos-controller.js
 - js/angular-controller/rel-curvas-abc-controller.js
 - js/angular-controller/rel-diario-vendedor-controller.js
 - js/angular-controller/rel-movimentacao-estoque-controller.js
 - js/angular-controller/rel-periodo-vendedor-controller.js
 - js/angular-controller/rel-vendas-categoria_controller.js
 - js/angular-controller/rel-vendas-deposito-controller.js
 - js/angular-controller/rel-vendas-fabricante-controller.js
 - js/angular-controller/rel_caixas-controller.js
 - js/angular-controller/rel_movimentacao_caixa_periodo-controller.js
 - js/angular-controller/rel_pagamentos-controller.js
 - js/angular-controller/rel_posicao_estoque-controller.js
 - js/angular-controller/relatorio-analitico-estoque-controller.js
 - js/angular-controller/relatorio-compras-consolidado-natureza-produto.controller.js
 - js/angular-controller/relatorio-compras-consolidado-produto.controller.js
 - js/angular-controller/relatorio-consolidado-caixa-controller.js
 - js/angular-controller/relatorio-contas-pagar.js
 - js/angular-controller/relatorio-despesas-plano-contas.controller.js
 - js/angular-controller/relatorio-fechamento-mensal-controller.js
 - js/angular-controller/relatorio-saldo-devedor-cliente-controller.js
 - js/angular-controller/relatorio-sangria.js
 - js/angular-controller/relatorio-total-produto-estoque-controller.js
 - js/angular-controller/relatorio-total-vendas-cliente-anual.controller.js
 - js/angular-controller/relatorio-total-vendas-cliente-controller.js
 - js/angular-controller/relatorio-total-vendas-estados-anual.controller.js
 - js/angular-controller/relatorio-total-vendas-vendedor-anual.controller.js
 - js/angular-controller/relatorio-total-vendas-vendedor-controller.js
 - js/angular-controller/relatorio-vendas-desconto.controller.js
 - js/angular-controller/relatorio-vendas-mesa.controller.js
 - js/angular-controller/relatorio_dre-controller.js
 - js/angular-controller/relatorio_pagamentos_fornercedor-controller.js
 - js/angular-controller/relatorio_produtos_vencer-controller.js
 - js/angular-controller/relatorio_vendas_hora_a_hora-controller.js
 - js/angular-controller/relatorio_vendas_periodo_controller.js
 - js/angular-controller/relatorio_vendas_produtos-controller.js
 - js/angular-controller/relatorio_vendas_produtos-mes-controller.js
 - js/angular-controller/situacao_especial-controller.js
 - js/angular-controller/vendas-controller.js
 - js/angular-controller/zera-estoque-controller.js
 - js/angular-controller/zoneamento-controller.js

**Comment by LEANDROCOELHO84** [comment]
[]  Dashboard
[] Produtos
[] Vitrine
[] Fabricantes
[] Fornecedores
[] Importadores
[] Categorias
[] Lançamentos Financeiros
 []Vendas
[] Caixas
[] Clientes/Usuários
 [] Grupos de Comissão
[] Configurações
[] Empreendimentos
[] Depósitos
[] Contas Bancárias
[] Maquinetas de Cartão de Crédito
[] Natureza de Operação
 [ ] Autorizar descontos
[] Faixas de Descontos
[] Mapa de Clientes
[] Estoque Analítico
[] Produtos Vencidos
[] Produtos a Vencer
[] Produtos em Estoque
[] Produtos c/ Estoque Min.
[] Vendas por Categorias
[] Vendas por Produto
[] Vendas por Produto por Mês
[] Vendas por Cliente
[] Vendas por Vendedor
[] Fechamento Mensal
[] Contas a Receber
[] Contas a Pagar
[] Resumos de Caixas
[]  Movimentação de Caixa
[] Pagamentos a Fornecedores
[] Movimentação de Estoque
[] Pedidos
[] Agenda
[] PDV
[] Devolução
[] Notas Fiscais
[] Desejos
[] Extrato
[] Base Tributária
[] Especialização NCM
[] Regime Especial
[] Regra Tributos
[] Situação Especial
[] Zoneamento
[] Operações
[] Controle de Estoque
[] Inventário
[] Baixa Manual
[] Transferência
[] Ordem de Produção
[] Limpeza de Estoque
[] Enviar Mercadoria
[] Pedidos Personalizados
[] Controle NF
[] Perfil
[] Vendas Vendendor
[] Mov. de Caixa
[] Controle de Mesas
[] Separar Venda
[] Serviços
[] Produtos
[] Vendas por Cliente
[] Nota Fiscal
[] Saldo Devedor de Clientes
[] Regras de Serviço
[] Ordens de Servicos
[] Nota Fiscal de Serviços
[] Mov. de Caixa p/ Periodo
[] Sangrias
[] Novo Pedido Personalizado
[] Vendas por Deposito
[] Vendas por Dia
[] Vendas por Vendedor Diário
[] Vendas por Fabricante
[] Curva ABC
[] Pedido de Mesa
[] Mapa de Visitantes
[] Clientes
[] Posição de Estoque
[] DRE
[] Planejamento de Plano de Contas
[] Log
[] Hora a Hora
[] Vendas por Vendedor por Periodo
[]Aniversariantes
[] Posição de Estoque
[] Mesas
[] Relatorio Caixa Borderô
[] Vendas por Mesa
[] Compras por Produto
[] Compras Por Natureza de Produto
[] Despesas por Plano de Contas
[] Vendas por vendedor anual
[] Vendas por cliente anual
[] Vendas por UF
[] Vendas com desconto

**Comment by Kenzo13** [comment]
Telas com defeito
Relatório de vendas por Vendedor por período.
Relatório de Vendas por Vendedor Diário
Pedidos Personalizados

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
