### ISSUE TITLE
Importacao de XML Codigo de Barras Duplicado

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1057]
o sistema esta permitindo cadastrar mais de uma vez um numero de codigo de barras o que pela tela de produtos e proibido, o sistema nao pode permitir que um numero de codigo de barras seja cadastrado novamente

**Comment by lukasqw** [comment]
Alterações WEB:
 - estoque.php
 - estoque-controller.js
