### ISSUE TITLE
Vendas por vendedor

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1058]
No relatório vendas por vendedor, quando apertamos o botão para detalhar venda, o campo que deveria informar o cliente, está informando o vendedor.

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/relatorio-vendas-vendedor-controller.js
- rel_vendas_vendedor.php

Alterações API:
- dao/RelatorioDao.php
