### ISSUE TITLE
Ajustar tela de vendas p/ incluir colunas adicionais

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1068]
- [x] Nº NF-e
- [x] Data da Coleta
- [x] Razão Social, caso cliente PJ (dentro de um small, numa segunda linha)

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/vendas-controller.js
- vendas.php

Alterações API:
- dao/VendaDao.php
