### ISSUE TITLE
Tratar reset da tela do PDV quando não é possível estabelecer comunicação c/ o Client

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1069]
Ao tentar emitir um CF-e (NFC-e ou SAT) e não é possível estabelecer comunicação com o programa Client, exibe-se uma mensagem notificando do problema, no entanto, não é feito um reset da tela ou botões para que seja possível fazer nova tentativa de processar o documento.

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
