### ISSUE TITLE
Empreendimento Tabacaria Raja 2

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1072]
Precisamos atualizar a lista de produtos do empreendimento Tabacaria Raja 02, sugestão, deletar todos os produtos desse empreendimento e compartilhar novamente os produtos a partir da Tabacaria Raja 01

**Comment by LEANDROCOELHO84** [comment]
foi zerado os produtos e compartilhado novamente.
desta forma todos os produtos da Raja1 esta na Raja2
