### ISSUE TITLE
Empreendimento Corpo em Forma

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1073]
Retomei a conversa ontem com o Cliente Corpo em Forma e ele ira testar o sistema por 20 dias e dando tudo certo durante esse período ele ira contratar nossos serviços para as 03 lojas dele, precisamos deletar todos os produtos do empreendimento ja existente e copiar para esse empreendimento a lista de produtos da X3 Suplementos Loja Física

**Comment by LEANDROCOELHO84** [comment]
Produtos ja deletados e replicados do empreendimento X3 Loja fisica.
