### ISSUE TITLE
Relatório de Vendas Diário

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#108]
O relatório deve apresentar as informacoes da tela de vendas, porem, deve existir um campo no rodapé da página que indique qual o ticket médio das vendas durante o período selecionado

**Comment by mtrystao** [comment]
[Modelo de Relatorio Vendas Periodo.xlsx](https://github.com/WebliniaERP/webliniaerp-web/files/930097/Modelo.de.Relatorio.Vendas.Periodo.xlsx)

**Comment by BreynerDeveloper** [comment]
Implementação na API, classes Dao e controller

**Comment by rafaelqw** [comment]
Alteraçoes Web:
rel_vendas_periodo.php
 js/angular-controller/relatorio_vendas_periodo_controller.js

**Comment by matheuscaetano** [comment]
TESTADO. OK !!!
