### ISSUE TITLE
Padronizar pesquisa de clientes em todas as telas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1080]
Cliente deseja que os campos de pesquisa de clientes sejam padronizados em todas as telas.
- [x] Mapear todas as telas onde existe a possibilidade de consulta de clientes
- [x] Padronizar, seguindo os critérios de maior quantidade de campos possíveis

**Comment by lukasqw** [comment]
Alterações WEB:
- js/angular-controller/clientes-controller.js
- js/angular-controller/lancamentos-controller.js
- js/angular-controller/ordem_servico-controller.js
- js/angular-controller/relatorio-saldo-devedor-cliente-controller.js
- js/angular-controller/relatorio-total-vendas-cliente-controller.js
- js/angular-controller/vendas-controller.js
