### ISSUE TITLE
Incluir soma de peso de produtos no Romaneio de Entrega

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1084]
Para facilitar a alocação dos volumes necessários para expedição e transporte, o cliente deseja visualizar no Romaneio de Entrega uma coluna com a informação do peso total (Bruto e Líquido) de todos os produtos

**Comment by rafaelqw** [comment]
Alterações API:
- dao/NotasRomaneioEntregaDao.php
- dao/RomaneioEntregaDao.php
- util/rel_templates/romaneio_entrega.php
