### ISSUE TITLE
Possibilidade de exportar lista de NF-e emitidas p/ Excel

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1085]
Cliente deseja que seja possível exportar a lista de NF-e emitidas de um periodo filtrado para o Excel

**Comment by rafaelqw** [comment]
Alterações WEB:
- notas-fiscais.php
- js/angular-controller/notas_fiscais-controller.js

**Comment by LEANDROCOELHO84** [comment]
erros
notas-fiscais.php:2708   
notas-fiscais.php:2709
notas-fiscais.php:2708
notas-fiscais.php:2709
angular.js:13294
