### ISSUE TITLE
Melhorar mecanismo de forma de pagamento no PDV p/ El Shaddai

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1086]
Cliente deseja que seus vendedores/representantes não possam alterar manualmente as datas pré-geradas dos boletos de pagamento de um pedido de venda
- [x] Ativar apenas campo de qtd de parcelas
- [x] Calcular a primeira data c/ D+10
- [x] Bloquear campos das datas geradas pelo calculo de tempo
- [x] Incluir campo de qtd de dias p/ cada parcela
  - ao atualizar o valor desse campo, recalcular a data automaticamente
- Ao pre-emitir a nota, recalcular as datas das faturas e atualizar os lançamentos financeiros respectivos

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/pdv-controller.js
- pdv.php
