### ISSUE TITLE
Ocultar produtos cadastrados como matéria prima no PDV

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1087]
No PDV os produtos com o atributo Matéria Prima (Insumo) não podem aparecer no PDV para venda

**Comment by rafaelqw** [comment]
Alterações API:
- controller/NfeController.php
- index.php

Alterações WEB:
- js/angular-controller/notas_fiscais-controller.js

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/pdv-controller.js
