### ISSUE TITLE
Incluir mais opções de filtro de produtos

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1088]
Cliente deseja filtrar os produtos por tipo:
- [x] Tipo de Produto (Normal, Composto, Serviço)
- [x] Sub-tipo (Matéria Prima)

**Comment by lukasqw** [comment]
Alterações WEB:
- produtos.php
- js/angular-controller/produtos-controller.js

**Comment by Kenzo13** [comment]
Testado e Okay

**Comment by LEANDROCOELHO84** [comment]
testado e funcionando
