### ISSUE TITLE
Corrigir problema de vinculo de lançamento financeiro c/ duplicata

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1097]
- Usuário realiza uma venda e registrar um pagamento em boleto
- Usuário emite NF-e referente essa venda e motor inclui duplicatas baseadas nos boletos da venda
- Usuário fecha o caixa
- Sistema replica os lançamentos financeiros p/ outra conta e perde-se o vinculo do lançamento financeiro c/ a duplicata (`tbl_duplicata`.`id_lancamento_financeiro`)

**Comment by lukasqw** [comment]
Alterações API:
 - dao/DashboardDao.php
 - dao/MovimentacaoCaixaDao.php

**Comment by mtrystao** [comment]
Seguem as evidencias do que eu consegui realizar em relacao a esse chamado, mas nao entendi como validar a parte parte referente a perda do vinculo, preciso de orientacao, mas ainda existe falha no momento de emitir a NF-e e considerar as duplicatas lancadas no PDV

[chamado 109u duplicata.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46eb9c9b2e8387a6cfb8ef1ab11df481394a2e702810a2693cc7f33ab0487e021b4d44be445e0945f4fdd87ef0b53a228a540cbbd16c5e75946f19abaa9e0dfd50e474d412dcfce9c85ecafa3c2ced8a8a4b391900198efe5c34a39d5985.pdf)

**Comment by mtrystao** [comment]
** Sem data de emissao da NF-e
![sem data de emissao.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46fb9197638682bd8ea9bb46e458fd9d3a55267c6b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e28b8c493d180d1b8efa5a27ed.jpg)

** Sem Numero da NF-e emitida
![sem numero da nota.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46fb9197638c96a48afbb003a05cb09a265226316546b3397f8fe62bab0021435a5918ad495c0e11aafa8f79a6be3b268a5d0aec833f5773d42103eee9dc4be05ce36ade0d97bcae8b4bcae93820e788894c3817021d8cfe4f78.jpg)

**Comment by filipecoelho** [comment]
@mtrystao qual a relação do problema relatado com o escopo do chamado?

**Comment by mtrystao** [comment]
as informacoes referentes a NF-e devam estar nos detalhes do lancamento financeiro e tb a data de emissao deveria estar na devida, isso é perda de vinculo?

**Comment by filipecoelho** [comment]
Mas esse não é o escopo do chamado.
Deve ser pontuado no chamado respectivo à demanda.

O problema do escopo só pode ser validado via BD pois é referente a estrutura do sistema.

**Comment by mtrystao** [comment]
conforme orientacao, esse chamado so pode ser validado via BD, estou voltando o mesmo para a coluna Forca Tarefa

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
