### ISSUE TITLE
Criar chaves de configurações p/ automatizar emissão de NF-e

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1102]
Criar as seguintes chaves de configuração no sistema, a fim de disponibilizar uma opção de emissão de NF-e One Click:
- Operação Interna Padrão (```id_operacao_interna_padrao```)
  - A idéia é que essa seja a operação de venda p/ dentro do estado padrão (UF Origem = UF Destino)
- Operação Externa Padrão (```id_operacao_externa_padrao```)
  - A idéia é que essa seja a operação de venda p/ fora do estado padrão (UF Origem != UF Destino)
- Transportadora Padrão (```id_fornecedor_transportadora_padrao```)
- Motoboy Padrão (```id_fornecedor_motoboy_padrao```)
- Agência dos Correios Padrão (```id_fornecedor_correios_padrao```)
- Peso Máximo por Volume (```qtd_peso_maximo_volume```)
- Incluir boletos da venda nas duplicatas da nota (```flg_incluir_boletos_venda_duplicata_nfe```)

**Comment by rafaelqw** [comment]
As alterações estão no chamado #1103
