### ISSUE TITLE
Informar dados automaticamente na NF-e baseando-se em configurações

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1103]
Ao abrir a tela de emissão de NF-e, o sistema deve ler as seguintes configurações e pré-seleciona-las:
- Operação (Interna ou Externa)
- Transportadora
  - caso tenha um produto de frete na venda
- Volumes
  - calcular automaticamente o peso dos produtos da venda e incluir os volumes automaticamente baseado na configuração (Peso Máximo por Volume)

**Comment by rafaelqw** [comment]
Alterações API:
- controller/LancamentosFinanceirosController.php
- controller/SigepController.php
- dao/NotasRomaneioEntregaDao.php
- dao/SigepDao.php
- dao/VendaDao.php
- index.php

Alterações WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/nota_fiscal-controller.js
- js/angular-controller/pdv-controller.js
- js/angular-controller/vendas-controller.js
- vendas.php

Alterações BD:
- ```INSERT INTO tbl_status_venda (dsc_status) VALUES ('Processando Faturamento');
INSERT INTO tbl_status_venda (dsc_status) VALUES ('Erro no Faturamento');
ALTER TABLE tbl_vendas ADD COLUMN id_forma_entrega_ezcommerce INT NULL AFTER ids_movimentacao_estoque;```
