### ISSUE TITLE
Faturamento somando devoluções

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1112]
Foi apurado que o total de faturamento esta somando as devoluções lançadas no PDV.
Apurado no treinamento feito com o Leandro da Top Suplementos

**Comment by filipecoelho** [comment]
@Kenzo13 informar os arquivos que foram alterados e subir p/ o Git

**Comment by Kenzo13** [comment]
Alterações API:
- dao/DashboardDao.php

**Comment by Kenzo13** [comment]
Testado e okay
