### ISSUE TITLE
Ao dar baixa de cartões criar despesa detalhada por maquineta, forma de pagamento e bandeira

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1113]
Através dos Lançamentos Financeiros, usando a função de selecionar lançamentos para dar baixa, na janela que é aberta para validação dos lançamentos, o cliente deseja que seja expandido os valores das taxas por bandeira para facilitar conferência posterior.

Ao concluir a baixa dos lançamentos, o sistema cria uma despesa automática para cada bandeira com seu respectivo valor.

**Comment by lukasqw** [comment]
Alterações WEB:
 - lancamentos.php
 - js/angular-controller/lancamentos-controller.js

Alterações API:
 - dao/LancamentosFinanceirosDao.php
 - controller/LancamentosFinanceirosController.php

**Comment by mtrystao** [comment]
Nao localizei a despesa criada automaticamente correspondente a taxa da maquineta

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
