### ISSUE TITLE
Problemas com Taxa de Maquineta após atualizar lançamento

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#1114]
Ao realizar alguma venda com forma de pagamento relacionada a Cartão e depois editar/dar baixa nesse lançamento está zerando a taxa de maquineta

**Comment by filipecoelho** [comment]
WEB:
- js/angular-controller/lancamentos-controller.js
- lancamentos.php

API:
- controller/LancamentosFinanceirosController.php
- dao/MaquinetaDao.php
