### ISSUE TITLE
Implementar mecanismo de baixa de lançamentos financeiros em lote

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1115]
Implementar função de dar baixa de lançamentos de contas a pagar e receber igual ao Relatório de Contas a Receber e remover a função do relatório

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/lancamentos-controller.js
- lancamentos.php
- rel_pagamentos.php

Alterações API:
- controller/LancamentosFinanceirosController.php
- dao/LancamentosFinanceirosDao.php
- dao/PagamentoClienteDao.php
- dao/PagamentoFornecedorDao.php
