### ISSUE TITLE
NOTA DE ENTRADA

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1118]
quando le o arquivo xml de um produto que esta cadastrado como unidade de fração não carrega o campo de fração na entrada de nota.
grava como unidade e não fração

**Comment by rafaelqw** [comment]
Alterações WEB:
- estoque.php
- js/angular-controller/estoque-controller.js

Alterações API:
- controller/EstoqueEntradaController.php
