### ISSUE TITLE
Pre Fechamento de comanda

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1121]
Cliente deseja ter um pré fechamento de suas comandas, para que os clientes possam fechar o pedido e só depois no caixa, finalizar a comanda e imprimir o cupom.

**Comment by lukasqw** [comment]
Alterações WEB:
 - controle-mesas.php
 - js/angular-controller/controle-mesas_controller.js

Alterações API:
 - index.php
 - dao/ContaBancariaDao.php
 - controller/ContaBancariaController.php

**Comment by LEANDROCOELHO84** [comment]
Pre comanda funcionando corretamente
![photo_2019-02-18_14-39-50.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46f89c95378dbcfbdfb8e60ef40fbdc5717976276457fa6625d5a164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff58a86453f1b00188cfe5c30a99c4acd5ee406.jpg)
