### ISSUE TITLE
Observações do orçamento

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1123]
Observações do orçamento não esta  tratando o texto corretamente .
o campo de observações esta com as litras pequeninas

**Comment by lukasqw** [comment]
Alterações API:
 - util/rel_templates/comprovante_venda.php
 - util/rel_templates/comprovante_ordem_servico.php

**Comment by LEANDROCOELHO84** [comment]
ordem de serviço esta aparecendo modulo de recebimento do pdv

**Comment by LEANDROCOELHO84** [comment]
![Capturar.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46cb958a379791a89dabf301b44fff9e2c4533317346f67d76d4bb7cbe477d52590d4ea4460e5f45fdf8db79aeb12e6c981e5ab38532022d8c6853beb2901eb80bbb258e4f80b7bc8d4cc1ed3e2df5c6.PNG)
