### ISSUE TITLE
Problemas na entrada de nota

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#1126]
- [x] Valor de custo não está sendo salvo na tabela de Item Estoque Entrada
- [x] Quantidade fracionada não está sendo salvo na tabela de Item Estoque Entrada
- [x] Ao carregar um XML não está identificando os produtos que são para controlar estoque fracionado
- [x] A mascara de entrada de valor fracionado não está funcionado corretamente.
  - Ex.: Tente digitar 0,6000
- [x] Campo de Qtd no modal de inclusão de produtos manualmente precisa ter a mesma quantidade de casas decimais

**Comment by Kenzo13** [comment]
Testado e okay
