### ISSUE TITLE
Listagem de solicitações de transferências de estoque não respeitando a ordem de data

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1127]
Empreendimento D.A. - 1 Anchieta

![erro-data.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550338e01befa51300278352/125516c66e82c728ace21e0d46ed86882ccf87a89be8fd0fe64de29b234324676b5ee17e2683b270eb437e075c591cac495f0944fdf88879f4be3b62964e49bc8f3900299f7744eeaa880dbe06b0218e4c8cbfba8d49c4ec3a25e199c2.png)

**Comment by Kenzo13** [comment]
Alterações WEB
- js/angular-controller/pedido_transferencia-controller.js

**Comment by LEANDROCOELHO84** [comment]
esta funcionando corretamente conforme solicitado no chamado
![ transferências de estoque .png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46a88088228c90af8afb1c89aa5ef9953a0623766901b03f7f94f62dff0037431f1d11f6140b1b56f6eb8c2df0b73474db095deed73f5f7cc16b11adb9834ded09bd32975dc7e7e2de139db17770a599855d3f170f198cfa5932a49d4bcb59ff4ce95f18.png)

**Comment by Kenzo13** [comment]
testado e ok

**Comment by mtrystao** [comment]
Listagem em ordem cronologica correta

**Comment by mtrystao** [comment]
Listagem em ordem cronologica correta, testado e ok

**Comment by mtrystao** [comment]
testado e ok
