### ISSUE TITLE
Não está exibindo o solicitante da transferência de estoque

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1128]
Na tela de solicitação de transferência não está exibindo o nome do usuário que solicitou o pedido de transferência nem a data da solicitação.

**Comment by Kenzo13** [comment]
Alterações Web
-  js/angular-controller/pedido_transferencia-controller.js
-  js/angular-controller/pedido_transferencia_recebido-controller.js

Alterações Api
- dao/TransferenciaEstoqueDao.php

**Comment by filipecoelho** [comment]
Qual o problema com esse chamado?

**Comment by Kenzo13** [comment]
O problema do chamado foi a falta do CTRL + SHIFT + R
Testado e ok

**Comment by mtrystao** [comment]
o usuario esta sendo apresentado mas a data em que o pedido foi realizado nao

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pedido_transferencia-controller.js
- js/angular-controller/pedido_transferencia_recebido-controller.js

**Comment by Kenzo13** [comment]
Testado e ok
