### ISSUE TITLE
Corrigir implementação de retorno de pesquisa de produtos nas telas de solicitação de transferência e envio de mercadoria

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1129]
Ao tentar pesquisar um produto por nome, está preenchendo mais de uma vez o array e com isso replicando os itens na listagem

**Comment by lukasqw** [comment]
Alterações WEB:
 - estoque.php
 - estoque-controller.js

**Comment by lukasqw** [comment]
Alterações WEB:
 - pedido_transferencia.php
 - pedido_transferencia_recebido.php 
 - js/angular-controller/pedido_transferencia-controller.js
 - js/angular-controller/pedido_transferencia_recebido-controller.js
