### ISSUE TITLE
No envio de mercadoria não está respeitando a regra de qtd múltipla ao informar a quantidade a ser enviada

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1131]
No modal de inclusão de produtos na listagem de envio de mercadoria, o campo qtd a ser enviada não respeita a regra de qtd múltipla, devido não estar trazendo a qtd multipla para a tela fazer o processo de validação

**Comment by Kenzo13** [comment]
Alterações Web
- js/angular-controller/importar_produtos.controller.js

**Comment by Kenzo13** [comment]
testado e ok
