### ISSUE TITLE
Ao gerar uma venda a partir de um envio de mercadoria, disponibilizar opção para criar um lanç. financeiro de receita

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1132]
Ao clicar em gerar venda a partir deste envio, o sistema deve disponibilizar opções de pagamento da venda

**Comment by lukasqw** [comment]
Alterações WEB:
- pedido_transferencia_recebido.php;
- js/angular-controller/pedido_transferencia_recebido-controller.js

Alterações API:
- dao/TransferenciaEstoqueDao.php
- controller/TransferenciaEstoqueController.php
