### ISSUE TITLE
Implementar detalhamento do lançamento financeiro no modal de comprovante de pagamento

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1135]

**Comment by lukasqw** [comment]
Alterações WEB:
- lancamentos.php
- js/angular-controller/lancamentos-controller.js

Alterações API:
- index.php
- dao/PagamentoClienteDao.php
- dao/PagamentoFornecedorDao.php
- controller/LancamentosFinanceirosController.php

**Comment by Kenzo13** [comment]
Testado e okay
