### ISSUE TITLE
Poder pesquisar plano de contas pelo nome ignorando os acentos e caracteres especiais

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1137]
Exemplo:
Plano de Contas: Movimentação de Caixa
Pesquisa: Movimentacao
Resultado: Nenhum resultado encontrado
Pesquisa: Movimentação
Resultado: Movimentação de Caixa

**Comment by rafaelqw** [comment]
Alterações WEB:
- inventario.php
- js/angular-controller/lancamentos-controller.js
- js/app.js
- lancamentos.php
- bower_components/angular-ui-select
- js/angular-ui-select-0.20.0.js
- js/chosen_v1.4.3-hanoii
