### ISSUE TITLE
Implementar mecanismo de checagem de lançamentos financeiros

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1138]
O usuário deseja clicar e marcar o lançamento como conferido.
Ao marcar como conferido, o usuário não pode mais editar os detalhes do lançamento, apenas confirmar ou não o pagamento.

Observações:
- Incluir botão de editar na coluna Ações
- Ao clicar no botão de Status apenas questionar se quer alterar o status do pagamento ou não

**Comment by lukasqw** [comment]
Alterações BD:
 - ```ALTER TABLE tbl_pagamentos_venda ADD COLUMN flg_conferencia INT NULL DEFAULT 0 AFTER flg_possui_detalhamento;```

 - ```ALTER TABLE tbl_pagamentos_fornecedores ADD COLUMN flg_conferencia INT NULL DEFAULT 0 AFTER flg_possui_detalhamento;```

 - ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('10', 'habilitar_conferencia', 'Habilitar conferencia no financeiro', 'Habilitar conferencia no financeiro');```
