### ISSUE TITLE
Fazer log de alterações de um lançamento financeiro

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1140]

**Comment by lukasqw** [comment]
Alterações no BD:
 - ```INSERT INTO `weblinia_clientes`.`tbl_tipo_log` (`nme_tipo_log`) VALUES ('ALTERAÇÃO DE LANÇAMENTO FINACEIRO');```

Alterações WEB:
 - js/angular-controller/lancamentos-controller.js

Alterações API:
 - controller/LancamentosFinanceirosController.php
 - dao/LogDao.php

**Comment by filipecoelho** [comment]
Fiz um teste alterando os dados de um lançamento e não funcionou!
