### ISSUE TITLE
Parametrizar layout do gráfico de Vendas Hora a Hora

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1142]
- Possibilitar exibição do gráfico em formato de Linha
  - Heatmap
  - Line
- Possibilitar a troca das cores padrões do gráfico de calor

**Comment by lukasqw** [comment]
Alterações WEB:
 - dashboard.php
 - empreendimento_config.php
 - js/angular-controller/dashboard-controller.js
 - js/angular-controller/empreendimento_config-controller.js

**Comment by LEANDROCOELHO84** [comment]
- [x] Possibilitar exibição do gráfico em formato de Linha
Heatmap
Line
- [x] Possibilitar a troca das cores padrões do gráfico de calor
![Heatmap e Line.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46c0919b378f82b9cfecff6fad53f5d665043761260ea62864c7b96aea147d50575b1ff9175b5916fcf18e7da6b73d71d80e03eac3714d36976345f3e5db55ea43a82a994e8cbcbd8f48c8e13823e28b8f463c1f1755.PNG)

**Comment by mtrystao** [comment]
Chamado validado

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
