### ISSUE TITLE
Implementar opção para fixar valores de campos ao criar lançamentos financeiros

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1146]
O usuário deseja bloquear alguns campos e fixar os valores para que ele consiga incluir varios registros semelhantes em que mude apenas alguns dados.
Todos os campos podem ficar fixos.

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/lancamentos-controller.js
- lancamentos.php
