### ISSUE TITLE
Relatório de Contas a Pagar não carregando dados

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1148]
No Dashboard, ao clicar nos indicadores Total Pago aos Fornecedores e Total a Pagar, está remetendo para o Rel. Contas a Pagar com a data no formato americano, e por esse motivo, não está carregando os dados.

**Comment by lukasqw** [comment]
Alterações WEB:
- produtos.php
- js/angular-controller/produtos-controller.js

**Comment by Kenzo13** [comment]
Testeado e okay

**Comment by LEANDROCOELHO84** [comment]
testado empreendimento "ambiente de teste"

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/homologacaoerp/public_html/rel_contas_pagar.php:1) in /home/homologacaoerp/public_html/util/login/restrito.php on line 4

**Comment by Kenzo13** [comment]
Após as novas atualizações, o relatório não apresenta mais o erro
