### ISSUE TITLE
Expandir visualização de notas de uma natureza/produto no Rel. Compras por Produto

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1150]
Nos relatórios:
Compras por Produto
Compras por Natureza de Produto

Ao clicar no produto ou natureza, deve ser criado uma segunda visualização, das notas lançadas naquele item (drill-down)

**Comment by lukasqw** [comment]
Alterações WEB:
 - relatorio-entradas-produto.php
 - relatorio-compras-consolidado-produto.php
 - relatorio-compras-consolidado-natureza-produto.php
 - js/angular-controller/relatorio-entradas-produto.controller.js
 - js/angular-controller/relatorio-compras-consolidado-produto.controller.js
 - js/angular-controller/relatorio-compras-consolidado-natureza-produto.controller.js

Alterações API:
 - index.php
 - dao/RelatorioDao.php
 - controller/RelatorioController.php

**Comment by mtrystao** [comment]
chamado validado

**Comment by mtrystao** [comment]
nao estou conseguindo testar esse relatorio diz que eu nao tenho acesso a esse relatorio, mas estou usando o usuario do JJ

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
