### ISSUE TITLE
Relatório Vendas por vendedor

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1152]

**Comment by mtrystao** [comment]
[Vendas por vendedor.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46de9194278390e99fe6ad03b258fe902c4228616b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e38b8c4e3b180c1c88f85827ed.xlsx)

**Comment by mtrystao** [comment]
O Relatório de vendas por vendedor devera conter uma forma para poder inserir a meta de 02 formas
1- Mensal, onde o ADM ira inserir o valor da meta mes a mes para cada vendedor
Ex: 
Jan - R$10.000,00
Fev - R$ 20.000,00
Mar - R$ 30.000,00

2- Recorrente, o ADM ira inserir um valor de META e esse valor será o mesmo para os demais meses

OBS: devera constar tb o percentual medio de descontos que o vendedor tem aplicado mensalmente

**Comment by mtrystao** [comment]
[Vendas por vendedor.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46de9194278390e99fe6ad03b258fe902c4228616b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984ec2e23c20e38b8c4e361f051c8efd5d27ed.xlsx)

**Comment by rafaelqw** [comment]
Alterações WEB:
- clientes.php
- relatorio-total-vendas-cliente-anual.php
- js/angular-controller/relatorio-total-vendas-vendedor-anual.controller.js
- relatorio-total-vendas-vendedor-anual.php

Alterações API:

- controller/ClienteController.php
- controller/RelatorioController.php
- dao/EmpreendimentoDao.php
- dao/RelatorioDao.php
- model/UsuarioEmpreendimentoTO.php
- index.php

Alterações BD:
```ALTER TABLE tbl_usuario_empreendimento ADD COLUMN vlr_meta DOUBLE NULL AFTER id_perfil;```
