### ISSUE TITLE
Vendas por UF

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1154]

**Comment by mtrystao** [comment]
[vendas por UF.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46fe9194278390e99fe6ad03917bb2d86b56357c2301a03f32dfa17de9442a595b0e1bfa425e0d44f4fedf2ba7b73d22d8540cffcd7f1d2598694ef1e1c84afd13b0328a478fb7b98e4ec0ea3925e0838f463f0c48.xlsx)

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/relatorio-total-vendas-estados-anual.controller.js
- relatorio-total-vendas-estados-anual.php

Alterações API:
- controller/RelatorioController.php 
- dao/RelatorioDao.php
- index.php
