### ISSUE TITLE
Autorizar desconto x Alterar Vendedor

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1155]
O bloqueio de desconto funciona corretamente, contudo, é Possivel alterar o vendedor no PDV e sem a necessidade de senha, dessa forma, é possível conceder desconto maior sem a necessidade de inserir senha, e necessário que mesmo no momento de alterar o vendedor seja pedido a senha do vendedor ou criar um mecanismo que controle essa situação

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js

Alterações API:
- controller/VendaController.php
