### ISSUE TITLE
Pesquisa de produto com lentidão

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1157]
existem momentos em que o sistema fica muito lento para realizar pesquisas de produtos, lançamento de vendas e alteração de paginas, sempre após as 22h00 entre 5a e Sábado

**Comment by filipecoelho** [comment]
Creio que o problema não ocorre mais, haja visto que o problema originava-se por conta de lounges que utilizam impressoras de cozinha e estamos migrando todos para o modulo offline

**Comment by mtrystao** [comment]
Até a madrugada do Sabado estava acontecendo como foi dito pelo Allan, haja visto que o cliente Rafa irmao do Vini nao fez nenhum pagamento na recepcao, somente nos caixas e nas vendas constava como Caixa Recepcao (o exemplo esta no grupo msg enviada pelo Allan)
