### ISSUE TITLE
Incluir campo de data de baixa de lançamentos através do Rel. Contas a Receber

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1165]

**Comment by filipecoelho** [comment]
WEB:
- js/angular-controller/rel_pagamentos-controller.js
- rel_pagamentos.php

API:
- controller/LancamentosFinanceirosController.php

**Comment by LEANDROCOELHO84** [comment]
compo data de baixa esta funcionando corretamento .
porem se vc puxar a data da baixa do lançamentos financeiro não retorna lançamentos
