### ISSUE TITLE
Telefone nas notas

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1170]
Cliente deseja que o campo fone/fax fique com as informações do número do destinatário

**Comment by lukasqw** [comment]
Alterações API:
 - controller/NfeController.php

**Comment by Kenzo13** [comment]
Teste realizado e tudo ok

**Comment by mtrystao** [comment]
Numero de telefone do cliente aparecendo no campo correto da NF-e

**Comment by mtrystao** [comment]
Numero de telefone do cliente aparecendo no campo correto da NF-e, testado e ok
