### ISSUE TITLE
Problemas com natureza do produto na entrada de nota

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#1183]
- Ao alterar a natureza de operação de um produto pela tela de entrada de notas não está alterando no cadastro do produto

**Comment by filipecoelho** [comment]
@rafaelqw quais arquivos devo subir a atualização?

**Comment by Kenzo13** [comment]
Produto não está mantendo o histórico das naturezas, ele está atualizando as informações

**Comment by rafaelqw** [comment]
- [ ] Quando não seleciona para Especificar as naturezas e o Custo, não conta o custo atual do produto

**Comment by rafaelqw** [comment]
Alterações API:
- controller/EstoqueEntradaController.php
