### ISSUE TITLE
Implementar Indicador de Resumo de Caixa

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1185]
- Incluir campo para entrada de saldo inicial do mês
- Exibir o valor de resumo a partir da seguinte formula:
  - SALDO INICIAL + FAT (CONF.CAIXA) - DESPESAS REALIZADAS

**Comment by lukasqw** [comment]
Alterações WEB:
 - dashboard.php
 - empreendimento_config.php
 - js/angular-controller/dashboard-controller.js
 - js/angular-controller/empreendimento_config-controller.js

Alterações API:
 - dao/DashboardDao.php

**Comment by filipecoelho** [comment]
- [ ] Ajustar o indicador p/ pegar mais de um plano de contas no calculo de receitas diversas

**Comment by rafaelqw** [comment]
Aterações WEB:
- js/angular-controller/dashboard-controller.js
- js/angular-controller/lancamentos-controller.js
- lancamentos.php

Alterações API:
- controller/PagamentoClienteController.php
- dao/LancamentosFinanceirosDao.php
- dao/PagamentoClienteDao.php
- model/PagamentoClienteTO.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by Kenzo13** [comment]
testado e ok
