### ISSUE TITLE
Venda de produto fracionado

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1187]
No momento de fazer a venda com um produto fracionado, o cliente coloca a quantidade, porém cada casa decimal está sendo contada como se fosse uma unidade e não como se fossem gramas ou KG.

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js

**Comment by LEANDROCOELHO84** [comment]
fração esta funcionando corretamento.
"obs. a quantidade de itens não deveria somar como unidade e sim como 1 produto com isso
 divergente pode causar confusão no caixa"

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
