### ISSUE TITLE
Vendas de produto composto sem estoque

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1188]
Cliente precisa fazer venda de produtos compostos sem estoque, porém a flg "Permitir realizar venda de produtos sem estoque?" deve estar habilitada

**Comment by rafaelqw** [comment]
Alterações API:
- dao/EstoqueDao.php

**Comment by LEANDROCOELHO84** [comment]
chamado testado e funcionando

**Comment by mtrystao** [comment]
ativado para so aparecer produtos em estoque no PDV, a partir desse momento consigo ver o produto teste composto e inserir no carrinho mas no momento de concluir a vendo recebo a informacao de que o produto nao tem un disposnivel

**Comment by rafaelqw** [comment]
Alterações API:
- controller/VendaController.php

Alterações WEB:
- js/angular-controller/pdv-controller.js
- rel_vendas_produto.php

**Comment by mtrystao** [comment]
o produto composto aparece no PDV contudo, qdo vou realizar o pagamento aparece a informacao de que nao existe o produto em estoque

**Comment by mtrystao** [comment]
o produto sem estoque esta sendo apresentado normalmente no PDV e a venda sendo realizada, contudo, num 2o momento se o insumo nao tiver estoque ele continua sendo vendido normalmente, qdo na verdade nao deveria

**Comment by rafaelqw** [comment]
A principio vamos será possível realizar venda de produtos compostos por mais que os insumos não tenham estoque
