### ISSUE TITLE
Relatorio de Vendas por Cliente Anual

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1190]
No relatorio de Vendas por Cliente Anual devera ser inserido
Novos Filtros para Pesquisa: UF e Vendedor

No relatorio devera ser inserido as Colunas de: UF e Nome do Vendedor

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/relatorio-total-vendas-cliente-anual.controller.js
- relatorio-total-vendas-cliente-anual.php

Alterações API:
- controller/RelatorioController.php
- dao/RelatorioDao.php
- index.php
