### ISSUE TITLE
Criar relatorio de Autorizacao de Desconto

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1191]
Cliente La Brisa solicita a criacao de um relatorio de Autorizacao de Descontos

Segue sugestao do Relatorio anexo a esse chamado

**Comment by mtrystao** [comment]
[Autorizacao de Descontos.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46c9818e2c908ab38eeabe4ce459f5d40d433470260ab72463c7af6aaf50740b0a0c0abe4b4a5a42aaf8812ff7e36a738c0e0be5d63b5f75c73c43feb0850da313f871d51bdaebe5c01982fa3737e682854e3b1a01198bfc5a36a79943cc4abb.xlsx)

**Comment by lukasqw** [comment]
Alterações WEB:
 - relatorio-vendas-desconto.php
 - js/angular-controller/relatorio-vendas-desconto.controller.js

Alterações API:
 - index.php
 - dao/RelatorioDao.php
 - controller/RelatorioController.php

**Comment by Kenzo13** [comment]
Valor original está divergente.

**Comment by rafaelqw** [comment]
- Quando o próprio operador já possui o desconto liberado está sendo gravado como Sem autorizador.
