### ISSUE TITLE
Filtrar Perfil de Acesso na Tela de Clientes usuarios

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1192]
Na Tela de Clientes/Usuarios deve ser inserido um combo para pesquisar Cliente/Usuario por Perfil de Acesso

**Comment by lukasqw** [comment]
Alterações WEB:
 - clientes.php
 - js/angular-controller/clientes-controller.js

**Comment by mtrystao** [comment]
chamado validado

**Comment by mtrystao** [comment]
chamado validado com sucesso
