### ISSUE TITLE
Corrigir relacionamento de informações de relatórios entre empreendimentos compartilhados

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1193]
Quando você compartilha os produtos com um empreendimento, alguns relatórios acabam trazendo informações do empreendimento anterior para o novo.

- produtos em estoque
- Vendas por categoria

**Comment by lukasqw** [comment]
Alterações API:
 - controller/RelatorioController.php
 - dao/RelatorioDao.php
 - index.php

**Comment by rafaelqw** [comment]
Produtos em Estoque
- [ ] Não está filtrando pelo produto
