### ISSUE TITLE
websocket selecionar cozinha por categoria

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1194]
melhorar mecanismo de selecionar cozinha para imprimir.
Quando manda imprimir na cozinha sabemos que é uma cozinha e assim tambem no rosh. não seria necessario selecionar para qual cozinha o pedido vai.

quando é bar que são em varios ambientes aplicar modal de selecionar cozinha. 
minimizando seleção do atendente

**Comment by rafaelqw** [comment]
Alterações BD:
- ```ALTER TABLE tbl_categorias ADD COLUMN id_cozinha INT NULL AFTER pth_vetor;```

**Comment by rafaelqw** [comment]
Não tenho uma impressora para testes!

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
