### ISSUE TITLE
Lançamentos Financeiros

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1197]
- [x] Na hora que o cliente vai fazer um lançamento em Voucher está sendo obrigatório selecionar a conta bancaria e isso não deveria acontecer.
- [x] Cartões quando dou baixa não está lançando as taxas!!!
- [x] Débito quando entro no dia pra dá baixa ele já está confirmado e sem a Taxa!! 
- [x] O crédito não está confirmado , porém fiz o teste, quando dou baixa não lança a taxa!

**Comment by lukasqw** [comment]
Alterações WEB:
 - lancamentos.php
 - js/angular-controller/lancamentos-controller.js

Alterações API:
 - dao/MaquinetaDao.php
 - controller/MaquinetaController.php
 - controller/PagamentoClienteController.php
