### ISSUE TITLE
La Brisa - Nao esta aparecendo o nome dos atendente

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1199]
Na tela de vendas e no cupom das vendas na maioria dos casos nao esta aparecendo o nome do atendente mas sim o nome do caixa que recebeu o dinheiro com isso dificulta o rastreio de problemas ou dos atendimentos realizados por cada atendente

**Comment by filipecoelho** [comment]
Solução discutida:
- [ ] Garantir que o usuário que foi registrado na abertura da comanda seja mantido no fechamento da venda
- [ ] Incluir campo de responsável no cadastro da mesa e ao abrir uma comanda, automaticamente vincular este responsável. Caso não haja nenhum responsável vinculado à mesa, manter o conceito atual que utiliza o id do usuário logado no sistema no momento da abertura da comanda.
- [ ] Incluir botão na comanda p/ trocar ou informar o atendente (apenas p/ ADMIN)

**Comment by rafaelqw** [comment]
Alterações WEB:
- controle-mesas.php
- js/angular-controller/controle-mesas_controller.js
- js/angular-controller/mesas-controller.js
- mesas.php
Alterações API:
- controller/MesaController.php
- dao/MesaDao.php
- dao/VendaDao.php
- index.php
- model/MesaTO.php

**Comment by LEANDROCOELHO84** [comment]
Solução discutida:
- [] Garantir que o usuário que foi registrado na abertura da comanda seja mantido no fechamento da venda
- [] Incluir campo de responsável no cadastro da mesa e ao abrir uma comanda, automaticamente vincular este responsável. Caso não haja nenhum responsável vinculado à mesa, manter o conceito atual que utiliza o id do usuário logado no sistema no momento da abertura da comanda.
- [] Incluir botão na comanda p/ trocar ou informar o atendente (apenas p/ ADMIN)

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
