### ISSUE TITLE
La Brisa relatorio de movimentacao de caixa

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1200]
No final do relatorio de movimentacao de caixa onde constam os valores finais o campo que total descontado a tx da maquineta que deveria ser menor que o total vendido esta aparecendo maior que o total vendido

**Comment by rafaelqw** [comment]
Alterações WEB:
- rel_movimentacao_caixa.php

**Comment by Kenzo13** [comment]
O valor da sangria está sendo retirado do campo "Valor total da venda" e isso não pode acontecer

**Comment by Kenzo13** [comment]
Creio que não, vamos supor que o caixa fique aberto por 3 dias.Nesses 3 dias tivemos diversas vendas e o total do lucro foi de 1000 reais... Se eu fizer uma sangria de 500 reais, o valor total das vendas vai ficar igual a 500, causará divergências. pois vendemos 1000 e não 500. Tirar o dinheiro do caixa para guardar numa conta não deveria tirar da quantidade recebida do pagamento das vendas.

**Comment by mtrystao** [comment]
chamado validado

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
