### ISSUE TITLE
La Brisa relatorio de movimentacao de caixa

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1201]
Cliente solicita que no relatorio de movimentacao de caixa ao clicar sobre o numero da venda ele deva ser direcionado para os detalhes da venda

**Comment by lukasqw** [comment]
Alterações WEB:
 - rel_movimentacao_caixa.php

**Comment by mtrystao** [comment]
chamado validado

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
