### ISSUE TITLE
La Brisa duplicando valores durante o recebimento no PDV

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1203]
No momento em que vc esta recebendo os valores da venda no PDV e clica em Finalizar para concluir o recebimento "provavelmente o modal nao esta sendo limpo"com isso se vc clicar varias vezes os valores recebidos serao repetidos e com isso havera duplicidade nos valores recebidos e assim diferenca no fechamento do caixa

**Comment by rafaelqw** [comment]
Alterações WEB:
- pdv.php
- js/angular-controller/pdv-controller.js

**Comment by mtrystao** [comment]
chamado validado

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
