### ISSUE TITLE
La Brisa troca de mesa entre pisos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1204]
Hoje nao é possivel trocar mesas entre os pavimentos apenas no piso 1 e com isso o processo a ser realizado nessa situacao é deletar a comanda e lanca-la novamente em um novo piso/mesa

**Comment by rafaelqw** [comment]
Alterações WEB:
- controle-mesas.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
