### ISSUE TITLE
La Brisa cadastro de novos clientes usuarios

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1205]
Na tela de Clientes/Usuarios ao realizar um novo cadastro e clicar em salvar para finalizar o processo o modal nao esta sendo limpo e com isso se vc continuar clicando o mesmo usuario vai sendo criado novamente no sistema

**Comment by lukasqw** [comment]
Alterações API:
 - controller/ClienteController.php

**Comment by Kenzo13** [comment]
Necessário desabilitar o botão

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
