### ISSUE TITLE
La Brisa tela de Pedido das atendentes

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1206]
Cliente solicita para que na tela de adicionar pedidos pelo celular antes de incluir os produtos e mandar o pedido para a cozinha ou rosh a conta de Credito - Debito = Saldo ou Debito apareca primeiro, pois, dessa forma a atendente podera cobrar o cliente antes do pedido ser gerado e assim evitar cancelamento de pedidos e desperdicio de produtos

**Comment by rafaelqw** [comment]
Alterações WEB:
- controle-mesas.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
