### ISSUE TITLE
Bloquear funcionalidade do PDV p/ perfil de caixa

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1212]
Cliente deseja que as seguintes funções sejam desativadas do perfil de caixa:
- [x] Incluir Produto da comanda
- [x] Excluir produto da comanda
- [x] Dar desconto nos produtos da comanda
- [x] Alterar valor do produto da comanda
- [x] Alterar quantidade do produto da comanda
- [x] Incluir/Trocar Cliente da comanda
- [x] Alterar data da venda
- [x] Alterar tipo de venda

**Comment by rafaelqw** [comment]
Alterações WEB:
- pdv.php

Alterações BD:
- ```INSERT INTO tbl_funcionalidade (cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('ver_botao_adicionar_cliente_pdv', 'Ver botão de adicionar cliente PDV', 'Ver botão de adicionar cliente PDV');```
- ```INSERT INTO tbl_funcionalidade (cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('ver_botao_adicionar_produto_pdv', 'Ver botão de adicionar produto PDV', 'Ver botão de adicionar produto PDV');```
- ```INSERT INTO tbl_funcionalidade (cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('ver_botao_desconto_pdv', 'Ver botão desconto PDV', 'Ver botão desconto PDV');```
- ```INSERT INTO tbl_funcionalidade (cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('ver_botao_exclusao_item_pdv', 'Ver botão exclusão de Produto  PDV', 'Ver botão exclusão de Produto  PDV');```
- ```INSERT INTO tbl_funcionalidade (cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('ver_campo_quantidade_pdv', 'Ver campo de quantidade do produto PDV', 'Ver campo de quantidade do produto PDV');```
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('43', 'ver_tipos_venda_pdv', 'Ver botões de tipo de venda no PDV', 'Ver botões de tipo de venda no PDV');```
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('43', 'ver_campo_data_venda', 'Ver campo data venda PDV', 'Ver campo data venda PDV');```

-```UPDATE tbl_funcionalidade SET id_modulo = '43' WHERE (id = '39');```
-```UPDATE tbl_funcionalidade SET id_modulo = '43' WHERE (id = '40');```
-```UPDATE tbl_funcionalidade SET id_modulo = '43' WHERE (id = '41');```
-```UPDATE tbl_funcionalidade SET id_modulo = '43' WHERE (id = '42');```
-```UPDATE tbl_funcionalidade SET id_modulo = '43' WHERE (id = '43');```

**Comment by Kenzo13** [comment]
Necessário retirar os botões "trocar vendedor","tela inteira" e "mais opções".

**Comment by mtrystao** [comment]
Testes realizados
Funcoes do PDV Bloqueadas
Os botoes Trocar Vendedor, Tela inteira e mais opcoes estao liberados e nao acredito que devam ser bloqueados tb
