### ISSUE TITLE
Problema ao criar lançamento financeiro como forma de pagamento em Cheque

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1214]
Ao criar um lançamento financeiro em cheque, com varias parcelas, são informadas as datas respectivas de cada cheque, no entanto, o sistema não esta gravando a data de cada cheque nos objetos.

**Comment by lukasqw** [comment]
Alterações WEB:
 - lancamentos.php

**Comment by mtrystao** [comment]
chamado validado

**Comment by mtrystao** [comment]
O primeiro lancamento financeiro funciona corretamente, porem, o segundo nao, com isso vc precisa sair e voltar para o sistema para dar continuidade aos lancamentos
