### ISSUE TITLE
Número da comanda no CNF não aparece completo

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1215]
No Cupom Não Fiscal (CNF) está cortando o número da venda (comanda).
Deve-se corrigir a quantidade de caracteres exibidos para que o usuário possa fazer a conferência ou usar esse número para uma troca/devolução em outro momento

**Comment by LEANDROCOELHO84** [comment]
funcionando corretamento so é necessario alterar o jar em todos os clientes que ultilizam os serviço
![photo_2019-01-31_14-15-27.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46f89c95378dbcfbdfb8e60ef40cbdc7787976276455f66622d2a164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff5898f453f1b011080fa5c36a59b49c051e406.jpg)

**Comment by mtrystao** [comment]
chamad validado

**Comment by rafaelqw** [comment]
Não consigo testar pois não tenho uma impressora para testes

**Comment by mtrystao** [comment]
nao tenho impressora

**Comment by LEANDROCOELHO84** [comment]
teste realizador e funcionando corretamente
![photo_2019-02-18_12-33-16.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46f89c95378dbcfbdfb8e60ef40fbdc5717976216457f06621d3a164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff58a87453f1b00188cff5935a2994ccb5fe406.jpg)
