### ISSUE TITLE
Regularizar indicadores de acordo com o regime de apuração do empreendimento

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1222]
Todos os indicadores do Dashboard deve se basear na configuração de regime de apuração:
- Competência ou Fiscal

**Comment by lukasqw** [comment]
Alterações WEB:
 - js/angular-controller/dashboard-controller.js

Alterações API:
 - dao/RelatorioDao.php
 - dao/DashboardDao.php
 - controller/LancamentosFinanceirosController.php

**Comment by lukasqw** [comment]
- [ ] Total Faturamento
 - [ ] Total Custo Produtos Vendidos
 - [ ] Total Taxa Maquinetas
 - [ ] Total Comissão Vendedores
 - [ ] Lucro Previsto
 - [ ] Vendas por tipo de Conta
 - [ ] Top 10 Vendas por Clientes
 - [ ] Top 10 Vendas por Fabricantes
 - [ ] Top 10 Vendas por Produtos
 - [ ] Qtde. Média Un. Prod. Vendidos
 - [ ] vendas por Categoria
 - [ ] Qtd. Vendas
 - [ ] Ticket Médio de Vendas
