### ISSUE TITLE
Cadastro de mesas

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1228]
Alterar Ordenação que esta pelo Id nas mesas para alfabética

http://webliniaerp.com.br/mesas.php

**Comment by lukasqw** [comment]
Alterações API:
 - dao/MesaDao.php

**Comment by lukasqw** [comment]
Teste Realizados, Tudo OK

**Comment by mtrystao** [comment]
Ordenacao das mesas sendo realizado atraves da Ordem Alfabetica, vale um pouco de atencao, pois, pode ser que o cliente queira nomear as mesas por nome e da forma que esta desenvolvido a ordenacao das mesas nao seguira o desejo do cliente mas sim a Ordem Alfabetica

**Comment by mtrystao** [comment]
Ordenacao de Mesas nao esta em Ordem Alfabetica

**Comment by rafaelqw** [comment]
Ficou a seguinte ordenação
- Piso
- Ordem Alfabética

**Comment by Kenzo13** [comment]
A ordenação está correta, porém não está trazendo mais o responsável das novas mesas cadastradas.

**Comment by rafaelqw** [comment]
Testar novamente
