### ISSUE TITLE
Controle de mesas

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1229]
colocar nome do responsável pela mesa na smesas 

http://webliniaerp.com.br/mesas.php

**Comment by rafaelqw** [comment]
Alterações WEB:
- controle-mesas.php
Alterações API:
- dao/MesaDao.php

**Comment by lukasqw** [comment]
Testes Realizado, Tudo OK.

**Comment by mtrystao** [comment]
cadastro e alteracoes funcionando corretamente

**Comment by mtrystao** [comment]
testado ok
