### ISSUE TITLE
Comprovante de Sangria PDV

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1230]
Imprimir comprovante para todas as  sangrias  no PDV

**Comment by lukasqw** [comment]
Alterações WEB:
 - pdv.php
 - js/angular-controller/pdv-controller.js

**Comment by rafaelqw** [comment]
Não tenho uma impressora para testes!

**Comment by rafaelqw** [comment]
Testes realizado, tudo ok!
