### ISSUE TITLE
Fechamento de caixa com mesas abertas

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1231]
O ultimo caixa aberto não poderá fechar caso tenha mesas com comandas abertas

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/pdv-controller.js

**Comment by lukasqw** [comment]
Teste Realizados, tudo OK.

**Comment by mtrystao** [comment]
Funcionalidade funcionando corretamente

**Comment by mtrystao** [comment]
Esta sendo possivel fechar o caixa mesmo tendo mesa em aberto

**Comment by rafaelqw** [comment]
Verificar status da chave de configuração "Bloquear fechamento de caixa com comanda aberta" na aba "Controle de Mesas"

**Comment by mtrystao** [comment]
testado e ok
