### ISSUE TITLE
Opção pra ver comandas na tela temporariamente mesmo que a chave de configuração esteja habilitada pra ocultar

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1233]
Cliente deseja que mesmo com as comandas ocultas, o usuário possa ver temporariamente para fazer alguma validação ou conferência rápida.

**Comment by mtrystao** [comment]
chamado validado

**Comment by mtrystao** [comment]
chamado validado com sucesso
