### ISSUE TITLE
Travamento do botão de salvar cadastro de cliente no controle de mesas depois de efetuar alguns cadastros

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1234]
Após realizar vários cadastros de clientes na tela de Controle de Mesas para abrir uma comanda, o botão de Salvar Cliente fica em Aguarde... e não é possível prosseguir

**Comment by mtrystao** [comment]
chamado validado

**Comment by mtrystao** [comment]
chamado validado com sucesso
