### ISSUE TITLE
Quando entrar em uma comanda pelo número do cartão e clicar em voltar, voltar para a visão das mesas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1235]
Se digitar o número do cartão do cliente e apertar enter entra na comanda. Ao clicar em voltar está voltando para uma mesa vazia (null)

**Comment by mtrystao** [comment]
chamado validado

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
