### ISSUE TITLE
Quando navegar para dentro de uma mesa e voltar, voltar para o piso que estava selecionado e não para o 1o piso

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1236]
Ao selecionar qualquer piso (2 ou 3, etc) e entrar em uma mesa deste piso e clicar em voltar, está voltando sempre para o piso 1. Ideal é que volte para o piso que o usuário havia selecionado.

**Comment by LEANDROCOELHO84** [comment]
estava como done e só foi aplicado no empreendimento orbitall.
foi passado para teste. 
para subir para produção

**Comment by Kenzo13** [comment]
Subimos os arquivos para homologação e está funcionando.

**Comment by mtrystao** [comment]
chamado validado

**Comment by mtrystao** [comment]
teste realizado com sucesso
