### ISSUE TITLE
Recalculo de datas de duplicatas usando funcionalidade DDL ao emitir NF-e não está funcionando

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1237]
Ao concluir a venda com as opções de pagamento em 3x no Boleto Bancário, vou tentar emitir a NF-e e nesse momento aparece a informação de que existe uma fatura ja criada com os dados informados, contudo, ao ir na aba Duplicatas consta apenas 1 duplicata com 10 anteriores a data atual

**Comment by mtrystao** [comment]
![Captura de Tela 2019-01-15 às 00.48.22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227049f37a3dd4b668beee9b124f5f4eb245504146feeb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da59ff41e04851a3163462e271357942930c38.png)
![Captura de Tela 2019-01-15 às 00.48.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227049f37a3dd4b668beee9b124f5f4eb245504145f5eb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da59f141e04851a3163462e271357942930c38.png)
![Captura de Tela 2019-01-15 às 00.44.50.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227049f37a3dd4b668beee9b124f5f4eb2455c4141fceb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da59f141e04851a3163462e271357941950c38.png)

**Comment by lukasqw** [comment]
Alterações WEB:
 - js/angular-controller/pdv-controller.js
 - js/angular-controller/nota_fiscal-controller.js

**Comment by mtrystao** [comment]
chamado validado com o Kenzo e Lucas

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
