### ISSUE TITLE
Exibir número do cartão no CNF (quando houver)

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1238]
Cliente deseja que no Cupom Não Fiscal (CNF) seja exibido o número do cartão usado pelo cliente durante a consumação na casa, para que seja usado em validações posteriores.

**Comment by rafaelqw** [comment]
Não consigo testar por não ter uma impressora para testes

**Comment by mtrystao** [comment]
nao consigo testar, nao tenho impressora

**Comment by LEANDROCOELHO84** [comment]
![photo_2019-02-18_15-09-36.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46f89c95378dbcfbdfb8e60ef40fbdc5717976266454fa6623d3a164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b00188cfe5e36a89143cd5fe406.jpg)
