### ISSUE TITLE
Nao está aparecendo o campo observações quando é editado um orçamento

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1239]
ao editar um orcamento nao esta trazendo a informacao de observacao, essa condicao esta sendo apresentada apenas no campo detalhes da venda

**Comment by lukasqw** [comment]
Alterações WEB:
 - js/angular-controller/pdv-controller.js

**Comment by mtrystao** [comment]
chamado validado

**Comment by mtrystao** [comment]
precisa limpar o campo observacao apos concluir a venda

**Comment by mtrystao** [comment]
chamado validado com sucesso
