### ISSUE TITLE
Funcionalidade juntar comandas não está funcionando corretamente

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1240]
Ao juntar comandas no PDV está ocorrendo os seguintes problemas:

- [x] Está recalculando os valores e aumentando sem nenhum critério e o valor total acaba não batendo sendo que se for fechado individualmente as comandas o valor seria outro
- [x] Não está cancelando as comandas "juntadas" conforme previsto

**Comment by lukasqw** [comment]
Alterações WEB:
 - controle-mesas.php
 - js/angular-controller/controle-mesas_controller.js

Alterações API:
 - model/VendaTO.php
 - controller/VendaController.php

**Comment by LEANDROCOELHO84** [comment]
![photo_2019-02-18_15-49-28.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46f89c95378dbcfbdfb8e60ef40fbdc5717976266450fa6622dda164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff58a86453f1b00188cfe5832a79042cb59e406.jpg)

**Comment by LEANDROCOELHO84** [comment]
esta calculando corretamente
