### ISSUE TITLE
Romaneio inserir campos Fornecedores e Soma total das NF-e

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1243]
Ao Selecionar as NF-es para geracao de romaneio e selecionar o tipo de entrega Transportadora: Deve-se abrir um check box para poder selecionar a Transportadora correspondente e tambem uma soma do valor das NF-es que estao sendo inseridas no romaneio

**Comment by lukasqw** [comment]
Alterações WEB:
 - notas-fiscais.php
 - js/angular-controller/notas_fiscais-controller.js

Alterações API:
 - model/NotaFiscalTO.php
 - model/RomaneioEntregaTO.php
 - dao/RomaneioEntregaDao.php
 - controller/NfeController.php
 - controller/RomaneioEntregaController.php

**Comment by mtrystao** [comment]
chamado validado com sucesso
