### ISSUE TITLE
Criar opcao de filtro na tela de lancamentos financeiros para No. Boleto, No. Cheque

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1244]

**Comment by lukasqw** [comment]
Alterações WEB:
 - lancamentos.php
 - js/angular-controller/lancamentos-controller.js

**Comment by mtrystao** [comment]
--Evidencias--
Nao esta apresentando nenhum campo para poder inserir o numero do boleto ou do cheque para realizar a busca

![Captura de Tela 2019-01-17 às 16.10.25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227049f37a3dd4b468beee9b124f5e48b240584146f9eb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da59f141e04851a314326be072327c4f950c38.png)


![Captura de Tela 2019-01-17 às 16.10.13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227049f37a3dd4b468beee9b124f5e48b240584145ffeb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da59f141e04851a314326be073317c469c0c38.png)

**Comment by mtrystao** [comment]
chamado validado

**Comment by mtrystao** [comment]
chamado validado com sucesso
