### ISSUE TITLE
Relatorio Vendas por Produto por Mes esta apresentando informacao errada

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1251]
O relatorio de Vendas por Produto por Mes esta apresentando valores diferentes do Dashboard e Relatorio de Vendas por Produto comparando o mes de Dezembro por exemplo

Vendas por Produtos por Mes  R$ 105.930,91
Vendas por Produto:                 R$ 104.293,91
Dashboard:                               R$ 104.293,91

**Comment by lukasqw** [comment]
Alterações API:
 - dao/ProdutoDao.php
