### ISSUE TITLE
Relatorio de contas a receber esta apresentando informacao errada

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1252]
ao extrair o relatorio de contas a receber esta sendo apresentado uma linha total do cartao de credito paga no valor de R$ 12.317,22 que nao faz relacao com nenhuma soma desse relatorio com esse filtro CARTAO DE CREDITO, logo abaixo os totais estao corretos, exemplo segue anexo

**Comment by mtrystao** [comment]
[contas a receber BS Dez 2018.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46eb9b94378390e98ea9ad46a758f2913b0605406920a63130d7b379e70037431f1d11f6140b1b56f6eb8c2df0b73474db095deed73f5f7cc16b11adb9834ded09bd32975dc7e7e2de139db17770a599855d3c1c0f198cfb5a32a39d49ca51f74ee05f18.xlsx)

**Comment by lukasqw** [comment]
Alterações WEB:
 - js/angular-controller/rel_pagamentos-controller.js
