### ISSUE TITLE
Envio de Produtos esta permitindo concluir o processo sem empreendimento de destino associado

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1256]
A Hage 04 realizou o enviou de produtos e nao associou o empreendimento de destino, com isso nao esta sendo possivel dar entrada na mercadoria conforme anexo

**Comment by mtrystao** [comment]
[relatorio.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46fa919622968cbb86e6fd0fe64de29b234324676b5ee17e2683b270eb437e075c591cac495f0944fdf88879f4be3b62964e49bc8f3900299f7744eeaa880dbe06b0218e4b82b1b88f4ec1ec3822e199c2.pdf)
![Captura de Tela 2019-01-17 às 15.09.15 (2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227049f37a3dd4b468beee9b124f5e4bb241514145f9e99129bfa42062ca1e54b7843e1b66cc2f14aaee8317bb50ef768849d7b6b48d1ac0e93c24b5d987482c02175ad8a1096afdc0019d1ae441f34c5dae123367e1713279459119702b6d756b.png)

**Comment by mtrystao** [comment]
[Uploading Captura de Tela 2019-01-17 às 15.15.24.png...]

**Comment by lukasqw** [comment]
Alterações WEB:
 - js/angular-controller/pedido_transferencia_recebido-controller.js

**Comment by LEANDROCOELHO84** [comment]
não e mais possível enviar produtos sem associar o empreendimento
![transferencia selecionar empreendimento.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46fc869b2d9185ac9decb140ad5cb0872c4a2270200bad2a62c5e625af507e04010b17f114061b1beee59b6be4e96625d91819e7c3685922c73515fdedd41cb953ba288c1985b7bd8b1e92e03a37fb99cd1e604a5a45d0b50877b29359c95ffc4ae44855a11b3165e276307d428653.png)
