### ISSUE TITLE
Erro gravíssimo: Ao concluir uma venda (comanda) vinculada a um cartão físico, está limpando a informação do cartão que estava vinculado

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1260]
Durante o processo de fechamento da venda, o campo id_cartao_fisico está sendo limpado e com isso, dificulta-se o processo de rastreamento posterior.

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js
