### ISSUE TITLE
Ajustar Relatório de Vendas por Produto p/ filtrar horário (opcional)

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1263]
Cliente deseja filtrar as vendas por uma faixa de data e hora específica

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/relatorio_vendas_produtos-controller.js
- rel_vendas_produto.php

**Comment by lukasqw** [comment]
Testes Realizados, Tudo OK.

**Comment by mtrystao** [comment]
insiro uma data e fim o sistema esta apresentando normalmente, contudo, nao aparece nenhuma informacao do dia e horario configurado

**Comment by Kenzo13** [comment]
testado e ok
