### ISSUE TITLE
Implementar De-Para de código de produto por fornecedor

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1266]
No processo de compras de um restaurante, pode-se fazer a aquisição de insumos e produtos por diversos fornecedores do mesmo item.
Uma vez que o muda-se o fornecedor, o código do produto (id) muda de fornecedor pra fornecedor. As vezes no mesmo fornecedor, o mesmo produto pode ter vários códigos internos, de acordo com a sua composição/forma de venda.

Exemplo:
- Coca-Cola Lata 300ml (Un. Tributável: Unidade)
  - 01234 - Coca-Cola Lata 300ml CX 6 UN (Un. Comercial: Caixa)
  - 01235 - Coca-Cola Lata 300ml CX 12 UN (Un. Comercial: Caixa)

Nota-se que se trata do mesmo produto, porém com códigos diferentes de acordo com a embalagem vendida.

Uma vez vinculado o código do fornecedor com o produto, para cada código deverá ser informado a quantidade de conversão, seja multiplicando ou dividindo, por um número ou fração, de acordo com a característica do produto.

Exemplo:
- Coca-Cola Lata 300ml (6 UN) - 3 - CX
  - FEMSA - Fornecedor
  - 01234 - Código do produto no fornecedor
  - Multiplicar
  - 6 unidades 

Ou seja, quando eu receber o produto 01234 do fornecedor FEMSA, cada caixa será multiplicado por 6 unidades, resultando na entrada de 18 unidades do produto no estoque

**Comment by lukasqw** [comment]
Alterações WEB:
 - produtos.php
 - js/angular-controller/produtos-controller.js

Alterações API:
 - dao/ProdutoDao.php
 - controller/ProdutoController.php
 - dao/ProdutoFornecedorConversaoDao.php
 - model/ProdutoFornecedorConversaoTO.php

Alterações BD:
´´´create table tbl_produto_fornecedor_conversao (
	id int auto_increment not null primary key,
    id_produto int not null,
    id_fornecedor int not null,
    cod_interno_fornecedor varchar(200) not null,
    dsc_unidade_comercial varchar(10) not null,
    dsc_unidade_tributavel varchar(10) not null,
    flg_fator_conversao int not null, -- 1- Divisão | 2- Multiplicação
    qtd_conversao double not null
);´´´
