### ISSUE TITLE
Implementar colunas comparativas no DRE

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1267]
Cliente deseja visualizar colunas comparativas no DRE para cada item, são elas:
  - Mês Anterior ((Mês Atual vs Mês Anterior)
  - Ano Anterior (Mesmo mês do ano anterior comparado ao mês atual)

**Comment by filipecoelho** [comment]
branch: espeto-carioca-fase-2-lucas

**Comment by jheizerwandel** [comment]
ALTERAÇÕES
 -  modified:   js/angular-controller/relatorio_dre-controller.js
 - modified:   rel_dre.php

**Comment by Kenzo13** [comment]
Validar as alterações com o scopo do chamado @filipecoelho

**Comment by filipecoelho** [comment]
@jheizerwandel está errado!
O escopo era bem claro:
Mostrar uma coluna do mês selecionado, outra coluna do mês anterior ao mês selecionado e mais uma coluna do mesmo mês do ano anterior

**Comment by jheizerwandel** [comment]
![diz_que_ta_errado.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5db068c9c1a140091db86/125516c66e82c728ace21e0d46ec9d801c9396acb0fdbe7ca14fe2952d49653f6b14b1247a80e03cfd18395459094fa445090a12ffffdb2baeb16a708b5d0abf83655866da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3822e0838f46381b041d8eed10.png)

**Comment by filipecoelho** [comment]
@jheizerwandel desculpe, não havia visto dessa forma e não tinha entendido

**Comment by jheizerwandel** [comment]
Se  o campo "especificar endereço"  estiver marcado sempre vai ser obrigatório especificar o endereço  ... caso o empreendimento não esteja configurado para  "controlar estoque por endereço"(coloquei esse campo na tela de conf , porem não aparece la, não no ambiente te teste, nesse commit "https://github.com/WebliniaERP/webliniaerp-web/commit/738338c4176b2d6f4edd0489020cf984eb30b6d8" podem ver que eu fiz e dei o commit )  é possível desmarcar essa opção  ...
