### ISSUE TITLE
Incluir campo observação Tela de Vendas e Lançamentos Financeiros

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#127]
Precisamos incluir campo observação em:
Tela de Vendas;
Lançamentos Financeiros
Se faz necessario a inserção desses campos, pois, existem vendas e pagamentos que precisamos incluir informacoes adicionais devido a algum tipo de negociação

**Comment by filipecoelho** [comment]
Na tela de lançamentos financeiros já foi incluido.
Falta incluir na tela do PDV.

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- js/angular-controller/pdv-controller.js
- pdv.php

Alteraçoes API: 
- controller/RelatorioPDF.php
- controller/VendaController.php
- util/rel_templates/comprovante_venda.php

**Comment by matheuscaetano** [comment]
Testado!
