### ISSUE TITLE
Trocar label de indicador de Pagamentos Confirmados do Dashboard

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1270]
Para que o objetivo do indicador fique mais claro, o label do indicador deve ser renomeado para Recebíveis Confirmados

**Comment by lukasqw** [comment]
Alterações WEB:
 - dashboard.php
 - js/angular-controller/dashboard-controller.js

**Comment by Kenzo13** [comment]
testado e ok

**Comment by mtrystao** [comment]
label alterado
