### ISSUE TITLE
Criar indicador no Dashboard p/ Total de Taxa de Serviço cobradas no período

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1272]

**Comment by lukasqw** [comment]
Alterações WEB:
 - dashboard.php
 - js/angular-controller/dashboard-controller.js

Alterações API:
 - index.php
 - dao/DashboardDao.php
 - controller/DashboardController.php

**Comment by Kenzo13** [comment]
testado e ok

**Comment by mtrystao** [comment]
Indicador criado, testado e ok
