### ISSUE TITLE
Criar visão de vendas por tipo de conta no gráfico de vendas hora a hora

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1273]
- No gráfico em linha, criar outras linhas para demonstrar por tipo de conta, qual o período de maior movimento
- No gráfico de calor, criar opção de filtro para exibir por tipo de conta, qual o período de maior movimento

**Comment by filipecoelho** [comment]
branch: espeto-carioca-fase-2-lucas

**Comment by jheizerwandel** [comment]
ALTERAÇÕES
  - WEB
     -  dashboard.php
     -  js/angular-controller/dashboard-controller.js
     -  js/angular-controller/relatorio-total-vendas-estados-anual.controller.js
 
- API
    -  config/func.php
    -  controller/PosiController.php
    -  dao/RelatorioDao.php
    -  index.php

**Comment by Kenzo13** [comment]
O mapa de calor não possui o filtro para selecionar o tipo de conta, nesse caso, ele não apresenta os dados de acordo com o tipo.

**Comment by jheizerwandel** [comment]
Outro chamado que tbm subi por engano para o "master"

**Comment by Kenzo13** [comment]
Testado e ok

**Comment by mtrystao** [comment]
nao esta sendo possivel realizar os filtros no relatorio

**Comment by mtrystao** [comment]
testado e ok
