### ISSUE TITLE
Na tela de lançamento de contagem de estoque, deve ser permitido a informação por setor de produto dentro do depósito

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1274]
Quando o usuário está contando o estoque, ele inicia em um determinado setor/corredor, porém ele pode mais tarde encontrar um produto em outro corretor que pertence a um setor que ele já contou e o sistema deve permitir o lançamento desse produto sem que seja apagado a contagem anterior, ou seja, somar-se ao item que já foi contado.
O mesmo processo deve ocorrer no aplicativo de contagem de estoque

**Comment by jheizerwandel** [comment]
ALTERAÇÕES
	- WEB
		- endereco_estoque.php
		- js/angular-controller/endereco-estoque-controller.js
	- API
		- dao/EnderecoEstoqueDao.php
		- model/EnderecoEstoqueTO.php


	- DB

		CREATE TABLE IF NOT EXISTS `tbl_endereco_estoque` (
		  `id` int(11) NOT NULL AUTO_INCREMENT,
		  `id_pai` int(11) DEFAULT NULL,
		  `nome` varchar(255) NOT NULL,
		  `descricao` text,
		  `flg_excluido` int(11) DEFAULT '0',
		  PRIMARY KEY (`id`)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8;

		CREATE TABLE IF NOT EXISTS `tbl_endereco_estoque_emprendimento` (
		  `id` int(11) NOT NULL AUTO_INCREMENT,
		  `id_endereco_estoque` int(11) NOT NULL,
		  `id_empreendimento` int(11) NOT NULL,
		  PRIMARY KEY (`id`),
		  KEY `FK_tbl_endereco_estoque_tbl_empreendimento` (`id_empreendimento`),
		  KEY `FK_tbl_endereco_estoque` (`id_endereco_estoque`),
		  CONSTRAINT `FK_tbl_endereco_estoque` FOREIGN KEY (`id_endereco_estoque`) REFERENCES `tbl_endereco_estoque` (`id`),
		  CONSTRAINT `FK_tbl_endereco_estoque_tbl_empreendimento` FOREIGN KEY (`id_empreendimento`) REFERENCES `tbl_empreendimento` (`id`)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by Kenzo13** [comment]
Quando não selecionamos o campo de Especificação do Endereço, recebemos uma mensagem dizendo para preenchermos todos os campos obrigatórios. O problema é que nem todos os clientes vão usar esse campo e não podem receber essa mensagem.

**Comment by rafaelqw** [comment]
Se  o campo "especificar endereço"  estiver marcado sempre vai ser obrigatório especificar o endereço  ... caso o empreendimento não esteja configurado para  "controlar estoque por endereço"(coloquei esse campo na tela de conf , porem não aparece la, não no ambiente te teste, nesse commit "https://github.com/WebliniaERP/webliniaerp-web/commit/738338c4176b2d6f4edd0489020cf984eb30b6d8" podem ver que eu fiz e dei o commit )  é possível desmarcar essa opção  , por padrão ela vem desmarcada para os emp sem essa conf

by @jheizerwandel

**Comment by filipecoelho** [comment]
Testado e funcionando corretamente, precisa apenas melhorar apenas a exibição depois, conforme os prints anexo:
![Captura de Tela 2019-05-14 às 01.48.07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550338e01befa51300278352/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227049f37e3dd4b768beee9b124f5f4fb245504144fbeb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da5af741e04850a31b366ae373327d43960c38.png)
![Captura de Tela 2019-05-14 às 01.49.09.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550338e01befa51300278352/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227049f37e3dd4b768beee9b124f5f4fb245514144f5eb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da59ff41e04850a31b366ae373327d449d0c38.png)
![Captura de Tela 2019-05-14 às 01.48.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550338e01befa51300278352/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227049f37e3dd4b768beee9b124f5f4fb245504145f9eb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da59f141e04850a31b366ae373327d449d0c38.png)
