### ISSUE TITLE
Criar mecanismo de bloqueio do cadastro de produtos e alguns campos no momento da edição para lojistas franqueados

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1280]
O cadastro de produtos deve ser bloqueado para o lojista franqueado, ficando apenas possibilitado a edição dos campos da aba Fiscal

-Bloquear por aba

**Comment by rafaelqw** [comment]
Alterações BD:
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('4', 'alterar_informacoes_basicas', 'Editar aba Informações Basicas', 'Editar aba Informações Basicas');```
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('4', 'alterar_empreendimentos', 'Editar aba Empreendimentos', 'Editar aba Empreendimentos');```
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('4', 'alterar_informacoes_preco', 'Editar aba Preços', 'Editar aba Preços');```
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('4', 'alterar_estoque', 'Editar aba estoque', 'Editar aba estoque');```
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('4', 'alterar_fornecedor', 'Editar aba fornecedores', 'Editar aba fornecedores');```
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('4', 'alterar_informacoes_complementares', 'Editar aba informacoes complementares', 'Editar aba informacoes complementares');```
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('4', 'alterar_informacoes_fiscais', 'Editar aba informacoes fiscais', 'Editar aba informacoes fiscais');```
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('4', 'alterar_combinacoes', 'Editar aba combinações', 'Editar aba combinações');```

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
