### ISSUE TITLE
Criar opções de filtro no Rel. Vendas por Estado

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1281]
Cliente deseja filtrar as vendas por estado através dos seguintes filtros:
- Por Produto
- Por Categoria

**Comment by filipecoelho** [comment]
branch: espeto-carioca-fase-2-lucas

**Comment by jheizerwandel** [comment]
ALTERAÇÕES

 - WEB
    -   js/angular-controller/relatorio_vendas_produtos-controller.js
    -   rel_vendas_produto.php

 - API
    -    modified:   dao/ProdutoDao.php

**Comment by jheizerwandel** [comment]
ALTERAÇÔES
  - API
     -  dao/RelatorioDao.php
 - WEB
     - relatorio-total-vendas-estados-anual.controller.js
     - relatorio-total-vendas-estados-anual.php

**Comment by Kenzo13** [comment]
Quando clico nos botões de inclusão de produto ou categoria, não acontece nada. Talvez tenha que subir o controller novamente.

**Comment by jheizerwandel** [comment]
Foi mal ai galera , eu subi as alterações desse chamado para o "MASTER"

**Comment by Kenzo13** [comment]
Quando um dos novos filtros não trás nenhum dado, ele dá o erro 404, porém não fecha o modal.

**Comment by Kenzo13** [comment]
Alterações WEB

- js/angular-controller/relatorio-total-vendas-estados-anual.controller.js
- relatorio-total-vendas-estados-anual.php

**Comment by mtrystao** [comment]
Relatorio de Venda por UF nao esta disponivel para o usuario do Jheizer e do Filipe

**Comment by mtrystao** [comment]
no momento de gerar o relatorio apresenta a informacao de que nao existem dados, porem, sao apresentados dados e o relatorio continua pensando
produto SEO
empreendimento: Ambiente de Testes
