### ISSUE TITLE
Incluir coluna e agrupar por Categoria no Rel. Vendas por Produto

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1282]

**Comment by filipecoelho** [comment]
branch: espeto-carioca-fase-2-lucas

**Comment by jheizerwandel** [comment]
ALTERAÇÕES

 - WEB
    -   js/angular-controller/relatorio_vendas_produtos-controller.js
    -   rel_vendas_produto.php

 - API
    -  dao/ProdutoDao.php

**Comment by Kenzo13** [comment]
testado e ok
