### ISSUE TITLE
Incluir novos bancos na lista do empreendimento Em Shaddai

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1283]

**Comment by mtrystao** [comment]
Marcio Tristao:
Filipe, e possivel cadastrar as factoring abaixo no campo de bancos?
INNOV SEC
K&G
EUROMONEY
MMD
GERENCIANET

**Comment by LEANDROCOELHO84** [comment]
alterações conforme solicitado
