### ISSUE TITLE
operador com nome diferente do usuario

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1300]
foi verificado na orbital que o caixa da bruna com o usuario bruna esta registrando as operações com o nome do usuario jenifer.
foi verificado no banco o usuario bruna e não tem nenhum registro outro operador no cadastro de usuarios

**Comment by lukasqw** [comment]
Alterações WEB:
 - pdv.php
 - js/angular-controller/pdv-controller.js

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
