### ISSUE TITLE
saldo devedor

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1301]
filtrar cliente com flag excluido para relatorio de saldos devedores

esta aparecendo o saldo negativo de cliente excluido

**Comment by rafaelqw** [comment]
Alterações API:
- dao/UsuarioDao.php

**Comment by lukasqw** [comment]
Testes Realizado, Tudo OK.

**Comment by mtrystao** [comment]
cliente Marcio Tristao com R$ -568,75 de saldo negativo foi deletado mas continua aparecendo na lista de saldo devedor de clientes no Dashboard

**Comment by Kenzo13** [comment]
testado e ok
