### ISSUE TITLE
Produto VIP Masculino e Femino sem possiiblidade de exclusao desse item

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1302]
Precisamos criar uma chave de configuracao aonde os produtos entrada homem, entrada mulher, vip open homem e vip mulher sejam inseridos automaticamente pelo sistema, pois, para cada produto desse vendido sera considerado como uma passoa dentro da casa

tera que ser visto a possiblidade de analisar essas infiormacoes, pois, elas nao sao servicos definidos e o valor pode mudar a qualquer momento

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php 
- controle-mesas.php 
- js/angular-controller/controle-mesas_controller.js 
- js/angular-controller/empreendimento_config-controller.js 
- js/angular-controller/produtos-controller.js 
- pdv.php

**Comment by rafaelqw** [comment]
- Não está aparecendo os botões de Alterar item de produtos que não são entradas.
- Está sendo possível remover o produto no PDV.

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
