### ISSUE TITLE
devolução de produto

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1304]
ao cancelar uma venda que tenha vale-troca
o sistema não esta retornando o vale troca para disponivel.

ou seja não é possivel refazer uma venda cancelada com o mesmo vale troca da venda anterior.

**Comment by filipecoelho** [comment]
branch: sprint-2-marco

**Comment by jheizerwandel** [comment]
ALTERAÇÔES
API
 - controller/VendaController.php
- dao/DevolucaoDao.php

**Comment by Kenzo13** [comment]
testado e ok

**Comment by LEANDROCOELHO84** [comment]
esta funcionando corretamente
