### ISSUE TITLE
Venda via PDV sendo registrada com dia 00/00/0000 e horario 00:00:00

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1305]
Voce realiza uma venda normalmente, porem, as informacoes de data e horario estao todas as zeradas, mas no relatorio de movimentacao de caixa a venda esta com a data e horario correto, clientes: Nutri Whey, CLF e Mr Analia Franco ja relataram essa situacao

Eu acabo de pegar esse caso no ambiente de homologacao
Empreendimento: El Shaddai Jireh
Vendedor: JJ
Cliente: Marcio
Venda: #4768864

Obs: Esse incidente deve estar afetando todos os clientes

**Comment by rafaelqw** [comment]
Alterações API:
- controller/VendaController.php 
- dao/VendaDao.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
