### ISSUE TITLE
Orcamento deletado nao esta devolvendo produto para o estoque

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1306]
vc acessa o pdv lanca um orcamento e os produtos ficam reservados, em outro momento vc deleta esse orcamento, nesse momento o sistema nao esta deixando o produto novamente disponivel para venda, ele simplesmente descarta o produto
Provavelmente por conta dessa situacao que o Daniel responsavel pelos inventarios da Hage estava reclamando que ao deletar os orcamentos os produtos nao voltavam para o estoque e nos achavamos que o cara estava limpando o estoque depois que os produtos estao disponiveis novamente em estoque

**Comment by mtrystao** [comment]
produtos que foram inseridos no orcamento e na sequencia o orcamento foi deletado e os produtos nao retornaram para o estoque

![orcamento deletado.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e78699228f86a79be6ff47a151f580284228316546b3397f8fe62bab0021435a5918ad495c0e11aafa8f79a6be3b268a5d0aec833f5773d42103eee9dc4be05ce36ade0d97bcae8b44cae93820e78e8a4c371d00198ffc4f78.jpg)

**Comment by mtrystao** [comment]
Relatorio de movimentacao de produto, o orcamento deletado simplesmente limpou o estoque do produto foi necessario inserir a qtde na mao


![orcamento deletado 2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e78699228f86a79be6ff47a151f580284228337b46ef696097ec22ba416f43554d4baa17595740adacdf28a0e43c788d0a0becd06c0d26ce3a03b0aac04ee155e57dd205d0f4ae805ec1ef3724e28e8f4a3b1a07198ef65433b2d4.jpg)

**Comment by rafaelqw** [comment]
No ambiente de clientes está funcionando normalmente, provavelmente o ambiente esteja desatualizado!

**Comment by mtrystao** [comment]
teste realizado no produto TESTE MARCIO 1, realizei 02 orcamento um com 1 unidade e outro com 05 unidades o orcamento de 1 unidade foi deletado atraves do botao cancelar venda e o orcamento foi cancelado e o produto retornado para o deposito, deletado o orcamento atraves do botao excluir orcamento, o orcamento foi deletado do relatorio de movimentacao de estoque mas as 05 unidades nao retornaram para o estoque

**Comment by rafaelqw** [comment]
Para realizar o teste deveria ter usado o botão correto para cada tipo de venda, quando for venda usar o botão de exclusão de venda e quando for orçamento usar o de orçamento... Os dois botões aparecia apenas para o usuário 498 Filipe M. Coelho

**Comment by Kenzo13** [comment]
As vendas feitas em orçamento, sendo excluídas e canceladas e está ok

**Comment by mtrystao** [comment]
produtos sendo devolvidos corretamente para o estoque, testado e ok!

**Comment by mtrystao** [comment]
testado e ok
