### ISSUE TITLE
Implementar aba e campos de parametrização de integração c/ EzCommerce

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1307]
As configurações são:
- [x] ezcommerce_ambiente (textfield)
- [x] ezcommerce_apenas_estoque (flag)
- [x] ezcommerce_bandeiras (textarea)
- [x] ezcommerce_depositos (textarea)
- [x] ezcommerce_formas_pagamentos (textarea)
- [x] ezcommerce_id_empreendimento_principal (textfield)
- [x] ezcommerce_id_externo_formas_entrega (textarea)
- [x] ezcommerce_layer_development_login (textfield)
- [x] ezcommerce_layer_development_senha (textfield)
- [x] ezcommerce_layer_production_login (textfield)
- [x] ezcommerce_layer_production_senha (textfield)
- [x] ezcommerce_produto_frete (textfield)
- [x] ezcommerce_status_venda (textarea)
- [x] ezcommerce_usuario_venda (textfield)

**Comment by lukasqw** [comment]
Alterações WEB:
 - empreendimento_config.php
 - js/angular-controller/empreendimento_config-controller.js

**Comment by lukasqw** [comment]
Teste Realizados, Tudo OK.

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/empreendimento_config-controller.js

**Comment by Kenzo13** [comment]
testado e ok
