### ISSUE TITLE
Implementar relatório detalhado (completo) do DRE

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1308]
Cliente deseja visualizar o DRE de forma detalhada, mostrando todas as pastas e seus níveis inferiores, até os lançamentos financeiros individuais de cada subpasta

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/relatorio-contas-pagar.js
- rel_contas_pagar.php

**Comment by Kenzo13** [comment]
Foi feito essa melhoria no relatório de contas a pagar.

**Comment by mtrystao** [comment]
ao tentar gerar o relatorio esta apresentando a informacao de que ocorreu um erro e nao gera o relatorio

**Comment by rafaelqw** [comment]
Necessário rodar as alterações de BD para funcionar

**Comment by mtrystao** [comment]
testado e ok
