### ISSUE TITLE
PDV - realizar desconto automatico qdo o cliente tiver algum saldo positivo, como é feito no controle de mesas qdo é inserido um produto na comanda

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1312]
criar um mecanismo no PDV para que seja feito o desconto de um credito que o cliente, dessa forma, a venda podera ser feita no modo deposito e o caixa tb nao precisara realizar nenhum tipo de conta para saber qto o cliente ainda precisa pagar, fazendo com que o processo de recebimento seja mais rapido e com menos 1 possibilidade de falha ou diferencas no caixa

**Comment by rafaelqw** [comment]
Alterações WEB:
- pdv.php

**Comment by Kenzo13** [comment]
- INSERT INTO `weblinia_clientes`.`tbl_funcionalidade` (`id_modulo`, `cod_funcionalidade`, `nme_funcionalidade`, `dsc_funcionalidade`) VALUES ('43', 'ver_botoes_modo_deposito', 'Ver botoes modo deposito', 'Ver botoes modo deposito');

**Comment by Kenzo13** [comment]
Chamado testado e ok

**Comment by mtrystao** [comment]
funcao esta funcionando corretamente, mas acredito que os campos e a nomenclatura poderia ser apresentada de uma forma mais clara, exatamente como esta no controle de mesas

Saldo: (-) ou (+)
Valor da compra: R$ xx,xx
Saldo: (+) ou (-)

**Comment by mtrystao** [comment]
essa observacao vale para a tela do carrinho aonde os produtos sao inseridos
