### ISSUE TITLE
Ao cancelar uma comanda pela 1ª vez não está limpando o modal de autorização de cancelamento

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1313]
O usuário com permissão de autorização de cancelamento de comanda autoriza pela primeira vez e nas outras vezes os campos já estão preenchidos e o usuário consegue cancelar sem a permissão real do usuario autorizador

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/controle-mesas_controller.js

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
