### ISSUE TITLE
Problemas na tela de cadastro externo

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#132]
- Colocar asterisco em vermelho ao lado do título dos campos obrigatórios
- Incluir botão para validar CPF e RG
- Não está trazendo os dados de estado e cidade pelo CEP
- Adicionar texto na mensagem de sucesso que o usuário receberá um email com os dados de acesso

**Comment by rafaelqw** [comment]
Referente aos testes realizados no chamado #130

**Comment by rafaelqw** [comment]
- [ ] Ponto 1
- [ ] Ponto 2
- [ ] Ponto 3
- [ ] Ponto 4

**Comment by filipecoelho** [comment]
@rafaelqw já está no ambiente para o @matheuscaetano testar?

**Comment by rafaelqw** [comment]
Disponivel no ambiente de produçao para testes!

**Comment by matheuscaetano** [comment]
Teste realizado. Melhoria inserida com sucesso!!
