### ISSUE TITLE
Orbital Fechamento de Venda em Modo Deposito botao Finalizar nao fica Habilitado para o perfil ADM usuario do JJ

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1324]
Orbital Fechamento de Venda em Modo Deposito botao Finalizar nao fica Habilitado para o perfil ADM usuario do JJ

**Comment by rafaelqw** [comment]
Alterações WEB:
- pdv.php

**Comment by lukasqw** [comment]
Teste Realizados, Tudo OK.

**Comment by mtrystao** [comment]
usuario do JJ nao esta conseguindo acessar empreendimentos no site de testes, dessa forma, nao sera possivel  realizar os testes

**Comment by LEANDROCOELHO84** [comment]
necessita colocar na tabela de funcionalidade a funcionalidade  ("ver_botoes_modo_deposito")
adicionar id do modulo na funcionalidade_perfil o id da funcionalidade criada
