### ISSUE TITLE
Orbital impressao automatica para Rosh e Cozinha nao esta funcionando

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1325]
Com o metodo de impressao automatica por impressora/categoria em funcionamento, qdo vc envia um pedido para as impressoras de Rosh e Cozinha nao esta saindo nada, foi necessario desabilitar essa funcao para que os produtos fossem impressos corretamente

**Comment by LEANDROCOELHO84** [comment]
testa do e funcionado

criado uma configuração na categoria onde add o cod da categoria.
assim não questionando o local.

**Comment by LEANDROCOELHO84** [comment]
esta imprimindo

porem com a funcão habilitado quando tem 2 cozinhas imprime no mesmo lugar

**Comment by LEANDROCOELHO84** [comment]
foi efetuado o teste no ambiente do Rafael 
e o erro não persiste.

**Comment by LEANDROCOELHO84** [comment]
Kenzo, [24.04.19 16:33]
ALTER TABLE weblinia_clientes.tbl_vendas  ADD COLUMN flg_pagamento_realizado INT NULL AFTER vlr_acrescimo  ;


ALTER TABLE tbl_produtos ADD COLUMN id_produto_master INT(11) NULL DEFAULT NULL AFTER id, ADD COLUMN id_produto_sub_master INT(11) NULL DEFAULT NULL AFTER id_produto_master, ADD COLUMN flg_has_combinacao INT(11) NULL DEFAULT '0' AFTER id_produto_master, ADD COLUMN flg_is_combinacao INT(11) NULL DEFAULT '0' AFTER flg_has_combinacao, ADD COLUMN flg_is_sub_combinacao INT(11) NULL DEFAULT '0' AFTER flg_is_combinacao, ADD COLUMN nome_combinacao VARCHAR(255) NULL DEFAULT NULL AFTER nome

INSERT INTO weblinia_clientes.tbl_funcionalidade (cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES 
('ver_corrigir_status_nota', 'Ver botão Corrigir Status da nota', 'Ver botão Corrigir Status da nota');


(está faltando colocar o id do módulo)
