### ISSUE TITLE
Clientes excluidos retornam no controle de mesa e PDV

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1326]
verificar pois estao retornando na tela os clientes com flg_excluido no PDV e Controle de mesas

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/controle-mesas_controller.js
- js/angular-controller/pdv-controller.js

**Comment by lukasqw** [comment]
Testes Realizado, tudo OK.

**Comment by LEANDROCOELHO84** [comment]
teste realizado com e não esta m ais retornando os clientes deletados
