### ISSUE TITLE
Incluir opção de VIP no controle de tipos de genero ao abrir comanda

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1327]

**Comment by rafaelqw** [comment]
Alterações WEB:
- controle-mesas.php
- empreendimento_config.php
- js/angular-controller/controle-mesas_controller.js
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/pdv-controller.js

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by mtrystao** [comment]
funcionalidade funcionando corretamente
