### ISSUE TITLE
adicionar vendedor por item no comprovante da venda

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#1328]
adicionar vendedor por itens nos
- relatorio de vendas 
- comprovante de vendas
o cliente quer saber quem vendeu depois que fechou a venda e não aparece nos relatorios

**Comment by lukasqw** [comment]
Alterações API:
 - dao/ItemVendaDao.php
 - controller/VendaController.php
 - util/rel_templates/comprovante_venda.php

**Comment by lukasqw** [comment]
Testes Realizados, Tudo OK.

**Comment by mtrystao** [comment]
No romaneio de vendas esta aparecendo o nome do vendedor, contudo as informacoes estao sendo apresentadas 2 vezes conforme anexo
