### ISSUE TITLE
Relatório Produtos em Estoque incorreto

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1330]
O relatório de Produtos em Estoque está com os valores de custo, atacado, intermediário e varejo do produto, incorretos. Estão retornando valores diferentes do PDV e da tela de Produtos.

**Comment by rafaelqw** [comment]
Alterações API:
- dao/RelatorioDao.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by mtrystao** [comment]
testado e ok
