### ISSUE TITLE
Liberacao de Relatorios TOP Suplementos Atacado

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1331]
Favor, liberar os Relatorios abaixo
-- Vendas por UF
-- Vendas por Cliente Anual
-- Vendas por Vendedor Anual

Empreendimento: 242
Usuario: 114074
Nome: Lucas
Perfil: ADM ID 3536

**Comment by LEANDROCOELHO84** [comment]
relatorios ja estao ok

![relatorios.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46fa919622968cbb86e6ac01e81fe086264c22703d46f96925d3e579e7167a04095c48fe41505812fcf8882af4e43477984019af80330b2b9b645bf9fa9015ad00b22a8a4a80b7b58d48c9ef3e26e3839d02.png)
