### ISSUE TITLE
Incluir opção p/ reimpressão da ordem de produção de um item da comanda

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1334]

**Comment by rafaelqw** [comment]
Alterações WEB:
- controle-mesas.php
- js/angular-controller/controle-mesas_controller.js
Alterações API:
- controller/OrdemProducaoController.php 
- dao/ItensOrdemProducaoDao.php 
- dao/OrdemProducaoDao.php 
- index.php

**Comment by LEANDROCOELHO84** [comment]
testado e funcionando

**Comment by LEANDROCOELHO84** [comment]
funcionando corretamente
