### ISSUE TITLE
Bloquear Modo Depósito para Perfil Caixa

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#1335]

**Comment by rafaelqw** [comment]
Alterações WEB:
- pdv.php

**Comment by LEANDROCOELHO84** [comment]
teste realizado esta tudo ok 

apos subir para produção não esquecer de rodar script para liberar para todos os perfis que não iram utilizar a função

**Comment by mtrystao** [comment]
Funcionalidade em funcionamento e ja esta em producao na Orbital, mas deve ser rodado o tal script para o ambiente dos clientes antes de subir

**Comment by Kenzo13** [comment]
testado e ok, habilitar o modo depósito para os demais perfis.

**Comment by LEANDROCOELHO84** [comment]
testado e funcionando
