### ISSUE TITLE
Data dos pagamentos estão como 00/00/0000

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#1336]

**Comment by rafaelqw** [comment]
Alterações WEB:
- pdv.php

**Comment by LEANDROCOELHO84** [comment]
teste realizados com datas posteriores e anteriores 
não retornou erro de data zerada

**Comment by Kenzo13** [comment]
teste realizados com datas posteriores e anteriores
não retornou erro de data zerada
