### ISSUE TITLE
Limitar consumo máximo em uma comanda

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#1337]

**Comment by rafaelqw** [comment]
Alterações WEB:
- controle-mesas.php
- empreendimento_config.php
- js/angular-controller/controle-mesas_controller.js
- js/angular-controller/empreendimento_config-controller.js

Alterações API:
- model/ItemVendaTO.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by mtrystao** [comment]
funcao funcionando corretamente
