### ISSUE TITLE
Data dos produtos

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1339]
Durante a entrada de uma nota, o produto está vindo com a data padrão para 2099,sendo que o cliente selecionou a data de vencimento.

**Comment by filipecoelho** [comment]
branch: sprint-2-marco

**Comment by jheizerwandel** [comment]
O erro conforme o descrito não foi encontrado , o que pode ser verificado é que mesmo  cadastrando um novo produto com o campo "flg_controlar_validade" com o valor  de "1" não estava dando a possibilidade de inserir as validades , este erro que foi corrido , caso não seja esse o erro relatado por vc @Kenzo13  , favor dar mais detalhes .

**Comment by jheizerwandel** [comment]
ALTERAÇÔES 
   WEB
      modified:   js/angular-controller/estoque-controller.js

**Comment by Kenzo13** [comment]
testado e ok

**Comment by mtrystao** [comment]
nao estou localizando o campo para cadastrar um novo produto na tela de nova entrada em controle de estoque

**Comment by filipecoelho** [comment]
O campo de cadastro de produtos é quando um produto não é encontrado na importação de nota, como já era antes.

**Comment by mtrystao** [comment]
mesmo selecionando o campo controlar data de validade nao esta abrindo o campo para inserir a data de validade do produto que esta entrando no estoque

**Comment by mtrystao** [comment]
![photo_2019-04-08_23-20-16.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46f89c95378dbcfbdfb8e60ef409bdc4717975206456f36621d3a164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b001c8ef85b33a49843cb5de406.jpg)

**Comment by filipecoelho** [comment]
@mtrystao Tenta atualizar a tela

**Comment by filipecoelho** [comment]
@jheizerwandel consegue dar uma olhada nesse chamado, parece que não esta funcionando essa implementação!

**Comment by mtrystao** [comment]
funcionalidade continua nao funcionando, @jheizerwandel vc chegou a tratar essa situacao?

**Comment by mtrystao** [comment]
testado e ok
