### ISSUE TITLE
Implementar processo de download e sincronização de clientes (BizCommerce)

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1342]
Abaixo segue documentação:
[Guia de Referência API BizCommerce](https://github.com/WebliniaERP/webliniaerp-web/files/2985069/Guia.de.Referencia.API_2018.pdf)

**Comment by rafaelqw** [comment]
Alterações API:
- dao/ClienteDao.php
- dao/UsuarioDao.php
- model/ClienteTO.php
- bizcommerce-syncronize-customers.php
- dao/BizCommerceDao.php

**Comment by rafaelqw** [comment]
Testado com 1 pedido, tudo ok!
Porém está sendo necessário dividir as informações de endereço nos respectivos campos. (Bairro, Número).

**Comment by filipecoelho** [comment]
@rafaelqw cadê o script de sincronização das vendas?

**Comment by rafaelqw** [comment]
@filipecoelho  está no #1343

**Comment by filipecoelho** [comment]
@rafaelqw blz

**Comment by rafaelqw** [comment]
Problemas do endereço corrigido
