### ISSUE TITLE
Implementar processo de download e sincronização de Pedidos e Vendas (BizCommerce)

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1343]
Abaixo segue documentação:
[Guia de Referência API BizCommerce](https://github.com/WebliniaERP/webliniaerp-web/files/2985069/Guia.de.Referencia.API_2018.pdf)

**Comment by rafaelqw** [comment]
Alterções WEB:
- lancamentos.php

Alterações API:
- controller/NotaFiscalController.php
- dao/BizCommerceDao.php
- dao/VendaDao.php
- model/VendaTO.php
- bizcommerce-syncronize-sales.php

Alterações BD:
- ```ALTER TABLE tbl_produtos ADD COLUMN id_bizcommerce INT NULL;```
- ```ALTER TABLE tbl_vendas ADD COLUMN id_bizcommerce INT NULL;```

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
Nota Emitida
Romaneio Gerado
Pedido entregue
