### ISSUE TITLE
Erros ao cadastrar produtos

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#135]
- [x] Está replicando os registros de estoque para o mesmo depósito e validade
  - [x] Adicionar uma quantidade para o mesmo depósito e data de validade.
- [x] Depois de terminar de cadastrar o estoque de um produto, o depósito não fica selecionado
- [x] Ao informar dados fiscais em clicar em salvar dá o erro 500 e a mensagem: erro ao atualizar pro
- [x] Não está exibindo as formas de aquisições na aba fiscal
- [x] Ao informar o código de barras e salvar está arredondando esse número

**Comment by rafaelqw** [comment]
Referente aos testes realizados no chamado #131

**Comment by rafaelqw** [comment]
Os dois últimos pontos já foi resolvido!

**Comment by filipecoelho** [comment]
Ponto 3 já está resolvido. Não houve intervenção.
