### ISSUE TITLE
Corrigir e deixar funcional mecanismo de cadastro e venda de produtos c/ grade (combinações)

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1351]

**Comment by filipecoelho** [comment]
branch: grade-de-produtos

**Comment by jheizerwandel** [comment]
ALTERAÇÕES
-WEB
ALTER TABLE `tbl_produtos`
	ADD COLUMN `id_produto_master` INT(11) NULL DEFAULT NULL AFTER `id`,
	ADD COLUMN `flg_has_combinacao` INT(11) NULL DEFAULT '0' AFTER `id_produto_master`,
	ADD COLUMN `flg_is_combinacao` INT(11) NULL DEFAULT '0' AFTER `flg_has_combinacao`;

**Comment by Kenzo13** [comment]
Não está sendo possível cadastrar uma sub combinação

**Comment by Kenzo13** [comment]
Alterações WEB
- js/angular-controller/produtos-controller.js

**Comment by mtrystao** [comment]
nao possuo conhecimento para testar o chamado

**Comment by mtrystao** [comment]
Crio o produto c/ combinacao insito a combinacao e na tela de produtos ao clicar para editar o produtos as combinacoes nao aparecem no produto Pai

**Comment by mtrystao** [comment]
testado e ok
