### ISSUE TITLE
Tabacaria Yucatam

### ISSUE THREAD

**Issue by ecoelhospbrasil** [WebliniaERP/webliniaerp-web#1352]
Criar empreendimento com os seguintes logins

Serao 3 pessoas:
Mayco Jose da Silva e Silva

Daniel de Castilho Rocha

Joel da Paz de Lima Junior

-------------------------------------------

E os admin serão:
Carlos Eduardo 

Matheus Pavanelli

Obs! O mayco é gerente, os outros 2 são vendedores

**Comment by Kenzo13** [comment]
Mayco
Login: mayco@yucatam
Senha: 123

Daniel
Login: daniel@yucatam
Senha: 123

Joel da Paz de Lima Junior
Login: joel@yucatam
Senha: 123

Carlos Eduardo
Login: carlos@yucatam
senha: 123

Matheus Pavalli
Login: matheus@yucatam
Senha: 123
