### ISSUE TITLE
Entrada de nota XML cadastrar valores de venda

### ISSUE THREAD

**Issue by Kenzo13** [WebliniaERP/webliniaerp-web#1354]
Cliente solicita que quando for dar entrada de uma NF-e na tela de controle de estoque -> nova entrada, tenha a opção de colocar os valores de atacado e varejo para os produtos que vão ser cadastrados.

**Comment by rafaelqw** [comment]
Alterações API:
- controller/ProdutoController.php

Alterações WEB:
- estoque.php
- js/angular-controller/estoque-controller.js

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by mtrystao** [comment]
Marquei a opcao alterar valor de custo, abre o campo para alterar o valor de custo, contudo, os campos das tabelas Atacado, Intermediario, Intermediario II e Varejo nao aparecem, caminho utilizado Depositos>> Controle de Estoque>> Nova entrada

**Comment by mtrystao** [comment]
teste realizado com sucesso

**Comment by mtrystao** [comment]
teste realizado com sucesso
