### ISSUE TITLE
PDV com lentidao qdo tem muitos produtos na tela

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#1356]
ao inserir mais de 15 produtos no PDV a tela esta ficando extremamente lenta, esse chamado esta sendo abeto apenas para registro, pois, a situacao ja e de conhecimento e esta sendo tratada

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js
- pdv.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by mtrystao** [comment]
eu continuo sentindo lentidao no PDV qdo existem muitos produtos no carrinho

**Comment by rafaelqw** [comment]
Testar novamente

**Comment by Kenzo13** [comment]
Testado com as novas melhorias e ok

**Comment by Kenzo13** [comment]
Testado e ok
