### ISSUE TITLE
Efetuar ajustes no processo de importação de vendas oriundas do PDV da POSI

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1358]
- [x] Refatorar o script de leitura dos arquivos de vendas p/ usar nova metodologia via acesso direto às classes (igual EzCommerce, BizCommerce)
- [x] Ajustar valor correto dos itens da venda através da TAG "Conta.produtos" no JSON
- [x] Incluir produto Taxa de Serviço através da TAG "servico" no JSON
- [x] Incluir atendente que incluiu produto na comanda através da TAG "garcom" do item da venda
- [x] Usar TAG "Conta.vendedorAbertura" do JSON p/ associar o usuário correto que abriu a comanda

**Comment by rafaelqw** [comment]
Alterações API:
- config/func.php
- dao/ItemVendaCombinadoDao.php
- dao/ItemVendaDao.php
- dao/PosiDao.php
- model/ItemVendaCombinadoTO.php
- model/ItemVendaTO.php
- vendas-posi-watcher-json-2.php

**Comment by rafaelqw** [comment]
Alterações API:
- dao/ItemVendaDao.php
- dao/PosiDao.php
- dao/VendaDao.php
- model/ItemVendaTO.php
- model/VendaTO.php
