### ISSUE TITLE
Lentidão ao tentar receber um pedido de transferência

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1359]
Cliente relata que ao clicar para receber um pedido de transferencia de mercadoria a tela trava e não consegue fazer mais nada

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pedido_transferencia-controller.js
- pedido_transferencia.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by mtrystao** [comment]
no momento de receber os produtos se eu clicar no botao NAO para atualizar o valor de custo o recebimento nao é concluido, somente se eu clicar em SIM, isso esta errado, pq eu posso receber o produto e nao querer atualizar o valor de CUSTO

**Comment by rafaelqw** [comment]
Ã interpretação correta é a informação dada no item da lista, a segunda pergunta é apenas uma afirmação de que deseja ou não atualizar os custos. Se um item da lista estiver ativo para alterar o custo não exibirá a segunda pergunta

**Comment by mtrystao** [comment]
nao foi identificado lentidao no processo de transferencia, testado e ok

**Comment by mtrystao** [comment]
testado e ok
