### ISSUE TITLE
Imagem demora para carregar no PDV

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#136]
- Ao colocar uma foto grande no produto demora para carregar, portanto deveria colocar um loading informando o usuário

**Comment by rafaelqw** [comment]
Referente aos testes realizados no chamado #131

**Comment by filipecoelho** [comment]
Alterado o nível de prioridade devido a importância do problema

**Comment by filipecoelho** [comment]
Rafael, testar se o problema continua ocorrendo!

**Comment by rafaelqw** [comment]
Usei uma imagem de 6 MB, foi rápido para carregar, porém não apareceu o loading

**Comment by filipecoelho** [comment]
A principio o loading não é necessário.
