### ISSUE TITLE
Problema no PDV ocasiona gravamento de data da venda futura

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1360]
Por algum motivo o sistema está gravando as vendas c/ data futura, apenas na tabela de vendas, porém na tabela de movimentação de caixa a data está correta.
Pra corrigir as vendas anteriores e c/ problema, devemos colocar a data das vendas c/ a data da movimentação de caixa e corrigir a raiz do problema no PDV, que provavelmente deve estar relacionado ao campo de alteração de data da venda, disponível no PDV.

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js

Alterações API:
- controller/VendaController.php

**Comment by Kenzo13** [comment]
Feitos vários testes e esta ok
