### ISSUE TITLE
Incluir tipos de dispositivos liberados no cadastro do caixa p/ configuração no Aplicativo de Venda e no PDV Web

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1361]
A idéia é que no cadastro do caixa tenha as opções PDV Web e Aplicativo e o usuário possa selecionar as opções que deseja liberar aquele caixa

**Comment by rafaelqw** [comment]
Alterações WEB:
- caixas.php

Alterações API:
- controller/ContaBancariaController.php
- dao/ContaBancariaDao.php
- model/ContaBancariaTO.php

Alterações BD:
- ```ALTER TABLE tbl_conta_bancaria ADD COLUMN tipo_acesso VARCHAR(45) NULL;```

**Comment by Kenzo13** [comment]
testado e ok
