### ISSUE TITLE
Incluir no cadastro do usuário qual caixa está liberado para ele

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1362]
A idéia é vincular ao usuário quais caixas estão liberados por ele, sendo que apenas 1 por empreendimento

**Comment by rafaelqw** [comment]
Alterações BD:
- ```ALTER TABLE tbl_usuario_empreendimento ADD COLUMN id_caixa_padrao1 INT NULL;```

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
