### ISSUE TITLE
Implementar mecanismo de controle de acessos simultâneos

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1363]
A idéia é rastrear o inicio da utilização do sistema pelo usuario através do login e verificar a possibilidade de identificar quando o mesmo se desconecta ou sai do sistema. 
Dessa forma será possível identificar a quantidade real de usuários conectados, quem são esses usuários e até mesmo que seja possível desconecta-los do sistema, caso haja alguma necessidade de intervenção.
Outra utilização também será para controlar o acesso simultâneo e impedir que o mesmo usuário se conecte em varios dispositivos ao mesmo tempo.

**Comment by jheizerwandel** [comment]
modified:   js/angular-services/user-service.js
        modified:   js/app.js
        modified:   util/login/login.php

**Comment by rafaelqw** [comment]
Por enquanto não usar a implementação para bloqueio do usuário

**Comment by Kenzo13** [comment]
Testado, porém está derrubando a sessão do usuário ha qualquer momento.

**Comment by rafaelqw** [comment]
A principio tudo ok! Não foi encontrado nenhum problema durante a sessão
