### ISSUE TITLE
Ajustar PDV p/ que possa exibir os produtos sem estoque, mesmo que o empreendimento esteja bloqueado para não fazer venda sem estoque

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1368]

**Comment by jheizerwandel** [comment]
ALTERAÇÕES
   - WEB
          -js/angular-controller/pdv-controller.js

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by rafaelqw** [comment]
Colocar em chave de configuração

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/pdv-controller.js
