### ISSUE TITLE
Implementar processo de travar pedido ao entrar nele e não permitir que nenhum outro usuário acesse

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1369]
Cliente deseja que ao entrar em um pedido/orçamento para edição o mesmo fique bloqueado e nenhum outro usuário possa entrar no mesmo pedido

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/pdv-controller.js
- js/angular-controller/vendas-controller.js
- vendas.php

Alterações API:
- controller/VendaController.php
- dao/EstoqueDao.php
- dao/VendaDao.php
- index.php
- model/VendaTO.php

Alterações BD:
- ```ALTER TABLE tbl_vendas ADD COLUMN id_usuario_edicao INT NULL;```

**Comment by Kenzo13** [comment]
Testado e ok
