### ISSUE TITLE
Cadastro de comissão por Produto ou Categoria

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1393]
Ajustar mecanismo de comissionamento p/ o vendedor por 3 vertentes:
- Todas as vendas realizadas
- Produtos específicos
- Categorias específicas

**Comment by filipecoelho** [comment]
Substitui os chamados #676 e #677

**Comment by rafaelqw** [comment]
Alterações API:
- controller/GrupoComissaoVendedorController.php
- dao/GrupoComissaoVendedorDao.php

Alterações WEB:
- grupo_comissao.php
- js/angular-controller/grupo-comissao-vendedor-controller.js

Alterações BD:
- ``` CREATE TABLE tbl_itens_grupo_comissao ( id int(11) NOT NULL AUTO_INCREMENT, id_grupo_comissao int(11) DEFAULT NULL, id_produto int(11) DEFAULT NULL, id_categoria int(11) DEFAULT NULL, PRIMARY KEY (id)) ENGINE=MyISAM AUTO_INCREMENT=35 DEFAULT CHARSET=latin1;```
- ```ALTER TABLE tbl_grupo_comissao_vendedor ADD COLUMN tipo_comissao VARCHAR(45) NULL```

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
