### ISSUE TITLE
Criar Relatório de Comissão por Vendedor

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1394]
Opções de fonte de dados:
- Vendedor atrelado à venda/conta
- Vendedor atrelado ao item vendido

Opções de agrupamento:
- Produtos
- Categorias

Opções de filtro:
- Período (c/ data e hora)
- Vendedor
- Produto
- Categoria

**Comment by rafaelqw** [comment]
Alterações API:
- controller/RelatorioController.php
- dao/GrupoComissaoVendedorDao.php
- dao/RelatorioDao.php
- index.php

Alterações WEB:
- js/angular-controller/relatorio-comissao-vendedores.controller.js
- relatorio-comissao-vendedores.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
