### ISSUE TITLE
Ajuste no cadastro de maquinetas e bandeiras p/ quantidade de dias

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1411]
Adicionar qtd de dias p/ lançamento em cartão de crédito e débito

**Comment by rafaelqw** [comment]
Alterações WEB
- js/angular-controller/lancamentos-controller.js
- js/angular-controller/maquinetas-controller.js
- js/angular-controller/ordem_servico-controller.js
- js/angular-controller/pdv-controller.js
- js/angular-services/user-service.js
- lancamentos.php
- maquinetas.php
- ordem-servico.php
- pdv.php

Alterações API
- controller/MaquinetaController.php
- controller/OrdemServicoController.php
- dao/MaquinetaDao.php
- dao/TaxaMaquinetaDao.php
- index.php
- model/MaquinetaTO.php
- model/TaxaMaquinetaTO.php

Alterações BD
- ```ALTER TABLE tbl_taxa_maquineta ADD COLUMN qtd_dias_lancamento_debito INT NULL;```
- ```ALTER TABLE tbl_taxa_maquineta ADD COLUMN qtd_dias_lancamento_credito INT NULL;```
- ```ALTER TABLE tbl_maquineta ADD COLUMN qtd_dias_lancamento_debito INT NULL;```
- ```ALTER TABLE tbl_maquineta ADD COLUMN qtd_dias_lancamento_credito INT NULL;```

**Comment by filipecoelho** [comment]
Testado em:
[ ] PDV
[ ] Lançamentos Financeiros
[ ] Ordem de Serviço

**Comment by filipecoelho** [comment]
TUDO OK!

**Comment by rafaelqw** [comment]
Incluir no PosiDao
