### ISSUE TITLE
Implementar módulo de serviços

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#147]
- Criar tela de Ordem de Serviços
- Integrar com o financeiro, produtos e estoque.

**Comment by filipecoelho** [comment]
- Alterações no BD:
- `ALTER TABLE tbl_atendimento_venda 
  DROP FOREIGN KEY FK_tbl_atendimento_venda_tbl_vendas,
  DROP FOREIGN KEY FK_tbl_atendimento_venda_tbl_atendimento,
  DROP FOREIGN KEY FK_tbl_atendimento_tbl_itens_venda;

  ALTER TABLE tbl_status_atendimento 
  ADD COLUMN clr_class VARCHAR(100) NULL DEFAULT NULL AFTER dsc_status,
  ADD COLUMN num_ordem INT(11) NULL DEFAULT NULL AFTER clr_class;

  DELETE FROM tbl_status_atendimento;

  INSERT INTO tbl_status_atendimento (id, dsc_status, clr_class, num_ordem)
  VALUES
  (1, 'Aguardando Atendimento', 'new-primary', 3),
  (2, 'Em Atendimento', 'primary', 4),
  (3, 'Aprovado', 'info', 2),
  (4, 'Pendente', 'warning', 1),
  (5, 'Cancelado', 'danger', 6),
  (6, 'Realizado', 'success', 5);

  ALTER TABLE tbl_status_procedimento 
  ADD COLUMN clr_class VARCHAR(100) NULL DEFAULT NULL AFTER dsc_status,
  ADD COLUMN num_ordem INT(11) NULL DEFAULT NULL AFTER clr_class;

  DELETE FROM tbl_status_procedimento;

  INSERT INTO tbl_status_procedimento (id, dsc_status, clr_class, num_ordem)
  VALUES
  (1, 'Pendente', 'warning', 1),
  (2, 'Agendado', 'info', 2),
  (3, 'Realizado', 'success', 3),
  (4, 'Cancelado', 'danger', 4);```

**Comment by filipecoelho** [comment]
@rafaelqw irá realizar a implementação do mecanismo de pesquisa

**Comment by rafaelqw** [comment]
Implementado mecanismo de pesquisa
