### ISSUE TITLE
Problemas nos relatórios

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#149]
- Estoque Analítico
   - [x] Incluir linha de totais no final da tabela
   - [x] Remover subtitulo
- Produtos Vencidos
   - [x] Alterar título para Relatório de Produtos Vencidos
   - [x] Remover subtítulo
   - [x] Produtos vencidos não aparecem
- Produtos a Vencer
   - [x] Alterar título para Relatório de Produtos a Vencer
   - [x] Remover subtítulo
   - [x] Produtos para vencer em até 30, 90, 120 dias não aparecem
- Produtos em Estoque
   - [x] Alterar título para Relatório de Produto em Estoque
   - [x] Não exibir coluna de depósito quando a opção "agrupar por" estiver vazia
- Produtos c/ Estoque Mín.
   - [x] Alterar o título para Relatório de Estoque Mínimo
   - [x] Produtos com estoque mínimo não aparecem
- Vendas p/ Produto
   - [x] Quando determino a data inicial, final e seleciono um produto o resultado da filtragem fica em "Aguarde, carregando itens...". Mas quando determino apenas as datas eu tenho o resultado da filtragem
   - [x] Incluir popover no histórico da margem de lucro
- Vendas p/ Produto p/ mês
   - [x] Alterar título para Relatório por Produto por Mês
- Vendas p/ Cliente 
   - [x] Alterar título para Relatório de Vendas por Cliente
   - [x] Remover subtítulo
- Vendas p/ Vendedor
   - [x] Alterar título para Relatório de Vendas p/ Vendedor
   - [x] Remover subtítulo
   - [x] Não está calculando a comissão de cada vendedor
- Fechamento Mensal 
   - [x] CMT não está sendo calculado corretamente
- Pagamentos 
   - [x] Alterar o título do menu para Pagamentos de Venda
   - [x] Remover subtítulo
- Contas a Pagar
   - [x] Filtrar registros pelo id do empreendimento
   - [x] Incluir linha de totais 
- Saldo Devedor Cliente
   - [x] Incluir linha de totais
   - [x] Não aparece os clientes que estão com saldo devedor
- Contas a Receber
   - [x] Filtrar registros pelo id do empreendimento
   - [x] Incluir linha de totais
- Resumo de Caixas
   - [x] Na barra superior azul está com o título HageERP Admin
   - [x] Alterar título para Relatório Resumo de Caixas
-  Movimentação de Caixa
   - [x] Ao fazer um pagamento avulso não registrou o nome da pessoa que pagou
   - [x] Total de pagamentos em dinheiro apresenta valor negativo: 
   - [x] Ao abrir o caixa entrei com 150,00, depois fiz duas vendas em dinheiro que totalizam 26,50, depois entrei com um reforço de 20,00, em seguida fiz uma sangria de 70,00.
   - [x] O correto era retirar os 70,00 do total de dinheiro disponível no caixa e não do dinheiro dos pagamentos, como sugere o totalizador no rodapé do relatório, visto que o Dinheiro(Reforços) ficou com 170,00 (150,00 + 20,00).

**Comment by rafaelqw** [comment]
Referente aos testes realizados no chamado #148

**Comment by BreynerDeveloper** [comment]
Ponto 2 - OK

**Comment by BreynerDeveloper** [comment]
Ponto 3 -  OK

**Comment by BreynerDeveloper** [comment]
Ponto 4 - item  1 ok

**Comment by rafaelqw** [comment]
Incluir em todos os Relatorios botao de Extrair para o Excel

**Comment by filipecoelho** [comment]
@rafaelqw pontuar no primeiro comentário, os itens que já estão concluídos e dar continuidade dos que ainda não foram tratados

**Comment by rafaelqw** [comment]
Alterações WEB:
- rel_analitico_estoque.php
- rel_contas_pagar.php
- rel_movimentacao_caixa.php
- rel_saldo_devedor_cliente.php
- rel_total_produto_estoque.php
- js/angular-controller/relatorio-saldo-devedor-cliente-controller.js
- js/angular-controller/relatorio-contas-pagar.js
- js/angular-controller/relatorio-analitico-estoque-controller.js

Alterações API:
- dao/ProdutoDao.php

**Comment by rafaelqw** [comment]
Novas alterações

Alterações WEB:
- js/angular-controller/relatorio_vendas_produtos-controller.js
- rel_vendas_produto.php

Alterações API:
- dao/ProdutoDao.php
- controller/ProdutoController.php
- index.php
