### ISSUE TITLE
Incluir configuração para controle de estoque

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#163]
- incluir chave de configuração para dizer se o empreendimento deve ou não  controlar o estoque

**Comment by filipecoelho** [comment]
@jheizerwandel informar quais arquivos foram alterados e as alterações no BD

**Comment by filipecoelho** [comment]
Arquivos alterados:
- ```webliniaerp-api\controller\VendaController.php```
- ```webliniaerp-api\dao\EstoqueDao.php```
- ```webliniaerp-web\empreendimento_config.php```
- ```webliniaerp-web\js\angular-controller\empreendimento_config-controller.js```
- ```webliniaerp-web\js\angular-controller\pdv-controller.js```

**Comment by filipecoelho** [comment]
Encontrei uma falha no processo e não esta mostrando os itens sem saldo!
Estou tratando agora.

**Comment by filipecoelho** [comment]
Corrigi alguns problemas na tela do PDV, porém não está salvando a movimentação de estoque, e deixar o estoque negativo.

**Comment by jheizerwandel** [comment]
Arquivo para corrigir o problema 
Dao/EstoqueDao.php
