### ISSUE TITLE
Compartilhamento de regras de tributação

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#213]
- Possibilidade de compartilhar Regra de Tributos
- No cadastro de produtos, listar as regras de tributos que estão associadas ao empreendimento
- Ao salvar o produto (cadastro ou atualização), gravar individualmente a regra referente ao empreendimento que está logado
- Alterar query que retorna as regras de tributação (FiltroTributosDao.php::getFiltroTributos)
  - ANTES:
    - INNER JOIN tbl_regra_tributos                     ON tbl_regra_tributos.cod_regra_tributos                    = tbl_produtos.cod_regra_tributos
              INNER JOIN tbl_filtro_tributos                  ON tbl_filtro_tributos.cod_regra_tributos                   = tbl_regra_tributos.cod_regra_tributos
  - DEPOIS:
    - INNER JOIN tbl_produto_regra_tributos             ON tbl_produto_regra_tributos.id_produto                    = tbl_produtos.id AND tbl_produto_regra_tributos.id_empreendimento = $id_empreendimento
              INNER JOIN tbl_regra_tributos                   ON tbl_regra_tributos.cod_regra_tributos                    = tbl_produto_regra_tributos.cod_regra_tributos 
              INNER JOIN tbl_filtro_tributos                  ON tbl_filtro_tributos.cod_regra_tributos                   = tbl_regra_tributos.cod_regra_tributos

**Comment by filipecoelho** [comment]
Solução adotada:
- Criação de uma tabela auxiliar que armazena os ids do produto, do empreendimento e da regra de tributação respectiva a cada empreendimento, possibilitando que o produto tenha mais de uma regra de tributação de acordo com cada empreendimento.

Alterações no BD:
```
-- criação da tabela
CREATE TABLE tbl_produto_regra_tributos_empreendimento (
  cod_produto_regra_tributos INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  cod_produto INT NOT NULL,
  cod_regra_tributos INT NOT NULL,
  cod_empreendimento INT NOT NULL
);

-- inclusão automática dos produtos existentes no banco de dados
INSERT INTO tbl_produto_regra_tributos_empreendimento
SELECT NULL, pro.id, reg.cod_regra_tributos, emp.id_empreendimento
FROM tbl_produto_empreendimento AS emp
INNER JOIN tbl_produtos 		AS pro ON pro.id = emp.id_produto
INNER JOIN tbl_regra_tributos 	AS reg ON reg.cod_empreendimento = emp.id_empreendimento
ORDER BY pro.id;
```

**Comment by filipecoelho** [comment]
Testes realizados em conjunto com o @BreynerDeveloper nos ambientes de Clientes e Hage e nenhum problema ocorreu.
Tudo funcionando corretamente.
