### ISSUE TITLE
Problemas de aparecer "registro chave"

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#217]
O problema de aparecer "registro chave" acontece apenas na tela de Lançamentos Financeiros ao tentar fazer um novo lançamento no modal de Cliente.

**Comment by rafaelqw** [comment]
Referente ao chamado #210

**Comment by filipecoelho** [comment]
@matheuscaetano identificar as telas onde esses registros são exibidos e pontuar para que o @rafaelqw atue na ocultação desses registros

**Comment by matheuscaetano** [comment]
- asd
 - asd

**Comment by matheuscaetano** [comment]
Testado, ajuste realizado com sucesso!
