### ISSUE TITLE
Problema na tela de Configurações

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#226]
Na aba Dados do Empreendimento, ao usuário colocar o CEP deveria automaticamente aparecer o endereço, bairro, estado e cidade

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js

**Comment by matheuscaetano** [comment]
Testado  e nenhum erro encontrado!
