### ISSUE TITLE
Ordenar abas da tela de produtos

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#234]
Informações Básica;
Empreendimento;
Preço;
Estoque;
Fornecedores;
Informações Complementares;
Fiscal.

**Comment by filipecoelho** [comment]
Não será atendido, pela baixa importância!

**Comment by rafaelqw** [comment]
Arquivo alterado:
-```webliniaerp-web/produtos.php```

**Comment by rafaelqw** [comment]
Tudo certo!
