### ISSUE TITLE
Relatório Formas de Pgto demorando

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#254]
- Ao gerar Relatório de Pagamentos, está fazendo com que o servidor fique sobrecarregado e não carrega os dados

**Comment by jheizerwandel** [comment]
Não consegui replicar o problema.
Informe mais detalhes, ambiente, empreendimento, parâmetros da pesquisa e  etc.

**Comment by rafaelqw** [comment]
Problema não resolvido

**Comment by filipecoelho** [comment]
Vamos deixar o chamado em aberto para que, caso ocorra novamente, tentaremos identificar o problema.

**Comment by mtrystao** [comment]
toda vez que é tentado utilizar esse relatório por forma de pagamento o sistema INTEIRO TRAVA, isso pode ser comprovado a qualquer momento
