### ISSUE TITLE
Incluir relatório de vendas por fabricante

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#267]

**Comment by mtrystao** [comment]
Montar relatório de fabricante, considerar os seguintes itens:
periodo
fabricante (1 ou mais fabricantes)
deposito (qdo usuario tiver acesso a apenas um deposito ja marcar o deposito que o mesmo tem acesso)
ID produto
nome do produto
fabricante
tamanho/cor
sabor
qtde vendida
media custo
media valor venda
media de desconto em %
media de desconto em R$
valor total vendido

**Comment by rafaelqw** [comment]
Alteraçao no BD:
-- cria o modulo
INSERT INTO tbl_modulo (
	nme_modulo, tlt_modulo, url_modulo, icn_modulo, id_modulo_pai, psc_menu_modulo, vsv_menu_modulo
) VALUES (
	'Relatorio de Vendas por Fabricante', 'Relatorio de Vendas por Fabricante', 'rel_vendas_fabricante.php', 'fa-file-text-o', 3, 21, 1
);

-- pega o id gerado do modulo
SET @cod_modulo = LAST_INSERT_ID();

-- associa o modulo a todos os empreendimentos do sistema
INSERT INTO tbl_modulo_empreendimento (id_modulo, id_empreendimento)
SELECT @cod_modulo, id
FROM tbl_empreendimento;

**Comment by matheuscaetano** [comment]
Testado. Ok!
