### ISSUE TITLE
Relatório Pagamentos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#269]
Alterar o nome do relatório para Contas a Receber
Incluir campo para pesquisa de cliente

**Comment by mtrystao** [comment]
[tela webliniaerp.pdf](https://github.com/filipecoelho/webliniaerp-web/files/312573/tela.webliniaerp.pdf)

**Comment by rafaelqw** [comment]
Alterações no BD:
- ```UPDATE `webliniaerp-clientes`.`tbl_modulo` SET `nme_modulo`='Contas a Receber' WHERE `id_modulo`='35';```
