### ISSUE TITLE
Incluir nova formas de pagamento

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#272]
Inserir formas de pagamento referentes aos cartões Refeição e Alimentacao

**Comment by filipecoelho** [comment]
Retornando o chamado p/ revisão pois continua com problema no cliente X-Force.

**Comment by rafaelqw** [comment]
Alterações API:
- controller/VendaController.php
- dao/MaquinetaDao.php

**Comment by mtrystao** [comment]
como eu faco para testar essa atualizacao?
