### ISSUE TITLE
PDV Tela de Vendas

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#273]
Quando vc esta realizando uma venda e o vendedor clica fora ele perdi todas as informacoes de venda, pois, esta utilizando formulário, ele não perder todas as informacoes da venda

**Comment by filipecoelho** [comment]
@matheuscaetano validar corretamente qual o problema que ocorre pois não ficou claro.

**Comment by matheuscaetano** [comment]
Testado.
