### ISSUE TITLE
Parcelamento, incluir o valor e dividir pela quantidade de parcelas

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#278]

**Comment by filipecoelho** [comment]
Neste caso, abrir o campo de valor total do lançamento e dividir pela quantidade de parcelas, deixando que o usuário possa editar qualquer uma das parcelas, e caso isso ocorra, recalcule o total novamente.

**Comment by filipecoelho** [comment]
será atendido pelo chamado #711
