### ISSUE TITLE
Melhorias na VITRINE

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#302]
- [x] ao acessar a vitrine os produtos esta com os valores zerados, só aparece o valor dos produtos qdo clico em + Detalhes
- [x] Nao esta aparecendo o sabor do produto nem na tela da vitrine bem como em + Detalhes
- [x] Precisamos de uma chave de configuração onde o ADM do empreendimento possa indicar se ele quer que apareca a lista completa dos produtos cadastrados ou apenas os produtos com estoque disponível
- [x] nesta tela de configurações incluir opção para exibir apenas produtos com estoque ou todos os produtos
- [x] Mostrar badge/contador de qtd de itens no link do carrinho no topo da pagina
- [x] Na tela Principal Inserir um botão Limpar Pesquisa

**Comment by rafaelqw** [comment]
Alterações WEB:
- carrinho.php
- detalhes.php
- js/angular-controller/detalhes-controller.js
- js/angular-controller/vitrine-controller.js
- vitrine.php

**Comment by mtrystao** [comment]
a tela da vitrine esta toda desconfigurada, acesso feito com o usuario e senha tristao123

**Comment by mtrystao** [comment]
Testes realizados com sucesso
Detalhes para tratar
1- Ao sair da Vitrine esta aparecendo a tela INATIVAR - HAGE SUPLEMENTOS
2- Melhorar a navegação na Vitrine
  2.1- trazer o botão comprar para a Tela principal
  2.2 - Inserir um campo para ja poder inserir a qtde desejada

**Comment by mtrystao** [comment]
![vitrine.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46fe9d8e318b8daccda5fd53b652fa912a5265296b51f52d21ddb729ba4428570d5f46ab17585e45fdabdb23a1a42062c80d55b98e30063e937f03a6aa8318b500bf22884687b7bf8d44c0ea3b37aa.jpg)
