### ISSUE TITLE
Opção pra cancelar a venda

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#324]

**Comment by rafaelqw** [comment]
Telas relacionadas com Pagamentos e Recebimentos:
- Relatório Fechamento Mensal
- Relatório Pagamentos Fornecedor
- Relatório Contas a receber
- Relatório Contas a pagar
- Relatório Saldo Devedor de Clientes
- Lançamentos Financeiros
- Dashboard

**Comment by jheizerwandel** [comment]
INSERT INTO tbl_status_venda (`dsc_status`) VALUES ('Cancelada');

**Comment by rafaelqw** [comment]
Incluir como apareceu no estoque, no Relatório Movimentação de Caixa

**Comment by filipecoelho** [comment]
- Ocultar as vendas excluidas do relatorio de movimentacao de caixa
- Não considerar vendas excluidas no indicador de saldo devedor de clientes
- Não considerar vendas excluidas no relatorio de saldo devedor de clientes
- Não considerar vendas excluidas no indicador de taxas de maquineta

**Comment by rafaelqw** [comment]
Ponto 2 continua aparecendo as venda excluidas no  relatorio de movimentação de caixa
Ponto 3 ok!
Ponto 4 ok!
Ponto 5 o indicador não voltou ao valor que estava após um cancelamento de venda

**Comment by rafaelqw** [comment]
Problemas corrigidos

**Comment by rafaelqw** [comment]
Ao excluir uma venda realizada com cartao de débito, não está excluindo o pagamento e só é possivel excluir após fechar o caixa

**Comment by filipecoelho** [comment]
@BreynerDeveloper, validar o processo de cancelamento de venda  e todos os desdobramentos.

**Comment by rafaelqw** [comment]
O pagamento pelo cartão de débito ainda continua aparecendo na tela de lançamentos

**Comment by mtrystao** [comment]
Verifique também por favor o relatório de vendas por vendedor, pois, caso a
venda tenha sido cancelada o vendedor não pode receber comissao

Em 9 de abr de 2017 10:25, "rafaelqw" <notifications@github.com> escreveu:

**Comment by jheizerwandel** [comment]
ALTRAÇÕES WEB 

 js/angular-controller/lancamentos-controller.js

 ALTRAÇÕES API

 dao/LancamentosFinanceirosDao.php
 dao/PagamentoClienteDao.php

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
