### ISSUE TITLE
Incluir Segmento

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#33]
Precisamos saber qual o segmento que o empreendimento esta sendo utilizado, hoje já temos mais de 02 tipos de empreendimentos ex. Suplemento / Vestuário / Autopeças / Industria Automotiva
Essa informação sera muito boa para sabermos quem sao os nossos clientes para posteriormente procurarmos parcerias com fornecedores desses segmentos, pois, teremos condições de saber o que nossos clientes estão comprando

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
