### ISSUE TITLE
Criar uma agendas separadas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#340]
- criar uma agenda separada para o controle de atendimento da especialidade Ortodontia, Endodontia e Clinico Geral

**Comment by jheizerwandel** [comment]
ALTERAÇÂO DB

ALTER TABLE tbl_itens_venda
 ADD COLUMN id_especialidade_procedimento INT(11) NULL DEFAULT NULL AFTER id_status_procedimento;

ALTER TABLE tbl_pagamentos_venda
 ADD COLUMN id_especialidade_procedimento INT(11) NULL DEFAULT NULL AFTER flg_transferencia_conta;


ALTERAÇÂO API

modified:   controller/AtendimentoController.php
modified:   dao/ItemVendaDao.php
modified:   dao/PagamentoClienteDao.php
modified:   model/ItemVendaTO.php
modified:   model/PagamentoClienteTO.php

ALTERAÇÂO WEB

modified:   controle-atendimento.php
modified:   js/angular-controller/controle_atendimento-controller.js

**Comment by rafaelqw** [comment]
Ao carregar relatório da ficha do paciente não está carregando a ficha por especialidade

**Comment by jheizerwandel** [comment]
WEB 

 modified:ficha-paciente.php
 modified:controle_atendimento.php
 modified:js/angular-controller/controle_atendimento-controller.js

API

modified:   dao/EspecialidadeDao.php
modified:   util/rel_templates/ficha_paciente.php
