### ISSUE TITLE
Melhorias na vitrine virtual

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#350]
1-Mostrar badge/contador de qtd de itens no link do carrinho no topo da pagina 
2- criar tela de configurações do cliente, onde ele possa editar as informações pessoais
3- nesta tela de configurações incluir opção para exibir apenas produtos com estoque ou todos os produtos
4- ao acessar a vitrine os produtos esta com os valores zerados, só aparece o valor dos produtos qdo clico em + Detalhes
5- Nao esta aparecendo o sabor do produto nem na tela da vitrine bem como em + Detalhes
6- Precisamos de uma chave de configuração onde o ADM do empreendimento possa indicar se ele quer que apareca a lista completa dos produtos cadastrados ou apenas os produtos com estoque disponível
7-Incluir chave de configuração para configurar o número de dias máximo que o produto deve aparecer na vitrine quando não tiver mais estoque disponível.
8- Marcar lista de desejos na vitrine (antigo chamado 301) e gerar a lista de desejos onde pode ser consultado em Modulos>> Clientes/Usuarios
9- Incluir alerta indicando que existe uma nova venda realizada via Cliente Loja Virtual

**Comment by rafaelqw** [comment]
Ponto 1 foi atendido pelo chamado #138
