### ISSUE TITLE
Tratar situação de estabelecimentos que trabalham em períodos noturnos

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#357]
Atualmente o sistema impõe de alguma maneira que o caixa deve ser fechado as 23:59:59.
Precisamos criar algum mecanismo que permita que o usuário possa trabalhar entre turnos.

**Comment by filipecoelho** [comment]
@rafaelqw favor fazer um relatório de apuração das consequências desta mudança no sistema.

**Comment by rafaelqw** [comment]
Telas que utilizam a rota "pedido_venda/abrir_caixa/@id_caixa/@id_empreendimento"

C:\wamp64\www\webliniaerp-web\js\angular-controller\controle_atendimento-controller.js:
  711  
  712      ng.abrirCaixa = function(){
  713:    		aj.get(baseUrlApi()+"pedido_venda/abrir_caixa/"+ ng.configuracoes.id_caixa_atendimento_clinica +"/"+ng.userLogged.id_empreendimento)
  714  			.success(function(data, status, headers, config) {
  715  				ng.caixa_aberto = data ;

C:\wamp64\www\webliniaerp-web\js\angular-controller\ordem_servico-controller.js:
  216  
  217  	$scope.abrirCaixa = function() {
  218:    		$http.get(baseUrlApi()+"pedido_venda/abrir_caixa/"+ $scope.configuracoes.id_caixa_padrao +"/"+ $scope.userLogged.id_empreendimento)
  219  			.success(function(data, status, headers, config) {
  220  				$scope.caixa = data;

C:\wamp64\www\webliniaerp-web\js\angular-controller\pdv_simple-controller.js:
  444  
  445  	$scope.abrirCaixa = function() {
  446:    		$http.get(baseUrlApi()+"pedido_venda/abrir_caixa/"+ $scope.configuracoes.id_caixa_padrao +"/"+ $scope.userLogged.id_empreendimento)
  447  			.success(function(data, status, headers, config) {
  448  				$scope.caixa = data;

C:\wamp64\www\webliniaerp-web\js\angular-controller\pedido-personalizado-controller.js:
  903  
  904  	ng.abrirCaixa = function(){
  905:    		aj.get(baseUrlApi()+"pedido_venda/abrir_caixa/"+ng.configuracoes.id_caixa_pedidos_venda+"/"+ng.userLogged.id_empreendimento)
  906  			.success(function(data, status, headers, config) {
  907  				ng.caixa_aberto = data ;

C:\wamp64\www\webliniaerp-web\js\angular-controller\pedido_venda-controller.js:
  742  
  743  	ng.abrirCaixa = function(){
  744:    		aj.get(baseUrlApi()+"pedido_venda/abrir_caixa/"+ng.configuracoes.id_caixa_pedidos_venda+"/"+ng.userLogged.id_empreendimento)
  745  			.success(function(data, status, headers, config) {
  746  				ng.caixa_aberto = data ;


Funçao do PDV onde eh forçado fechamento de caixa as 23:59:59

ng.fecharPDV = function(){
		var btn = $('#btn-fechar-caixa');
		btn.button('loading');
		if(empty(ng.fechamento.id_conta_bancaria)){
			$("#conta_destino").addClass("has-error");
				var formControl = $("#conta_destino")
					.attr("data-toggle", "tooltip")
					.attr("data-placement", "bottom")
					.attr("title", 'Informe a conta de destino')
					.attr("data-original-title", 'Informe a conta de destino');
				formControl.tooltip();
				btn.button('reset');
			return false ;
		}

		aj.get(baseUrlApi()+"caixa/aberto/"+ng.userLogged.id_empreendimento+"/"+ng.pth_local+"/"+ng.userLogged.id)
			.success(function(data, status, headers, config) {
				if(data.open_today)
					var url = baseUrlApi()+"caixa/fechamento/"+ng.caixa_aberto.id+"/"+ng.fechamento.id_conta_bancaria+"";
				else{
					dta_fechamento = data.dta_abertura ;
					dta_fechamento = dta_fechamento.split(' ');
					dta_fechamento = dta_fechamento[0]+' 23:59:59';
					var url = baseUrlApi()+"caixa/fechamento/"+ng.caixa_aberto.id+"/"+ng.fechamento.id_conta_bancaria+"/"+dta_fechamento;
				}

		   		aj.get(url)
					.success(function(data, status, headers, config) {
						if(ng.print_report_thermal_printer)
							ng.getInformacoesFechamentoCaixa(ng.caixa_aberto.id);
						else
							window.location = 'rel_movimentacao_caixa.php?id='+ng.caixa_aberto.id;
					})
					.error(function(data, status, headers, config) {
						alert('Ocorreu um erro');
				});
			})
			.error(function(data, status, headers, config) {
				alert('Caixa não encontrado');
				window.location = 'pdv.php';
			});
	}


Relatorios que forçam a data de fechamento para 23:59:59

C:\wamp64\www\webliniaerp-web\js\angular-controller\rel_caixas-controller.js:
   90  		if( !empty(dta_inicial) && !empty(dta_final)){
   91  			dta_inicial = formatDate(dta_inicial)+" 00:00:00";
   92: 			dta_final   = formatDate(dta_final)+" 23:59:59";
   93  
   94  			query_string = query_string+"&("+$.param({'abt_caixa->dta_abertura':
   ..
  101  										})+"";
  102  		}else if(!empty(dta_final)){
  103: 			dta_final   = formatDate(dta_final)+" 23:59:59";
  104  
  105  			query_string = query_string+"&("+$.param({'abt_caixa->dta_fechamento':





  C:\wamp64\www\webliniaerp-web\js\angular-controller\relatorio-sangria.js:
   39  			dtaInicial = formatDate(dtaInicial);
   40  			dtaFinal   = formatDate(dtaFinal);
   41: 			queryString += "&"+$.param({'mvc->dta_movimentacao':{exp:"BETWEEN '"+dtaInicial+" 00:00:00' AND '"+dtaFinal+" 23:59:59'"}});
   42  		} else if(dtaInicial != "") {
   43  			dtaInicial = formatDate(dtaInicial);
