### ISSUE TITLE
Controle de Mesas - Necessidades

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#366]
- [x] Incluir Taxa de Serviço, % a ser cobrado no momento do fechamento da mesa ou comanda que pode ou não ser pago pelo cliente
- [x] Adm poder criar as mesas do seu espaço sem a necessidade de ter que acionar a equipe técnica
- [x] Transferir de mesa toda as comandas
- [x] Poder dividir o valor da comanda pela qtde de pessoas XX caso a mesa não esteja separadas com mais pessoas
- [x] Poder fechar a mesa inteira e não somente a comanda individual
- [x] Conseguir controlar o tempo de ocupacao das mesa
- [x] Poder realizar pgto parcial do consumo da mesa independente da qtde de pessoas que estejam na mes, pgto avulso
- [x] Eles possuem o produto Mix onde eles colocam mais de sabor de essência e tb % de um sabor e % de outro
  Exemplo: Mix - Limao - 80%
                                  Menta - 20%
  E essa informação precisa aparecer lá na produção

**Comment by filipecoelho** [comment]
- Incluir opção para pagar uma parte da mesa (necessidade Espaço Hookah)

**Comment by filipecoelho** [comment]
Com o fechamento da contratação do sistema com um novo cliente (Akemi Açai & Hamburgueria), o chamado foi reaberto e deve considerar os seguintes pontos:

- [ ] Incluir opção p/ selecionar cor de uma categoria (cadastro de produtos)
- [ ] Incluir opçãp p/ selecionar cor de um produto (cadastro de produtos)
- [ ] Incluir opção p/ adicionar produtos no carrinho através de grade (chave de configuração) de itens (1º categorias, 2º produtos da categoria)
- [ ] Incluir opção p/ adicionais de um produto (cadastro de produto)
- [ ] Implementar opção de incluir adicionais de um produto e estes adicionais serem impressos na ordem de produção da cozinha

**Comment by filipecoelho** [comment]
Para o item 1, usar: https://github.com/buberdds/angular-bootstrap-colorpicker

**Comment by rafaelqw** [comment]
Alterações BD:
- ```ALTER TABLE tbl_vendas ADD COLUMN dta_abertura TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER id_transferencia;```
- ```ALTER TABLE tbl_vendas ADD COLUMN qtd_pessoas INT NULL DEFAULT 0 AFTER dta_abertura;````
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('67', 'add_mesa', 'Adicionar novas mesas', 'Adicionar novas mesas');```
- ```ALTER TABLE tbl_movimentacao_caixa ADD INDEX id_venda (id_venda ASC);```

Alterações WEB:
- controle-mesas.php
- empreendimento_config.php
- js/angular-controller/controle-mesas_controller.js
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/pdv-controller.js
- pdv.php

Alterações API:
- controller/MesaController.php
- controller/VendaController.php
- dao/MesaDao.php
- dao/PagamentoClienteDao.php
- dao/VendaDao.php
- index.php
