### ISSUE TITLE
Problemas com PDV

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#374]
- Após configurar a aba PDV na tela de configurações e acessar a tela do PDV aparece a seguinte tela:
  ![pdv](https://cloud.githubusercontent.com/assets/6650717/17494804/b24a0f0e-5d8c-11e6-845e-224858eae044.png)

E não deveria, deveria aparecer caixa não configurado, porque não foi criado nenhum caixa com aquele IP

**Comment by filipecoelho** [comment]
Arquivos alterados:
- ```webliniaerp-web/pdv.php```
- ```webliniaerp-web/js/angular-controller/pdv-controller.js```

**Comment by filipecoelho** [comment]
@matheuscaetano validar se essa situação ocorre

**Comment by matheuscaetano** [comment]
Ao tentar abrir o caixa sem configurar,ele fica em aguarde constantemente e não abre, mas  também não mostra nenhuma mensagem ex: "caixa não configurado", fica apenas no aguarde.
