### ISSUE TITLE
Problema com devolução no ambiente da Hage

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#382]

**Comment by filipecoelho** [comment]
@rafaelqw Detalhar na descrição o que realmente acontece pra gerar o problema

**Comment by mtrystao** [comment]
Qdo tentamos realizar uma devolução com data de validade de 2021 aparece uma msg de erro e não contempla a devolução, ao realizar algumas tentativas posteriormente o produto aparece como negativo mas nenhum vale troca esta associado a devolução

**Comment by mtrystao** [comment]
![erro devolucao](https://cloud.githubusercontent.com/assets/13888745/18028123/49e85b22-6c4c-11e6-9fe4-e4f22fbbed8e.jpg)

**Comment by mtrystao** [comment]
Pessoal, essa é tela onde demonstra que a qtde devolvida fica negativa

**Comment by filipecoelho** [comment]
@rafaelqw , favor testar essa situação especificada pelo Marcio.
