### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#385]
Incluir outras formas de período a ser utilizado no Dashboard
Dia;
Ultimos 5 dias;
Ultimos 7 dias;
Ultimos 15 dias;
Ultimos 30 dias;
Periodo configurarel.
Qualquer opção selecionada deverá ser salva ser mantida até que esse período seja alterado

**Comment by BreynerDeveloper** [comment]
Solicitação implementa

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
