### ISSUE TITLE
Diferenca de valor entre o valor do Relatorio de Estoque  x Total Custo Dashboard

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#396]

**Comment by filipecoelho** [comment]
@rafaelqw , favor especificar em qual situações esse problema ocorre. 
Inclua evidências!

**Comment by rafaelqw** [comment]
- Da pra ver pelo empreendimento da Baba Bidu Louge de Itaquera, no período de agosto inteiro

**Comment by rafaelqw** [comment]
- Fui no Relatório de Produtos em Estoque e calculei valor de custo de cada produto vezes a quantidade no estoque, ai deu um valor. E no Dashboard mostra outro
![photo451563790986750236](https://cloud.githubusercontent.com/assets/6650717/19127262/a410b522-8b14-11e6-852f-a6c2a359ff3b.jpg)

**Comment by jheizerwandel** [comment]
Tinha um erro que foi corrido , porem o indicar de "Custo Total (Produtos em Estoque)" mostra apenas o estoque padrão , então para comparar o indicador com o relatório e preciso selecionar o estoque(o estoque padrão do empreendimento) no relatório

**Comment by rafaelqw** [comment]
Ok, etendido
