### ISSUE TITLE
Relatório de Fechamento mensal com problema

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#403]
- No Relatório de Fechamento mensal está duplicando os itens por conta da validade
- Da pra ver pelo empreendimento da Baba Bidu Louge de Itaquera, no período de agosto inteiro
  Dashboard: 
  ![image](https://cloud.githubusercontent.com/assets/6650717/19126849/f75175fc-8b12-11e6-9dfd-c2b3ebb46a2e.png)
  Relatório:
  ![image](https://cloud.githubusercontent.com/assets/6650717/19126892/1b85edd6-8b13-11e6-9743-a89301c04a86.png)

**Comment by rafaelqw** [comment]
Problema já havia sido resolvido!

**Comment by LEANDROCOELHO84** [comment]
foi efetuado teste nos relatorio de fechamento mensal no qual a soma do relatório não esta mais duplicando.
OBS:  Soma no DASHBOARD  esta com diferença de R$2,05 do relatório de fechamento.
![solução chamado 403.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46fb9b963621440a4ce6ff40ac5cfd952d4967277957e1673295f127b54778154d555ca9470e5e4cf8a8dc7da5b06e70825b5dedd06c5e26943516bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8e4e381c05108bff5e30a18b06.png)
