### ISSUE TITLE
Desbloquear procedimentos na ficha do paciente sem que ele esteja na fila de atendimento

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#407]
- Obs: Modal de lançamento de atividades

**Comment by jheizerwandel** [comment]
ALTER TABLE `tbl_atendimento`
	ADD COLUMN `flg_atendimento_fake` INT(1) NULL DEFAULT '0' AFTER `id_profissional_atendimento`;
