### ISSUE TITLE
Cartão parcelamento

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#416]
Na tela da maquineta, inserir o limite máximo de parcelas que é permitido receber no empreendimento, pois, essa qtde de parcela deve estar alinhada com a taxa de cartão cadastrada no sistema e tb para não permitir que o caixa lance um numero maior de parcelas na venda uma vez que essa informação estará amarrada no sistema

**Comment by filipecoelho** [comment]
Na verdade isso é um problema, no PDV , deveria ser validado quando ele seleciona a maquineta e tenta receber uma quantidade de parcelas maior que o que está no cadastro da maquineta.
