### ISSUE TITLE
Corrigir problema de indicadores no Dashboard

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#421]
Não está calculando o total de faturamento, principalmente, mas vale conferir os outros indicadores também.

**Comment by jheizerwandel** [comment]
Query para atualizar as vendas já feitas 

UPDATE tbl_vendas AS tabela_v 
	INNER JOIN (
	SELECT 
		tv.id,
		(
			SELECT SUM(tpv.valor_pagamento) FROM tbl_pagamentos_venda AS tpv 
			WHERE tpv.id_cliente = tv.id_cliente AND tpv.id_empreendimento = 75
		) AS valor_pagamentos
	FROM tbl_vendas AS tv 
	WHERE tv.id_empreendimento = 75 AND tv.venda_confirmada = 0 
	HAVING valor_pagamentos IS NOT NULL 
	) AS tbl_alguma_coisa ON tabela_v.id = tbl_alguma_coisa.id
	SET tabela_v.venda_confirmada = 1 ,
	tabela_v.id_status_venda = 6
