### ISSUE TITLE
Implementar emissão de Carta de Correção de NF-e

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#424]
- Deve ser criada uma tabela de cartas de correção
- Deve ser possível emitir mais de uma carta de correção para a NF-e
- Deve ser criado um modal para exibir as cartas de correções emitidas

Abaixo segue exemplo de implementação pela Focus:
https://focusnfe.com.br/2012/07/como-emitir-uma-carta-de-correcao-eletronica-cce/

Link p/ Documentação:
https://focusnfe.com.br/api/doc/nfe/

**Comment by jheizerwandel** [comment]
CREATE TABLE IF NOT EXISTS `tbl_nota_fiscal_correcao` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cod_nota_fiscal` int(11) DEFAULT NULL,
  `carta_correcao` text,
  `status` varchar(255) DEFAULT NULL,
  `chave_nfe` varchar(255) DEFAULT NULL,
  `status_sefaz` varchar(255) DEFAULT NULL,
  `numero_sequencial_evento` varchar(255) DEFAULT NULL,
  `mensagem_sefaz` varchar(255) DEFAULT NULL,
  `caminho_xml` text,
  `caminho_pdf` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
