### ISSUE TITLE
Criar mecanismo de cancelamento de NF-e e possibilidade de emissão de uma nova nota para a mesma venda

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#426]

**Comment by filipecoelho** [comment]
Tempo estimado: 8h

**Comment by filipecoelho** [comment]
Previsão de entrega: 15/01/2018

**Comment by filipecoelho** [comment]
- Alterações API:
  - dao/NotaFiscalDao.php
  - dao/NotaFiscalDao.php
  - controller/NfeController.php
  - dao/ItemTransferenciaEstoqueDao.php
  - model/NotaFiscalTO.php

- Alterações WEB:
  - js/angular-services/user-service.js
  - js/angular-controller/nota_fiscal-controller.js
  - js/angular-controller/notas_fiscais-controller.js
  - nota-fiscal.php
  - notas-fiscais.php

**Comment by LEANDROCOELHO84** [comment]
TESTE REALIZADO COM SUCESSO 
 
-CRIAR TABELA 

ALTER TABLE weblinia_clientes.tbl_nota_fiscal
ADD COLUMN cod_transferencia INT NULL AFTER chave_nfe_referenciada;
