### ISSUE TITLE
Excluir vendas de teste da Impavido

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#428]
As vendas reais começaram na segunda-feira dia 03/10, todas as vendas anteriores devem ser excluidas, inclusive pagamentos

**Comment by jheizerwandel** [comment]
SELECT * FROM tbl_empreendimento AS te WHERE te.nome_empreendimento LIKE 'Impavido';

SELECT tv.* FROM tbl_vendas AS tv 
WHERE  date_format(tv.dta_venda,'%Y-%m-%d')  < '2016-10-03' 
AND tv.id_empreendimento = 108 ;

SELECT tpv.* FROM tbl_controle_pagamento_venda  AS tcpv
INNER JOIN tbl_pagamentos_venda AS tpv ON tcpv.id = tpv.id_controle_pagamento
WHERE tpv.id_empreendimento = 108 AND   date_format(tcpv.dta_pagamento,'%Y-%m-%d')  < '2016-10-03' ;


SELECT * FROM tbl_abertura_caixa AS tac 
WHERE tac.id_empreendimento = 108 AND   date_format(tac.dta_fechamento,'%Y-%m-%d')  < '2016-10-03' ;

SELECT * FROM tbl_movimentacao_caixa AS tmc WHERE tmc.id_abertura_caixa IN (SELECT tac.id FROM tbl_abertura_caixa AS tac 
WHERE tac.id_empreendimento = 108 AND   date_format(tac.dta_fechamento,'%Y-%m-%d')  < '2016-10-03') ;

SELECT * FROM tbl_pagamentos_venda WHERE id IN (SELECT tmc.id_lancamento_entrada FROM tbl_movimentacao_caixa AS tmc WHERE tmc.id_abertura_caixa IN (SELECT tac.id FROM tbl_abertura_caixa AS tac 
WHERE tac.id_empreendimento = 108 AND   date_format(tac.dta_fechamento,'%Y-%m-%d')  < '2016-10-03') ) ;
