### ISSUE TITLE
Venda utilizando varios depósitos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#430]
No momento da venda onde é utilizado mais de um deposito é necessário que seja indicado qtas unidades serao liberadas por cada deposito, pois, da forma como esta sendo realizado hoje nao existe a indicação de onde os produtos estao saindo o que atrapalha o estoque e o processo do CLIENTE

**Comment by filipecoelho** [comment]
Este procedimento foi contornado associando os caixas aos ips de cada computador em todos os empreendimentos
