### ISSUE TITLE
Incluir controle de estoque por lote

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#433]
- Adicionar campo LOTE nas tabelas de controle de estoque.
  O controle de estoque será baseado no conjunto:
- Depósito
- Lote
- Validade

**Comment by jheizerwandel** [comment]
ALTER TABLE `tbl_produtos`
	ADD COLUMN `flg_controlar_lote` INT(1) NULL DEFAULT NULL AFTER `profundidade_pacote`;

**Comment by rafaelqw** [comment]
- Não é possível cadastrar produto com 2 lotes diferentes mas com a mesma validade
