### ISSUE TITLE
Controle Certificado Digital

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#435]
Inserir na tela de configurações um mecanismo para controlar a vigência do certificado digital do empreendimento e deve começar a emitir avisos qdo estiver com 30 dias para vencer

**Comment by filipecoelho** [comment]
- [ ] @rafaelqw incluir campo na tela de configurações p/ armazenar data de validade do certificado digital do empreendimento
- [ ] @lucianacaetano repassar para o @matheuscaetano uma relação com as empresas que estão cadastradas na Focus para emissão de NF-e e na Bematech Partners para emissão de SAT CF-e.
- [ ] @matheuscaetano contactar cada cliente da relação repassada pela @lucianacaetano e pegar a data da compra de cada certificado digital e calcular a data de validade e incluir a informação no campo criado pelo @rafaelqw

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/app.js

Alteraçoes API:
- dao/ProdutoDao.php

**Comment by rafaelqw** [comment]
Verificar em todos os modulos se existe a url do MOMENT

**Comment by rafaelqw** [comment]
Arquivos WEB:

- agenda.php
- agendamento-consulta.php
- baixa_estoque.php
- caixas.php
- categorias.php
- clientes.php
- contas.php
- controle-mesas.php
- controle_nfe.php
- controle_protese.php
- depositos.php
- desejos_clientes.php
- devolucao.php
- empreendimento.php
- especializacao_ncm.php
- extrato.php
- fabricantes.php
- faixa_desconto.php
- faixa_desconto_permitido.php
- ficha-paciente.php
- fornecedores.php
- grade.php
- grupo_comissao.php
- importadores.php
- lancamentos.php
- lista_pedidos_personalizados.php
- mapa.php
- maquinetas.php
- nota-fiscal-servico.php
- nota-fiscal.php
- notas-fiscais.php
- operacao.php
- ordem-servico.php
- ordem_producao.php
- pedido-personalizado.php
- pedidos_fornecedores.php
- perfis.php
- plano_contas.php
- procedimentos.php
- produtos-optimized.php
- produtos.php
- regime_especial.php
- regra_servico.php
- regra_tributos.php
- rel-movimentacao-estoque.php
- rel-vendas-categoria.php
- rel_analitico_estoque.php
- rel_caixas.php
- rel_consolidado_caixa.php
- rel_contas_pagar.php
- rel_fechamento_mensal.php
- rel_movimentacao_caixa_periodo.php
- rel_pagamentos.php
- rel_pagamentos_fornecedor.php
- rel_produtos_estoque_minimo.php
- rel_produtos_vencer.php
- rel_produtos_vencidos.php
- rel_saldo_devedor_cliente.php
- rel_sangria.php
- rel_total_produto_estoque.php
- rel_total_vendas_vendedor.php
- rel_vendas_cliente.php
- rel_vendas_deposito.php
- rel_vendas_fabricante.php
- rel_vendas_periodo.php
- rel_vendas_produto.php
- rel_vendas_produto_mes.php
- rel_vendas_vendedor.php
- rel_vendas_vendedor_dia_dia.php
- relatorio-diario-clinica.php
- separar_venda.php
- situacao_especial.php
- vendas.php
- zera-estoque.php
- zoneamento.php

**Comment by matheuscaetano** [comment]
Ao inserir a data (de validade)  nos empreendimentos, verifiquei que não esta funcionando o alerta!
