### ISSUE TITLE
SANGRIA - GERAR RELATORIO

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#436]
Gerar relatorio de Sangria
Campos sugeridos:
Periodo de: **/**/__ até **/**/__
Operador-Data-Cliente-Descrição-Valor

**Comment by filipecoelho** [comment]
Arquivos alterados:
- WEB:
 - ```js/angular-controller/relatorio-sangria.js```
 - ```rel_sangria.php```

- API:
 - ```controller/RelatorioController.php```
 - ```dao/PagamentoFornecedorDao.php```
 - ```dao/RelatorioDao.php```
 - ```index.php```
