### ISSUE TITLE
Implementar ajustes no processo de emissão de NF-e

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#444]
- Poder editar o valor dos itens da venda
- Poder selecionar a operação de cada produto
- Possibilidade de selecionar/alterar o cliente para emissão da nota
  - Se o cliente da venda for diferente do selecionado, perguntar pro usuário se deseja trocar o cliente da venda (caso a venda tenha um cliente associado)

**Comment by filipecoelho** [comment]
1º e 2º Ponto:
 - Carregar os itens da venda quando a tela é aberta;
 - Incluir botão de Operação p/ cada produto na listagem
 - Enviar a lista no mesmo formato que a API recebe e envia de volta calculado
3º Ponto:
 - Incluir modal de seleção de cliente

**Comment by mtrystao** [comment]
![Importacao XML melhoria 2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46c1998a2c9097a88ce8b0039c70dcd424432b7b2616aa2a30d7a164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b041c80f7593ca49e4fca59e406.jpg)

**Comment by filipecoelho** [comment]
Tempo estimado: 8h

**Comment by filipecoelho** [comment]
Previsão de entrega: 15/01/2018

**Comment by filipecoelho** [comment]
- Alterações API:
  - dao/NotaFiscalDao.php
  - dao/NotaFiscalDao.php
  - controller/NfeController.php
  - dao/ItemTransferenciaEstoqueDao.php
  - model/NotaFiscalTO.php

- Alterações WEB:
  - js/angular-services/user-service.js
  - js/angular-controller/nota_fiscal-controller.js
  - js/angular-controller/notas_fiscais-controller.js
  - nota-fiscal.php
  - notas-fiscais.php

**Comment by mtrystao** [comment]
* Poder editar o valor dos itens da venda - Teste Ok
* Poder selecionar a operação de cada produto - Teste Ok
* Possibilidade de selecionar/alterar o cliente para emissão da nota - Teste NAO OK

Obs: verifique a possiblidade de poder alterar tb a qtde de unidades

**Comment by LEANDROCOELHO84** [comment]
TESTE REALIZADO

- []Poder editar o valor dos itens da venda
- []Poder selecionar a operação de cada produto
- []Possibilidade de selecionar/alterar o cliente para emissão da nota
- []Se o cliente da venda for diferente do selecionado, perguntar pro usuário se deseja 
- []trocar o cliente da venda (caso a venda tenha um cliente associado)
