### ISSUE TITLE
Filtros na vitrine virtual não funcionam

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#448]
As fotos nao estao aparecendo

**Comment by filipecoelho** [comment]
Arquivos alterados:
- WEB:
 - ```empreendimento_config.php```
 - ```estoque.php```
 - ```js/angular-controller/empreendimento_config-controller.js```
 - ```js/angular-controller/pdv-controller.js```
 - ```js/angular-controller/vitrine-controller.js```
 - ```pdv.php```
 - ```vitrine.php```

**Comment by rafaelqw** [comment]
Problema corrigido!
