### ISSUE TITLE
Implementar mecanismo de atualização em massa do sistema para a loja virtual (PrestaShop)

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#462]

**Comment by filipecoelho** [comment]
Pontos alinhados na reunião de hoje (28/11/16):
- [ ] Não está capturando os dados do cliente na PrestaShop e cadastrando no WebliniaERP
 - Na PrestaShop é possível ter mais de um endereço, e neste caso, devemos sempre pegar o endereço de entrega do cliente e capturar os demais endereços e incluir num campo de observações (a ser criado) no cadastro do cliente
- [ ] Implementar atualização de status de pagamento conforme atualização na PrestaShop (ativar gatilhos/hooks)
- [ ] Incluir uma chave de configuração para determinar o ID do produto que representará o Frete, e ao concluir uma venda, validar se esta possui frete e adicionar este produto padrão e atualizar o seu valor de venda baseando-se no valor do frete que veio da PrestaShop
- [ ] Ao cadastrar um novo produto e associá-lo a vários empreendimentos, incluir processo de atualização de todas as lojas virtuais integradas nesses empreendimentos, a fim de que o produto suba para todas elas.
- [ ] Incluir chave de configuração para retorno de informações quando um produto for atualizado no PrestaShop para o WebliniaERP, dando a possibilidade de fazer ou não a atualização de dados no sentido do PrestaShop para o WebliniaERP.
- [ ] Implementar funcionalidades para bloqueio de edição dos campos de informações do produto
- [ ] Implementar processo em que as reservas deem baixa efetivamente no depósito padrão e caso o pedido seja efetivado, voltar o produto pro deposito onde foi feito a baixa e dar a baixa no deposito do caixa q esta sendo finalizado e registrar as operações de entrada e saida corretamente no relatorio de movimentacao de estoque.
 - Com isso devemos garantir que todos os empreendimentos que estão utilizando o deposito do produto em questão tenham a mesma quantidade do produto e também atualize as lojas virtuais vinculadas ao depósito.
- [ ] Implementar chamado #336
- [ ] Caso o pedido recebido (orçamento) seja oriundo de uma venda da loja virtual, desabilitar o botão de separação de estoque e finalização pelo PDV até que o pagamento  tenha sido efetivado.
- [ ] Remover ferramenta de formatação de texto do campo descrição curta e colocar o limite de caracteres de acordo com a documentação da PrestaShop
- [ ] Implementar método de identificação de quais campos do cadastro de produtos foi realmente alterado e só enviar para PrestaShop aquilo que foi realmente alterado
 - Eu penso em criar flags (variaveis booleanas) que representa cada informação que é enviada para a PrestaShop e ao fazer a requisição, enviar essas variáveis e controlar o que é sincronizado.
- [ ] Implementar script em background que atualize apenas o estoque dos produtos

**Comment by jheizerwandel** [comment]
API - 09/01/2017
       modified:   config/constants.php
        modified:   controller/PrestaShopController.php
        modified:   controller/VendaController.php
        modified:   dao/EstoqueDao.php
        modified:   dao/PrestaShopDao.php
        modified:   dao/VendaDao.php
        modified:   logs/logErrorPrestaShop.txt
        modified:   model/TRGTblEstoqueAUTO.php

WEB - 09/01/2017
        modified:   js/angular-controller/rel-movimentacao-estoque-controller.js
        modified:   rel-movimentacao-estoque.php
        modified:   vendas.php

**Comment by jheizerwandel** [comment]
ponto tratado "Implementar atualização de status de pagamento conforme atualização na PrestaShop (ativar gatilhos/hooks)" 

API - 22/01/2017
        modified:   controller/PrestaShopController.php
        modified:   dao/PrestaShopDao.php
WEB - 22/01/2017
  modified:  empreendimento_config.php
  modified:  js/angular-controller/empreendimento_config-controller.js

**Comment by filipecoelho** [comment]
@rafaelqw ao rodarmos o script para atualizar a loja virtual da Hage Suplementos, verificar se todos os produtos subiram e se carregou todas as informações dos produtos na loja virtual

**Comment by filipecoelho** [comment]
@mtrystao e @jheizerwandel se o @rafaelqw identificar que rodou tudo certo, irei concluir que o chamado está resolvido.

**Comment by mtrystao** [comment]
perfeito!! precisamos dessa validação para dar continuidade ao processo de subida da 1a loja virtual da Hage Suplementos
