### ISSUE TITLE
Nota Fiscal - Melhoria IE, Tipo de Nota, Tipo de Documento

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#483]
Para os empreendimentos que forem do simples o numero IE devera ser único para todos os Estados Brasileiros, caso o empreendimento nao seja do simples o empreendimento devera ser configurado com o numero IE para cada Estado

O sistema devera analisar so o destinatário possui CNPJ ou CPF e assim no momento de emitir a nota o campo Consumidor Final devera ser selecionado autoamenticamente para Normal ou Consumidor Final

Tipo de Documento: qdo a nota estiver sendo emitida através da tela de vendas, o Tipo de Documento pré selecionado deve ser Nota de Saida

**Comment by filipecoelho** [comment]
1º ponto não é regra, deve ser validado com a contabilidade essa informação.
2º ponto OK, é possível.
3º ponto OK, é possível.
