### ISSUE TITLE
Incluir botão para adicionar produto existente nas combinações

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#487]

**Comment by filipecoelho** [comment]
branch: grade-de-produtos

**Comment by Kenzo13** [comment]
Quando vamos adicionar uma combinação em outra combinação aparece o seguinte erro
![Capturar.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0c1076f15a6400138e3405/125516c66e82c728ace21e0d46cb958a379791a89dabf301b44fff9e2c4533317346f67d76d4bb7cbe477d52590d4ea4460e5f45fdf8db79aeb12e6c981e5ab38532022d8c6853beb2901eb80bbb258e498db4b4884ac6e83a26f5c6.PNG)
