### ISSUE TITLE
Problema com modal de categorias no Relatório de vendas por categoria

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#502]
- Não está listando as categorias no modal

**Comment by filipecoelho** [comment]
@BreynerDeveloper, validar situação.

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- js/angular-controller/rel-vendas-categoria_controller.js

**Comment by matheuscaetano** [comment]
Testado, ajuste realizado com sucesso!
