### ISSUE TITLE
Tela de Maquinetas com problemas nos botões de atalho

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#505]

**Comment by rafaelqw** [comment]
Nao so na tela de maquinetas, mas sim nas seguintes:
- [ ] Maquinetas
- [ ]

**Comment by rafaelqw** [comment]
Arquivos alterados WEB:
- [x] maquinetas.php
- [x] rel_caixas.php
- [x] rel_total_vendas_cliente.php

**Comment by matheuscaetano** [comment]
Testado, ajustes realizados com Sucesso!!
