### ISSUE TITLE
Todos os Clientes - Inutilizar o usuario

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#509]
Precisamos criar uma forma de inutilizar os funcionários de TODOS os clientes para que as informacoes relacionadas aos mesmos nao sejam perdidas

**Comment by rafaelqw** [comment]
Alteração Banco de Dados:
- alter table tbl_usuarios add flg_ativo int default 1;

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
