### ISSUE TITLE
Emitir Nota Fiscal de Transporte

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#511]
Precisamos implantar a possibilidade de emitir nota fiscal de transporte CFOP

**Comment by filipecoelho** [comment]
Tempo estimado: 16h

**Comment by filipecoelho** [comment]
Previsão de entrega: 15/01/2018

**Comment by jheizerwandel** [comment]
Arquivos alterados nos chamados #426, #444, #511

API:
	modified: dao/NotaFiscalDao.php
	modified: controller/NfeController.php
    modified: dao/ItemTransferenciaEstoqueDao.php
    modified: model/NotaFiscalTO.php
WEB:
	modified: js/angular-services/user-service.js
	modified: js/angular-controller/nota_fiscal-controller.js
    modified: js/angular-controller/notas_fiscais-controller.js
    modified: nota-fiscal.php
    modified: notas-fiscais.php

**Comment by filipecoelho** [comment]
Testes realizados:
- [ ] Não está trazendo o xProd

**Comment by filipecoelho** [comment]
Testes realizados, tudo OK!
