### ISSUE TITLE
Enviar e-mail nos relatórios de Sangria, Contas a Pagar e Receber

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#512]
Incluir nos relatórios Sangrias, Contas a Pagar e Receber o campo para envio de e-mail

**Comment by rafaelqw** [comment]
Alterações API:
- util/email_templates/relatorio-contas-pagar-receber.php
- controller/RelatorioController.php
- dao/RelatorioDao.php
- index.php

**Comment by mtrystao** [comment]
ativar flag de envio de notificacao e e-mail cadastrado, preciso da URL para poder iniciar os testes
