### ISSUE TITLE
Corrigir problema ao lançar item na tela de transferência de mercadorias

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#513]
O usuário reclama que ao tentar lançar um item ele não lança uma unidade de imediato e precisa incluir novamente a quantidade depois de ter adicionado na lista, gerando retrabalho.

**Comment by filipecoelho** [comment]
@BreynerDeveloper, validar situação.

**Comment by BreynerDeveloper** [comment]
Verdade
