### ISSUE TITLE
Incluir opção de taxas por bandeiras nas maquinetas para vendas parceladas

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#517]

**Comment by lukasqw** [comment]
Alterações WEB:
 - maquinetas.php
 - empreendimento_config.php
 - js/angular-controller/maquinetas-controller.js
 - js/angular-controller/empreendimento_config-controller.js

Alterações API:
 - controller/MaquinetaController.php

**Comment by rafaelqw** [comment]
- Ao incluir uma taxa por um bandeira o campo de bandeira está sendo limpo e não deveria

**Comment by rafaelqw** [comment]
- [ ] Taxas de débito não estão sendo aplicadas na venda

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
