### ISSUE TITLE
Identificar na coluna Reservado o Orçamento relacionado

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#523]
Inserir no PDV na coluna Reservado os Orcamentos relacionados que estao reservando o produto, igual ao que acontece na coluna Estoque na tela de produtos

**Comment by rafaelqw** [comment]
Alteraçao WEB:
- pdv.php
- js/angular-controller/pdv-controller.js
- css/custom.css
- js/angular-controller/rel-vendas-fabricante-controller.js
- rel_vendas_fabricante.php

Alteraçoes API:
- controller/VendaController.php
- dao/VendaDao.php
- index.php

**Comment by matheuscaetano** [comment]
TESTADO. OK!
