### ISSUE TITLE
Falha Pedido de Transferencia de Mercadoria

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#524]
Ao solicitar mercadoria através de transferencia de mercadoria alguns produtos nao estao aparecendo
Ex. Hage 05 pedindo para a Hage 00 Deposito
Colageno Laranja New Millen
Creator 150g Black Skull
Protetor para Cabeca Rosa
Protein Bar Nutrilatina Cookies
Boneco UFC Vanderlei Silva
Coqueteleira Robocop Preta com Verde

**Comment by filipecoelho** [comment]
@BreynerDeveloper, valide essa situação com o cliente e verifique se o problema persiste.
Se não persistir, inclua o label de inválido e encerre o chamado.
Caso o problema exista de fato, levantar possível solução.

**Comment by BreynerDeveloper** [comment]
Os testes que fiz em transferência de mercadorias esta funcionando normalmente  ,todos os produtos  transferidos apareceram , mas notei no cadastro de produtos.....Se o produto  não estiver compartilhado com ambos empreendimentos, ele não aparece,  verifiquei os produtos descriminados no chamado tanto na HAGE 05 E HAGE  00 , os produtos não tem cadastro...
