### ISSUE TITLE
Controle de Estoque - Entrada Manual

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#534]
Em Modulos>Depositos>Controle de Estoque>Nova Entrada
O Combo Box Alterar Valor de Custo vem selecionado automaticamente e esse campo nao deve ser selecionado por default 
A busca de produtos por Código de Barras nao esta funcionando

**Comment by filipecoelho** [comment]
chamado replicado, será atendido pelo chamado #514
