### ISSUE TITLE
Corrigir problemas no módulo de clínicas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#538]
- [ ] Acrescentar coluna deve na ficha do paciente, depois do campo valor
- [x] Mudar logo do relatório é nome da empresa (esta como COP - Alagoinhas)
- [x] Fazer mapas individuais  para lançar especialidade
(Endo, Cirurgia, Orto, etc.)
- [x] Ver por que os valores não batem com o valor real do mês
- [x] Ver por que quando abrimos o sistema, aparecem lançamentos do dia , sendo que nem lançamos nada nem entrou paciente ainda
- [ ] Ver por que está duplicando lançamento na ficha do paciente
- [x] Não está gravando o CPF do paciente no módulo de clínicas

**Comment by filipecoelho** [comment]
- Ponto 2 - Resolvido
- Ponto 5 - Ocorre quando é feito o agendamento de realização de um procedimento
- Ponto 6 - O sistema está se comportando corretamente, pois é incluído um procedimento na ficha do paciente e depois é lançado as atividades, ao concluir um procedimento, este é marcado como Realizado
- Ponto 7 - Não consegui replicar. Nos testes, foi gravado corretamente.

**Comment by filipecoelho** [comment]
Atualizando ponto 6: há uma exibição em duplicidade na ficha do paciente e no modal de ficha do paciente, na tela de controle de atendimento

**Comment by filipecoelho** [comment]
Resolver pontos 1 e 6

**Comment by jheizerwandel** [comment]
API
modified:   util/rel_templates/ficha_paciente.php
