### ISSUE TITLE
Data de Validade

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#540]
Quando é feito uma transferencia de mercadoria do deposito para as demais lojas a informacao de data de validade não sendo transferida juntamente com as demais informacoes do produto, com isso a data de validade não esta aparecendo na loja da Hage qdo recebe o produto e assim da conseguimos controlar a data de validade

**Comment by filipecoelho** [comment]
Basta marcar a opção de considerar validade em transferencia de estoques na configuração do empreendimento
