### ISSUE TITLE
Exportar Relatorio de Clientes

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#551]
Liberar exportação da lista de clientes em Modulos>Clientes/Usuario

**Comment by BreynerDeveloper** [comment]
Já existe esta liberação

**Comment by filipecoelho** [comment]
@matheuscaetano verificar se essa opção já não existe!

**Comment by matheuscaetano** [comment]
Chamado Invalido, essa opção já existe!
