### ISSUE TITLE
Melhorias no PDV, relatório de produto em estoque

### ISSUE THREAD

**Issue by BreynerDeveloper** [WebliniaERP/webliniaerp-web#553]
- [x] Na tela do PDV os códigos de barras iguais devem ser consolidados e não apresentando linha a linha,  (Danilo contabilidade deu Ok que podemos fazer).

- [x] Localizar o cliente através da Razão Social e Fantasia em todos os pontos do sistema

- [x] No relatório de Produtos em Estoque a soma total de produtos na ultima linha esta errado.

- [x] No PDV a opção para alterar automaticamente a tabela de preços para uma venda esta apresentando a opção PARCEIRO, essa opção só deve ser apresentada para usuários logado com o Perfil de ADM, pois, essa condição reduz o valor do produto ao valor de CUSTO e isso impacta diretamente o negocio do Cliente.

- [x] aplicar a mesma coisa do item 4 para o botão de exibir o custo real do produto

- [x] Na tela de entrada de produtos em Deposito, Inventario, quando selecionar um produto, esse produto deve ficar com o botão CINZA desabilitado como ja existe em outros pontos do sistema a fim de melhorar a visibilidade e nao confundir o usuário

**Comment by filipecoelho** [comment]
@BreynerDeveloper separar cada item em um chamado para serem tratados individualmente

**Comment by filipecoelho** [comment]
Ponto 1 será atendido pelo chamado #580
