### ISSUE TITLE
Data de emissão em NFS-e não está sendo preenchida

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#555]
o campo data de emissão está ficando como NaN/NaN/NaN porque não está capturando a data de emissão do retorno da Focus

**Comment by rafaelqw** [comment]
Arquivos alterados API:
- controller/NFSeController.php

Alteraçoes BD:
update tbl_nota_fiscal set status = 'processando_autorizacao' where cod_empreendimento = 127 and status = 'autorizado' and cod_ordem_servico is not null
