### ISSUE TITLE
Está exibindo o custo da mercadoria para todos os perfis no processo de transferencia

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#558]
ocultar para perfis diferentes de admin

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- js/angular-controller/pedido_transferencia_recebido-controller.js
- pedido_transferencia_recebido.php

**Comment by matheuscaetano** [comment]
Testado, ajuste feito com sucesso!

**Comment by matheuscaetano** [comment]
Testado, ajuste realizado com sucesso!
