### ISSUE TITLE
Alerta e email de novos cadastros não esta funcionando

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#559]

**Comment by rafaelqw** [comment]
Alterações BD:
- Criar coluna flg_cadastro_externo
```ALTER TABLE `weblinia_clientes`.`tbl_usuarios` 
ADD COLUMN `flg_cadastro_externo` INT NULL DEFAULT 0 AFTER `id_externo`;
```

**Comment by mtrystao** [comment]
Preciso de orientação em como devo acessar a realização do cadastro Externo e para qual empreendimento ser direcionado esse cadastro, a partir desse momento, terei condições de testar a funcionalidade
