### ISSUE TITLE
Lancamentos financeiros - Label Banco

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#561]
quando vc esta cadastrando boletos no sistema em algum momento o label dos bancos some e ai vc precisa sair do sistema limpar temporários e históricos ou ficar saindo e entrando novamente ate que a lista de bancos apareca

**Comment by filipecoelho** [comment]
@matheuscaetano verificar se não é o mesmo problema apontado no chamado #593

**Comment by matheuscaetano** [comment]
Mesmo problema que o foi identificado no chamado #593, já ajustado!!
