### ISSUE TITLE
Incluir chave de configuração p/ dar baixa automática em pgto de cheque e cartão de crédito

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#563]

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- rel_movimentacao_caixa.php

Aletraçoes API: 
- controller/VendaController.php

**Comment by matheuscaetano** [comment]
Testado, e nenhum erro foi encontrado
