### ISSUE TITLE
Alterar indicadores do Dashboard p/ COP

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#568]
O indicador de total de faturamento considera apenas as vendas efetuadas no período vigente.
No entanto, para eles o que vale como faturamento são os pagamentos realizados no período, independente se está pago ou não (ou seja, considerar a data de lançamento e não de pagamento).

**Comment by filipecoelho** [comment]
Incluir também um gráfico de pizza exibindo o faturamento dividido por especialidade

**Comment by rafaelqw** [comment]
Alterações WEB:
- dashboard.php
- js/angular-controller/dashboard-controller.js

Alterações API:
- controller/DashboardController.php
- dao/DashboardDao.php
- index.php

**Comment by rafaelqw** [comment]
Teste realizado! Tudo ok!
