### ISSUE TITLE
IMPRESSAO EXTRATO

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#570]
QDO VC CLICA PARA IMPRIMIR NA TELA DE EXTRATO ESTAO ABRINDO 02 TELAS MAS NAO CARREGA O RELATORIO

**Comment by filipecoelho** [comment]
@LEANDROCOELHO84 vamos testar uma solução e ver se resolve o problema:
- existe uma função padrão no sistema que carrega os dados em uma outra aba e na sequência solicita o comando de impressão. A idéia é colocar essa parte da impressao dentro de um setTimeout para que ele aguarde alguns segundos, que é o tempo do conteúdo ser carregado no navegador antes de imprimir, pois o erro ocorre porque o comando de impressao é ativado antes do conteúdo ser renderizado pelo navegador

**Comment by filipecoelho** [comment]
Infelizmente não tem como resolver este problema, apenas implementando o chamado #162, quando todos os relatórios forem transferidos para PDF
