### ISSUE TITLE
Gerar Alarme Data de Nascimento

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#575]
O sistema deve gerar um alarme no sistema iniciando que existe(m) X cadastros aniversariantes no dia de hoje e ao clicar no alerta deve aparecer os clientes que fazer aniversario no dia marcado

**Comment by lukasqw** [comment]
Esta funcionando tudo ok.
Ordenar a relatório de aniversario pela data de nascimento.

**Comment by filipecoelho** [comment]
@lukasqw Boa!
