### ISSUE TITLE
Baixa Manual

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#576]
- [x] Precisa disponibilizar o relatorio de Baixa Manual
- [x] Incluir campo de observações
- [x] Criar cadastro de motivos de baixa manual
- [x] Incluir campo p/ mencionar o motivo da baixa manual (combobox)

**Comment by rafaelqw** [comment]
Alterações API:
- controller/EstoqueSaidaController.php
- dao/EstoqueDao.php
- dao/EstoqueSaidaDao.php
- index.php
- model/EstoqueSaidaTO.php
- controller/MotivoBaixaManualController.php
- dao/MotivoBaixaManualDao.php
- model/MotivoBaixaManualTO.php

**Comment by mtrystao** [comment]
1- Em configurações Aba Estoque na linha onde disponível para fazer o cadastro do motivo da Baixa, favor, alterar de SALVAR para INCLUIR, pois, existe 2 vezes a palavra SALVAR
2- Apos Inserir um motivo de baixa a informação some e nao tenho condições de Editar ou de Excluir o motivo criado anteriormente
3- Nao consegui localizar o relatorio para gerar e assim poder valida-lo

**Comment by filipecoelho** [comment]
1 - Será tratado depois;
2 - Pra mim funcionou corretamente;
3 - Não existe relatório, o registro aparecerá no relatório de movimentação de estoque
