### ISSUE TITLE
Melhoria Envio ou Solicitação de Mercadoria

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#577]
Qdo estamos no modulo de transferencia localizamos o produto desejado e inseridos a qtde desejada mas qdo sai do combo box e vai para a tela do sistema a qtde inserida some, esse numero deve ser guardado, pois, gera retrabalho

**Comment by filipecoelho** [comment]
problema já foi apontado no chamado #513 e já foi resolvido
