### ISSUE TITLE
Desabilitar Tabelas Atacado e Intermediario e VArejo

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#578]
Devemos disponibilizar uma forma do cliente poder desabilitar as tabelas que ele nao trabalha, pois, caso o cliente nao insira nenhum percentual ele pode vender o valor no preço de custo e gerar problemas Tabelas: Atacado, Intermediario e Varejo ou então caso não tenha nenhum % nas tabelas devera ser seguido o valor de Varejo

**Comment by rafaelqw** [comment]
Chamado Atendido pelo #645
