### ISSUE TITLE
Implementar ajustes para integração c/ PDV Posi

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#582]
- Incluir campo de chave externa nas seguintes tabelas:
  - Cadastro de Caixas (tbl_conta_bancaria)
  - Cadastro de Clientes & Usuários (tbl_usuarios)
  - Configuração de Empreendimento (tbl_empreendimento)
  - Cadastro de Maquineta de Cartão (tbl_maquineta)
  - Cadastro de Produtos (tbl_produtos)
  - Disponibilizar o campo nas telas respectivas para manutenção.
- Ajustar métodos gravarVenda, gravarItensVenda e gravarMovimentações do VendaController.php para receber dados via JSON no $_POST['data_post']
  - Tratar para converter o objeto "encodado" p/ array para não impactar na forma como capturamos os campos no código atualmente e não aumentar a complexidade da implementação
- Verificar se o item da venda tem margem de lucro, se não tiver, calcular a margem automáticamente para não obrigar o sistema da POSI incluir um campo de margem de lucro (fazer isto para as 3 tabelas de preço).

**Comment by jheizerwandel** [comment]
modified:   controller/VendaController.php
