### ISSUE TITLE
Melhorias Comprovante de Venda

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#586]
- [x] Inserir no comprovante de entrega o CNPJ ou CPF do cliente e também as datas do parcelamento acordado seja no cheque, cartão de credito, boleto ou promessa de pagamento
- [x] Inserir tb o nome do vendedor

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/vendas-controller.js

Alterações API:
- dao/VendaDao.php
- util/rel_templates/comprovante_venda.php

**Comment by mtrystao** [comment]
Informacoes inseridas corretamente no romaneio
