### ISSUE TITLE
Problema - Venda Duplicada

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#587]
Identificar o motivo pelo qual vendas estao sendo duplicadas na Hage, impactos
Estoque
Faturamento da Loja
Comissão do Vendedor

**Comment by filipecoelho** [comment]
@matheuscaetano verificar se o problema persiste

**Comment by matheuscaetano** [comment]
Problema ocorria por causa da possibilidade de fechar a aba de opções (Cupom) após finalizar a venda, desta forma volta para a tela de pagamento dando a possibilidade de realizar a mesma venda novamente.
