### ISSUE TITLE
Estoque minino considerar deposito padrão

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#588]
A configuração de estoque minimo esta considerando a qtde de unidades existentes em todos os depósitos e não somente no deposito padrão do empreendimento, da forma como esta a configuração de estoque mínimo não funciona, pois, esta somente todas as unidades existentes em todos os depósitos impedindo o acompanhamento individual por empreendimento

**Comment by filipecoelho** [comment]
- [ ] Criar chave de configuração p/ configurar se quer considerar todos os depósitos no estoque minimo, ou apenas o estoque padrão

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js

**Comment by filipecoelho** [comment]
@rafaelqw já está no ambiente para o @matheuscaetano testar?

**Comment by rafaelqw** [comment]
Disponivel no ambiente de produçao para testes!

**Comment by matheuscaetano** [comment]
Teste realizado. Melhoria implantada com sucesso!!
