### ISSUE TITLE
Data de Validade esta somando todos os depósitos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#589]
O relatório de data de validade não esta mostrando a qtde de produtos existente por cada deposito mas sim a soma total, conforme as imagens em anexo

**Comment by mtrystao** [comment]
![data de validade 1](https://cloud.githubusercontent.com/assets/13888745/25775347/77379c16-3279-11e7-808c-398c24b16210.jpg)
![Uploading data de validade 2.jpg…]()

**Comment by mtrystao** [comment]
![data de validade 1](https://cloud.githubusercontent.com/assets/13888745/25775357/8786d3ca-3279-11e7-886d-1587da6b74bc.jpg)

**Comment by mtrystao** [comment]
![data de validade 2](https://cloud.githubusercontent.com/assets/13888745/25775362/a5737186-3279-11e7-85ff-7f7c5e86be02.jpg)

**Comment by rafaelqw** [comment]
Arquivos alterados API:
- dao/ProdutoDao.php

**Comment by matheuscaetano** [comment]
Testado, ajuste realizado com sucesso!
