### ISSUE TITLE
Relatório de Mov de Caixa

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#590]
O relatório de movimentação de caixa esta apresentado informação duplicada com mesmo ID de venda

**Comment by mtrystao** [comment]
[relatorio duplicado.pdf](https://github.com/WebliniaERP/webliniaerp-web/files/984461/relatorio.duplicado.pdf)

**Comment by filipecoelho** [comment]
@matheuscaetano verificar se o problema persiste

**Comment by matheuscaetano** [comment]
Após realizar alguns testes, e verificar em alguns empreendimentos não foi encontrado nenhum erro.
