### ISSUE TITLE
Relatório vendas diario por vendedor

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#591]
* Inserir o Titulo da 1a coluna No. da Venda 
* inserir uma nova coluna contendo o nome do cliente que fez a compra
* inserir coluna contendo o valor do desconto que sera Real (menos) Valor Venda (multiplicado) pela Qtde vendida
* Inserir combo para pesquisar percentual de Desconto
   Maior
   Menor
   Igual
   Diferente
* Ao Clicar no botão Exportar devera ser exportado todas as paginas geradas e nao somente a pagina que o usuario esta observando

**Comment by filipecoelho** [comment]
Foi atendido pelo chamado #635
