### ISSUE TITLE
Problemas ao selecionar vendedor/cliente na tela de vendas

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#599]
- Ao selecionar um vendedor/cliente nao exibe os mesmos no campo
- E ao buscar um vendedor/cliente aparece varios

**Comment by rafaelqw** [comment]
Alteraçoes Web:
- vendas.php
- js/angular-controller/vendas-controller.js

**Comment by matheuscaetano** [comment]
TESTADO! OK!
