### ISSUE TITLE
Criar chave de configuraçao de saldo devedor

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#601]
- Incluir chave de configuraçao na tela de Configuraçoes > Aba PDV

**Comment by rafaelqw** [comment]
Alteraçoes API:
- dao/DashboardDao.php
- dao/UsuarioDao.php

Alteraçoes WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js

**Comment by matheuscaetano** [comment]
TESTADO. OK!
