### ISSUE TITLE
Melhorar Relatorio de Movimentaçao de Caixa

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#604]
- Esclarecer as contas feitas nas formas de pagamentos no Relatorio de Movimentaçao de Caixa

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- js/angular-controller/rel_movimentacao_caixa-controller.js
- rel_movimentacao_caixa.php

**Comment by matheuscaetano** [comment]
Na linha "Saldo Dinheiro", esta parecendo: R$ {{ getSaldoDinheiro() | numberFormat : 2 : ',' : '.'}} ao invés do valor.

**Comment by rafaelqw** [comment]
Problema corrigido, queira validar novamente

**Comment by matheuscaetano** [comment]
Testado. Ok!!!
