### ISSUE TITLE
Incluir campo de observaçao no cupom nao fiscal

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#608]

**Comment by filipecoelho** [comment]
Client atualizado com as melhorias disponível em:
http://www.webliniaerp.com.br/client/webliniaer-fiscal-client.jar

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
