### ISSUE TITLE
Relatório de Resumo de Caixa

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#611]
O relatório de resumo de caixa não esta trazendo as informacoes consolidadas no cabeçalho da pagina, essa situação esta acontecendo no ambiente da Hage, mas provavelmente esteja acontecendo no ambiente dos clientes tb

**Comment by rafaelqw** [comment]
Alteraçoes WEB: 
- js/angular-controller/relatorio-consolidado-caixa-controller.js
