### ISSUE TITLE
Incluir opção de taxa de serviço no controle de comandas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#612]

**Comment by filipecoelho** [comment]
Arquivos alterados:
```- js/angular-controller/pdv-controller.js```

**Comment by filipecoelho** [comment]
@rafaelqw depois informe aqui quais arquivos você alterou para que possamos subir para o ambiente

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- controle-mesas.php
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/angular-services/user-service.js

**Comment by matheuscaetano** [comment]
Teste realizado. Melhoria implantada com sucesso! Taxa de 10% adicionada.
