### ISSUE TITLE
No PDV a Tabela Parceiro somente para ADM

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#617]
No perfil de Caixa esta aparecendo a opção de alterar o preço do produto para a Tabela Parceiro, com isso os vendedores estao gerando prejuízos para o dono da loja

**Comment by rafaelqw** [comment]
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('43', 'ver_tabela_parceiro', 'Ver Tabela Parceiro no PDV', 'Ver Tabela Parceiro no PDV');```

**Comment by mtrystao** [comment]
Perfil Caixa nao esta visualizando a Tabela Parceiro!!
