### ISSUE TITLE
Problemas com Relatorio Movimentaçao de Caixa

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#619]
- Nao aparece a forma de pagamento - Promessa de Pagamento nas FORMAS DE PAGAMENTOS

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- rel_movimentacao_caixa.php

Alteraçoes API:
- controller/MovimentacaoCaixaController.php
- dao/MovimentacaoCaixaDao.php'

**Comment by matheuscaetano** [comment]
Testado.
