### ISSUE TITLE
transferencia de produtos e impressão de pedido

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#624]
1- Quando vamos tratar um pedido recebido de transferencia de produtos os campos estao vindo preenchidos, esses campos não podem estar preenchidos pq o vendedor esta deixando de atender itens solicitados

2- Quando um detalhe de pedido é impresso os produtos estao ordem alfabética mas qdo vamos tratar no sistema a lista de produtos esta na ordem em que eles foram inseridos, precisa ser mantido um padrão ou seja pela ordem em que os produtos foram inseridos ou em ordem alfabética

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- js/angular-controller/pedido_transferencia_recebido-controller.js

**Comment by matheuscaetano** [comment]
Testado, ajustes realizados com sucesso!!!
