### ISSUE TITLE
Lançamentos Financeiros

### ISSUE THREAD

**Issue by matheuscaetano** [WebliniaERP/webliniaerp-web#626]
O mundo do corpo teve alguns problemas com Lançamentos Financeiros duplicados.

**Comment by filipecoelho** [comment]
@matheuscaetano sempre que abrir um chamado, identifique de qual cliente se refere através dos labels que iniciam com 3-

**Comment by filipecoelho** [comment]
@LEANDROCOELHO84 precisa entrar em contato com o cliente e identificar qual foi a situação que gerou o problema e tentar replicar para evidenciarmos e tratar.

**Comment by mtrystao** [comment]
Eu sugiro cancelar esse chamado, pois, não tivemos mais essa reclamação por parte do cliente, porem, deve ser finalizado os ajustes nos relatórios solicitados pelo mesmo que é o ponto que ele tem nos cobrado bastante

**Comment by filipecoelho** [comment]
ok @mtrystao
