### ISSUE TITLE
Relatório de Saldo devedor de Clientes

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#627]
Precisamos que o relatório seja colocado em ordem de valor do menor R$ para o maior R$

Precisamos de mais 02 colunas 
1- Quem vai Cobrar (nome da pessoa que esta atuando com o cliente) e 
2- Observação (inserir o histórico dos acionamentos) 

Pode ate ocultar as colunas de Endereço, pois, caso seja necessário podemos pegar pela tela de clientes/usuarios

**Comment by rafaelqw** [comment]
Relatorio ordenado por ordem decrescente de valor (do maior para o menor)
Arquivos alterados API:
- dao/UsuarioDao.php

**Comment by filipecoelho** [comment]
@rafaelqw já está no ambiente para o @matheuscaetano testar?

**Comment by rafaelqw** [comment]
Disponivel no ambiente de produçao para testes!

**Comment by matheuscaetano** [comment]
ainda não esta aparecendo as 02 colunas
1- Quem vai Cobrar (nome da pessoa que esta atuando com o cliente) e
2- Observação (inserir o histórico dos acionamentos)

**Comment by rafaelqw** [comment]
Esses dois pontos citados pelo @matheuscaetano ainda serão incluídos
