### ISSUE TITLE
Relatório de Curva ABC

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#629]
Precisamos criar o relatório de Curva ABC para Produtos e 
Fabricas
Objetivo, identificar de forma rápida a Curva ABC de produtos vendidos no período e a Curva ABC de fabricas que mais vendem

**Comment by mtrystao** [comment]
segue exemplo do relatório

**Comment by mtrystao** [comment]
[Curva A,B e C Hage 021.xlsx](https://github.com/WebliniaERP/webliniaerp-web/files/1396033/Curva.A.B.e.C.Hage.021.xlsx)
Modelo do Relatorio de Curva A, B, C

**Comment by mtrystao** [comment]
Conceito da Curva A, B e C

Parâmetros de observação da curva ABC[editar | editar código-fonte]

Curva ABC
A curva ABC, no caso de administração de estoques, apresenta resultados da demanda de cada item nas seguintes áreas:

giro no estoque;
proporção sobre o faturamento no período;
margem de lucro obtida.
Os itens são classificados como (Carvalho, 2002, p. 227):

de Classe A: de maior importância, valor ou quantidade, correspondendo a 20% do total (podem ser itens do estoque com uma demanda de 65% num dado período);
de Classe B: com importância, quantidade ou valor intermediário, correspondendo a 30% do total (podem ser itens do estoque com uma demanda de 25% num dado período);
de Classe C: de menor importância, valor ou quantidade, correspondendo a 50% do total (podem ser itens do estoque com uma demanda de 10% num dado período).
Os parâmetros acima não são uma regra matematicamente fixa, pois podem variar de organização para organização nos percentuais descritos.A definição das classes A, B e C obedece apenas a critérios de bom senso e conveniência dos controles a serem estabelecidos e é definida pelo gestor.

O que importa é que a análise destes parâmetros propicia o trabalho de controle de estoque do analista cuja decisão de compra pode se basear nos resultados obtidos pela curva ABC. Os itens considerados de Classe A merecerão um tratamento preferencial. Assim, a conseqüência da utilidade desta técnica é a otimização da aplicação dos recursos financeiros ou materiais, evitando desperdícios ou aquisições indevidas e favorecendo o aumento da lucratividade.

**Comment by rafaelqw** [comment]
Alterações Web:
- js/angular-controller/rel-curvas-abc-controller.js
- js/app.js
- rel_curvas_abc.php

Alterações API:
- controller/RelatorioController.php
- dao/RelatorioDao.php
- index.php

**Comment by filipecoelho** [comment]
@mtrystao o chamado já está disponível para testar a sua funcionalidade.
favor, realizar para que possamos subir para produção
