### ISSUE TITLE
Relatório de Movimentação de Caixa

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#631]
Incluir uma coluna informando o nome do vendedor que realizou a venda, pois, assim será possível saber os vendedores que realizaram vendas no dia

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- rel_movimentacao_caixa.php

Alteraçoes API:
- dao/MovimentacaoCaixaDao.php

**Comment by filipecoelho** [comment]
@rafaelqw já está no ambiente para o @matheuscaetano testar?

**Comment by rafaelqw** [comment]
Disponivel no ambiente de produçao para testes!

**Comment by matheuscaetano** [comment]
Teste realizado. Melhoria implantada com sucesso!!
