### ISSUE TITLE
Transferencia de produtos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#632]
Nao estou conseguindo ver produto disponível no estoque do deposito mesmo tendo saldo do produto ex. Estou na Hage 02, seleciono o empreendimento Deposito e coloco whey gold, sei que existe disponível o sabor chocolate de 5LBS mas não consigo visualizar esse produto e ele esta compartilhado com o empreendimento HAGE 02, essa situação acontece independente do perfil do usuário que esta logado

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- js/angular-controller/pedido_transferencia-controller.js

**Comment by rafaelqw** [comment]
Teste realizado, Tudo ok!
