### ISSUE TITLE
Relatório de Vendas por Produto por Mês

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#633]
Inserir o total de produtos (unidades) vendidas

**Comment by rafaelqw** [comment]
Arquivos Alterados WEB:
- rel_vendas_produto_mes.php

**Comment by filipecoelho** [comment]
@rafaelqw já está no ambiente para o @matheuscaetano testar?

**Comment by rafaelqw** [comment]
Disponivel no ambiente de produçao para testes!

**Comment by matheuscaetano** [comment]
Teste realizado. Melhoria Inserida com sucesso!!
