### ISSUE TITLE
Ticket Medio

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#634]
Criar um indicador no Dashoard atual indicando o ticket médio de vendas (R$) e produtos (UN)

**Comment by filipecoelho** [comment]
@mtrystao explique melhor como seria o indicador de ticket médio de produtos, pois o de vendas é simples, mas não entendi como seria o de produtos

**Comment by mtrystao** [comment]
A ideia desse indicador seria apresentar o valor médio das vendas e qtde média de produtos vendidos no período
ex 1 Ticket medio Valor por venda
R$1.000,00 | total vendido
                10 | total de vendas
R$100,00 | ticket medio de   vendas

Ex 2 Ticket medio Produtos Vendidos
1500 | total de und   vendidas
  300 | total de vendas
      5 | media de produtos   vendidos

**Comment by rafaelqw** [comment]
Alterações WEB:
- dashboard.php
- js/angular-controller/dashboard-controller.js

Alterações API:
- controller/DashboardController.php
- dao/DashboardDao.php
- index.php
