### ISSUE TITLE
Relatório de Vendas por Vendedor Diário

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#635]
Inserir filtro para busca de % de desconto sendo
Maior
Menor ou 
Igual a uma faixa especifica

Inserir Total
Custo
Venda Real
Venda c/ Desconto
Qual a diferença entre o Valor Real e o Valor c/ Desconto (identificar quanto e qual o % foi concedido de desconto no período)

**Comment by rafaelqw** [comment]
Alterações WEB:
- rel_vendas_vendedor_dia_dia.php
- js/angular-controller/rel-diario-vendedor-controller.js

**Comment by LEANDROCOELHO84** [comment]
Inserir filtro para busca de % de desconto sendo 
 Maior 
Menor 
Igual a uma faixa especifica

Inserir Total
Custo
Venda Real
Venda c/ Desconto

Qual a diferença entre o Valor Real e o Valor c/ Desconto (identificar quanto e qual o % foi concedido de desconto no período)

testado e funcionando corretamente

**Comment by mtrystao** [comment]
nao esta limpando o filtro de vendedor após gerar o relatorio

**Comment by filipecoelho** [comment]
@rafaelqw vc corrigiu os erros apontados?

**Comment by rafaelqw** [comment]
Problema corrigido!
Alteração WEB:
- js/angular-controller/rel-diario-vendedor-controller.js

**Comment by LEANDROCOELHO84** [comment]
teste realizado  . somente limpa o filtro quando aplicado a função no botão 
não quando gera o relatório.
