### ISSUE TITLE
Relatório de Sangria

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#636]
Inserir no relatório de Sangrias as colunas de Favorecido e Plano de Contas e logo abaixo do total de sangrias incluir o total de vezes que Plano de contas aparece e a soma do plano de contas  (objetivo: saber o detalhamento de sangrias por retirada)

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- js/angular-controller/relatorio-sangria.js
- rel_sangria.php

Alteraçoes API: 
- dao/RelatorioDao.php

**Comment by filipecoelho** [comment]
@rafaelqw já está no ambiente para o @matheuscaetano testar?

**Comment by rafaelqw** [comment]
Disponivel no ambiente de produçao para testes!

**Comment by rafaelqw** [comment]
Teste realizado, tudo ok!
