### ISSUE TITLE
Criar 02 empreendimentos Biro Muscle e compartilhar produtos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#637]
Criar os empreendimentos

1 - Biro Muscle - Santos
2 - Biro Muscle - Ipiranga

Obs: A Loja Biro Muscle Santos sera a Loja Matriz e devera compartilhar os produtos com a loja do Ipiranga

**Comment by rafaelqw** [comment]
Procedimentos realizados!
