### ISSUE TITLE
Relatório Produtos em Estoque

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#638]
Inserir a soma em cada coluna
Coluna Qtde unidade colocar na coluna Certa
Coluna Total de Custo

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- js/angular-controller/relatorio-total-produto-estoque-controller.js
- rel_total_produto_estoque.php

**Comment by filipecoelho** [comment]
@rafaelqw já está no ambiente para o @matheuscaetano testar?

**Comment by rafaelqw** [comment]
Disponivel no ambiente de produçao para testes!

**Comment by matheuscaetano** [comment]
Teste realizado. Melhoria implantada com sucesso!!

**Comment by LEANDROCOELHO84** [comment]
teste realizado e verificado que  os totais das colunas não são condizentes com os valores das colunas das respectivas colunas conforme foto em anexo.
![rel_total_produto_estoque.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46fa91961c968cbd8ee58053b652f4813d4918763a10ac3a6580a164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff58a87453f1b041980fa583ca2984fca5ee406.png)

**Comment by LEANDROCOELHO84** [comment]
testado novamente com as configurações de tabela de preço e retornou corretamento.
conforme anexo.
![rel_total_produto_estoque_ok.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46fa91961c968cbd8ee58053b652f4813d4918763a10ac3a6580dc27b40037431f1d11f6140b1b56f6eb8c2df0b73474db095deed73f5f7cc16b11adb9834ded09bd32975dc7e7e2de139db17770a599855d3f160f198cfe5c3ca59f4fcd51f44fe85f18.png)
