### ISSUE TITLE
e-commerce Hage Suplementos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#639]
Seguem algumas opções de Templates para o e-commerce da Hage em ordem de prioridade de interesse, precisamos identificar qual modelo pode ser utilizado em nossa plataforma Prestashop, para iniciarmos o desenvolvimento e implantação
01 -http://labbluesky.com/prestashop/lab_hermes/en/
02 - http://demo.posthemes.com/pos_t90/layout3/en/
03 - http://xpert-idea.com/prestashop/jakiro/demo/two/en/
04 - http://demo.posthemes.com/pos_facon/en/
05 - http://preview.themeforest.net/item/lifestyle-prestashop-responsive-theme/full_screen_preview/6667813

**Comment by rafaelqw** [comment]
Temas que sao compativeis:
01 - http://labbluesky.com/prestashop/lab_hermes/en/
02 - http://demo.posthemes.com/pos_t90/layout3/en/
03 - http://xpert-idea.com/prestashop/jakiro/demo/two/en/
05 - http://preview.themeforest.net/item/lifestyle-prestashop-responsive-theme/full_screen_preview/6667813

**Comment by filipecoelho** [comment]
Produtos importados com fotos e todas as informações, agora podemos dar continuidade na implantação
