### ISSUE TITLE
Problema na tela de Devoluções

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#643]
Campo de Perfil esta listando toda tabela de perfil, devera listar apenas a configuraçao do usuario na tela de configuraçoes

**Comment by rafaelqw** [comment]
Alterações WEB:
- devolucao.php
- js/angular-controller/devolucao-controller.js

**Comment by LEANDROCOELHO84** [comment]
teste efetuado e esta aparecendo somente  os perfil   (varejo / atacado / caixa )
![webliniaerp-web_devolucao.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46ff91982f8b8da08eecad53e94af596164222652608b628718aa164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b041980f95932a49943cb5ae406.png)
