### ISSUE TITLE
Criar chave de configuraçao

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#645]
Criar chave de configuraçao para desabilitar tabelas de vendas no geral. Exemplo: Loja nao vende no Atacado e Intermediario

**Comment by filipecoelho** [comment]
@matheuscaetano validar em todas as telas do sistema onde aparece a informação da tabela de preço

**Comment by LEANDROCOELHO84** [comment]
VALIDAÇÃO CONCLUÍDA.
[TAB PRECOS.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46dcb5b863b2b18cacc68c01e81fe086264c22703d46f96925d3e579e7167a04095c48fe41505812fcf8882af4e43477984019af80330b2b9b645bf9fa9015ad00b32a8a4a84b6be894ac7ee3821e28e9d02.xlsx)

**Comment by rafaelqw** [comment]
Alterações WEB:
- dashboard.php
- empreendimento_config.php
- grade.php
- pdv.php
- produtos-optimized.php
- produtos.php
- js/angular-controller/dashboard-controller.js
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/grade-controller.js
- js/angular-controller/lancamentos-controller.js
- js/angular-controller/pdv-controller.js
- js/angular-controller/perfis-controller.js
- js/angular-controller/produtos-controller.js
- js/angular-controller/produtos_optimized-controller.js
- js/angular-controller/relatorio-analitico-estoque-controller.js
- js/angular-controller/relatorio-total-produto-estoque-controller.js
- js/angular-services/user-service.js
- rel_analitico_estoque.php
- rel_total_produto_estoque.php
- rel_vendas_fabricante.php

Melhorias API:
- dao/EstoqueDao.php

**Comment by rafaelqw** [comment]
Telas alteradas:
[ ] - Dashboard
[ ] - 
[ ] - 
[ ] - 
[ ] -

**Comment by LEANDROCOELHO84** [comment]
<div ng-if="item.body_html" ng-bind-html="item.body_html" class="github-markdown ng-binding ng-scope" open-links-in-new-tab=""><p>Telas alteradas:</p>
<ul class="contains-task-list">
<li class="task-list-item enabled"><input checked="" class="task-list-item-checkbox" id="" type="checkbox"> Dashboard</li>
<li class="task-list-item enabled"><input checked="" class="task-list-item-checkbox" id="" type="checkbox"> Produtos</li>
<li class="task-list-item enabled"><input checked="" class="task-list-item-checkbox" id="" type="checkbox"> Produtos Otimizado</li>
<li class="task-list-item enabled"><input checked="" class="task-list-item-checkbox" id="" type="checkbox"> Vitrine</li>
<li class="task-list-item enabled"><input checked="" class="task-list-item-checkbox" id="" type="checkbox"> PDV</li>
<li class="task-list-item enabled"><input checked="" class="task-list-item-checkbox" id="" type="checkbox"> Perfis</li>
<li class="task-list-item enabled"><input checked="" class="task-list-item-checkbox" id="" type="checkbox"> Rel Estoque Analitico</li>
<li class="task-list-item enabled"><input checked="" class="task-list-item-checkbox" id="" type="checkbox"> Rel Produtos em Estoque</li>
</ul></div>

Todas tags funcionando com e sem o filtro
