### ISSUE TITLE
Romaneio de Vendas c/ problemas

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#654]
O Romaneio de compras não esta "puxando"o saldo devedor do cliente, devido a essa situação no momento da impressão o cliente esta ficando com credito mas na verdade deveria ZERAR o saldo, contudo, no sistema o Extrato esta apresentando as informacoes certas, a falha esta no Romaneio

**Comment by filipecoelho** [comment]
@LEANDROCOELHO84 preciso que replique a situação que gerou o problema e evidencie para que o @rafaelqw possa tratar

**Comment by LEANDROCOELHO84** [comment]
@mtrystao Poderia informar qual o ID da venda e o empreendimento que a venda foi realizada ?

**Comment by mtrystao** [comment]
Vou providenciar as informacoes solicitadas e anexo aqui

**Comment by filipecoelho** [comment]
@mtrystao favor incluir as informações necessárias para que se possa evidenciar o problema e proceder com o tratamento.

**Comment by rafaelqw** [comment]
@mtrystao favor enviar as informações para tratar o chamado!

**Comment by filipecoelho** [comment]
@mtrystao como as informações não foram enviadas, estou reprogramando a tarefa para a próxima semana

**Comment by rafaelqw** [comment]
Fiz uma simulação efetuando o pagamento do saldo devedor do cliente Alexandre Barufi (R$ 4.616,26).
Lancei uma venda com o cliente associado no valor de R$ 1,50. Não trouxe nenhum saldo de crédito.
Em seguida lancei outra venda no valor de R$ 150,00 e também não trouxe nenhum saldo de crédito para o cliente.
