### ISSUE TITLE
Cadastro Rapido Busca End por CEP

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#660]
Inserir na tela de cadastro rapido o mecanismo para buscar enderece através do CEP da mesma forma como temos na tela de usuários/clientes

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- js/angular-controller/pdv-controller.js

**Comment by rafaelqw** [comment]
Teste realizado , tudo ok!
