### ISSUE TITLE
Criar o empreendimento Hulk Suplementos Santos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#663]
Criar o empreendimento Hulk Suplementos Santos com os produtos e preços igual a Loja Hulk Suplementos Hortolândia 
Apenas os Jr e a Priscila terão acesso a esse novo empreendimento
Deve ser criado um perfil Sub Admin para o Marcio (responsável pela loja) esse usuário não poderá excluir vendas, alterar estoque ou preço dos produtos
O Marcio devera ser treinado para utilização do sistema (13) 97401-2227fica

**Comment by rafaelqw** [comment]
Empreendimento criado,  produtos, valores compartilhados e usuários compartilhados e  criados.

**Comment by matheuscaetano** [comment]
Treinamento realizado, e login e senha criado!!
