### ISSUE TITLE
Criar Limite de Credito

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#667]
Precisamos criar um mecanismo onde seja inserido um limite de credito para o cliente, dessa forma, as compras no Fiado e Parcelado deverão ser baseadas através desse limite, com isso o cliente não podera comprar um valor maior que o limite de credito disponível, 
Essa função podera ou não ser habilitada para o empreendimento ou para o cliente

**Comment by rafaelqw** [comment]
Alterações BD:
- ```ALTER TABLE tbl_usuarios ADD COLUMN vlr_limite_credito DOUBLE NULL;```

**Comment by lukasqw** [comment]
- [ ] Trocar a mensagem exibida quando a venda ultrapassar o saldo do cliente.
- [ ] corrigir o calculo do saldo final.

**Comment by lukasqw** [comment]
- [ ] Não é possível finalizar uma venda com clientes com saldo negativo, mas sem limite de saldo ativado.
- [ ] No segundo botão de finalizar não deve exibir a mensagem de saldo insuficiente.

**Comment by filipecoelho** [comment]
- [ ] Ao entrar no modo depósito, selecionar o cliente, adicionar produtos, clicar em receber e depois cancelar o pagamento é possível finalizar sem exibir a mensagem
