### ISSUE TITLE
Relatório de Movimentação de caixa via impressora termica

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#673]
O relatório de movimentacao de caixa via impressora termica esta apresentando divergência do relatório de movimentacao de caixa via PDF

**Comment by mtrystao** [comment]
![mov caixa](https://user-images.githubusercontent.com/13888745/30766988-4eb95338-9fcf-11e7-9eb5-517b04680e67.jpg)

**Comment by filipecoelho** [comment]
Problema resolvido.

Será necessário atualização em massa de todos os clientes que utilizam o programa webliniaerp-fiscal-client.jar
