### ISSUE TITLE
Subir o Certificado da Goldman

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#674]
Favor subir para a Focus e configurar o empreendimento da Goldman com o Certificado Digital
Certificado: Valid
Ticket: 70317036142
Senha: GOLDMAN1234

**Comment by matheuscaetano** [comment]
Aguardando retorno da Soraia, quanto ao Ticket do certificado para emissão

**Comment by filipecoelho** [comment]
@mtrystao como está essa questão?

**Comment by filipecoelho** [comment]
@filipecoelho @marcio_tristao ??

**Comment by mtrystao** [comment]
Continuo aguardando retorno da Soraia, ela informou que o contrato social estava ilegível e por esse motivo foi travado, temos que aguardar o posicionamento

**Comment by filipecoelho** [comment]
@mtrystao Ok!

**Comment by mtrystao** [comment]
Soraia, continua aguardando retorno do Contador

**Comment by mtrystao** [comment]
Pessoal, problema resolvido com o Certificado da Goldman, podem dar continuidade na subida no mesmo e na sequencia instruir o cliente em como utilizar. Obrigado

**Comment by LEANDROCOELHO84** [comment]
Tabela de Produtos já configurados como fiscal só esta faltando alguns produtos  que sera necessário solicitar para contabilidade.  para impressão dos cupom só é necessário fazer testes no cliente para concluir o chamado

**Comment by LEANDROCOELHO84** [comment]
tabelas de produtos e empreendimento configurado para impressão fiscal
feito testes e tudo funcionando.
