### ISSUE TITLE
Cadastro Rapido na esta permitindo CNPJ - 4 LIFE

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#675]
Ao tentar cadastrar um CNPJ via Cadastro Rapido esta solicitando a inserção do CPF e não permitindo o cadastro da empresa

**Comment by rafaelqw** [comment]
Alteraçoes WEB:
- js/angular-controller/pdv-controller.js

Alteraçoes API:
- controller/ClienteController.php

**Comment by rafaelqw** [comment]
Teste realizado, tudo ok!
