### ISSUE TITLE
Subir certificado digital CLF Artesanato

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#682]
Favor, instalar e configurar o certificado digital da CLF Artesanato (LOJA)
Certificado da Valid
www.certificadodigital.com.br
Protocolo: 000001008129183
Senha: 28445076

**Comment by LEANDROCOELHO84** [comment]
foi vinculado o sat ao CNPJ  -- Marcia da CLF pediu para fazer a configuração do equipamento no dia 25/09

**Comment by LEANDROCOELHO84** [comment]
Equipamento instalado
