### ISSUE TITLE
Goldman - Diferença de Produtos no momento de fechar a comanda

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#688]
Orcamento #187257 esta com 5 Skol Litro, porem, no momento de fechar a Comanda so constam 4 Skol Litrao, estou inserindo as fotos para evidenciar

**Comment by mtrystao** [comment]
![goldman 1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46ef9b96278f82a7cfb8fd0fe64de29b234324676b5ee17e2683b270eb437e075c591cac495f0944fdf88879f4be3b62964e49bc8f3900299f7744eeaa880dbe09b0218e4f83b0bd8349c4e13d21e199c2.jpg)

**Comment by mtrystao** [comment]
![goldman 2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46ef9b96278f82a7cfbbfd0fe64de29b234324676b5ee17e2683b270eb437e075c591cac495f0944fdf88879f4be3b62964e49bc8f3900299f7744eeaa880dbe09b0218e4f83b0bd834ac1ed3f27e399c2.jpg)

**Comment by mtrystao** [comment]
![goldman 3.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46ef9b96278f82a7cfbafd0fe64de29b234324676b5ee17e2683b270eb437e075c591cac495f0944fdf88879f4be3b62964e49bc8f3900299f7744eeaa880dbe06b0218e4f83b0bd834ac6e93420ee99c2.jpg)

**Comment by mtrystao** [comment]
![goldman 4.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46ef9b96278f82a7cfbdfd0fe64de29b234324676b5ee17e2683b270eb437e075c591cac495f0944fdf88879f4be3b62964e49bc8f3900299f7744eeaa880dbe06b0218e4f83b0bd834bc3e83b22ee99c2.jpg)

**Comment by matheuscaetano** [comment]
Erro corrigido. Tudo funcionando normalmente!
