### ISSUE TITLE
Transferencia de produtos apenas para produtos disponíveis no Deposito

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#691]
O processo de pedido de transferencia de produtos sempre foi para que as lojas so pudessem pedir produtos disponíveis no estoque do Deposito, por algum motivo desde o ultimo final de semana esta sendo possível visualizar todos os produtos cadastrados no empreendimento Deposito, com isso as lojas estao pedido produtos que nem trabalhamos mais, por favor, realizar o ajuste necessário para que seja possível solicitar apenas os produtos disponíveis no estoque do Deposito

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pedido_transferencia-controller.js

**Comment by LEANDROCOELHO84** [comment]
efetuado testes  na transferência do produto estão retornando da forma estiver que estiver  configurado no estoque do produto  . 
OBS se o produto estiver sem data de validade ou vencido no estoque não retorna na pesquisa. de transferência de produtos conforme  IMG em anexo
![correção chamado 961.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46eb9b883187206e2c2ab003a755f199284228337052f2693cc7f33ab0487e021b4d44be445e0945f4fdd87ef0b53a228a540cbbd16c5e75946f19abaa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4e3f18041080fe5b33a5905985.png)
