### ISSUE TITLE
Especificação de produtos

### ISSUE THREAD

**Issue by matheuscaetano** [WebliniaERP/webliniaerp-web#694]
Toda vez que vão abrir uma comanda e adicionar produtos pelo celular, se não especificar a questão de sabor ou cor na descrição não aparece, ou seja, a unica forma de ver é pelo computador ou então clocando na descrição.

**Comment by rafaelqw** [comment]
Alterações WEB:
- controle-mesas.php

**Comment by rafaelqw** [comment]
Teste realizado, tudo ok!
