### ISSUE TITLE
CBR Salgaderia Informacoes Fiscais

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#695]
Favor, atualizar a lista de produtos da CBR Salgaderia conforme planilha em anexo, TEM QUE OLHAR A PLANILHA PARA VALIDAR AS INFORMACOES, essa atualizada é necessária para que seja possível a impressão de Cupom Fiscal

**Comment by mtrystao** [comment]
[Cópia de produtos salgaderia.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46cb3749338b82e98becff53b652f4813d4934333a05af2c7181e63ab643394d4d1f0cf31b0d0c00eef39b2ea0e03d788e0d5ebbd26b0d74ce3a47acb9831eed53b227995397f4edd4189fb5646fb2c99d452c1f021288fa5d32a2904fc95aff4ce34447e9.xlsx)

**Comment by rafaelqw** [comment]
Informações  atualizadas!
