### ISSUE TITLE
PDV - arredondamento cod de barras

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#697]
Ao procurar um produto pelo campo do nome e "bater"o cod de barras o produto esta sendo apresentado corretamente, porem, o código de barras esta sendo arredondado, favor, corrigir para que o código de barras seja apresentado corretamente

**Comment by mtrystao** [comment]
![PDV cod de barras.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46d8b0ac63818cadcfedba03a65ce2862855653f6b14b1247a80e03cfd18395459094fa445090a12ffffdb2baeb16a708b5d0abf83655866da2f53fde6d640e258f075c95d8fa4be8a46c1ed3d22ee828d47361f02198bed10.jpg)

**Comment by filipecoelho** [comment]
Conforme imagens anexas, foi replicado o cenário e o problema não foi identificado. 
Sinalizando chamado como inválido!

![Captura de Tela 2018-01-07 às 14.37.10.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550338e01befa51300278352/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227149f37a3dd5b468beee9b124f5e4ab2425f4145fceb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da59ff41e04854a1103260e67e327943930c38.png)

**Comment by filipecoelho** [comment]
- [ ] @rafaelqw atualizar os 2 ambientes
- [ ] @LEANDROCOELHO84 testar o chamado

**Comment by LEANDROCOELHO84** [comment]
- [ ] @rafaelqw atualizar os 2 ambientes
- [ ] @LEANDROCOELHO84 testar o chamado
