### ISSUE TITLE
Criar empreendimento Strong Suplementos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#698]
Por favor, queira criar o empreendimento Strong Suplementos e subir o produtos os produtos da Hage para esse novo empreendimento
ATENCAO o novo empreendimento deve subir no ambiente de clientes

**Comment by rafaelqw** [comment]
Empreendimento criado, falta rodar uma parte do script para replicação dos produtos.

drop table if exists tmp_produtos_replicacao;

-- selecionando os produtos que serão replicados
create temporary table tmp_produtos_replicacao
select 
	prd.codigo_barra,
	prd.nome,
	0 as id_fabricante,
	fab.nome_fabricante,
	0 as id_categoria,
	cat.descricao_categoria,
	0 as id_tamanho,
	tam.nome_tamanho,
	0 as id_cor,
	cor.nome_cor,
	prd.cod_ncm,
	prd.cod_forma_aquisicao,
	prd.cod_origem_mercadoria,
	prd.cod_tipo_tributacao_ipi,
	prd.dsc_unidade_medida
from tbl_produto_empreendimento as tpe
inner join tbl_produtos as prd on prd.id = tpe.id_produto
left join tbl_fabricante as fab on fab.id = prd.id_fabricante
left join tbl_categorias as cat on cat.id = prd.id_categoria
left join tbl_tamanho as tam on tam.id = prd.id_tamanho
left join tbl_cor_produto as cor on cor.id = prd.id_cor
where tpe.id_empreendimento = 111 -- não mudar esse parâmetro
	and prd.id <> (
		select valor 
		from tbl_configuracao 
		where id_empreendimento = 111 -- não mudar esse parâmetro 
			and nome = 'id_produto_debito_anterior_cliente'
	);

alter table tmp_produtos_replicacao modify column id_fabricante int(11);
alter table tmp_produtos_replicacao modify column id_categoria int(11);
alter table tmp_produtos_replicacao modify column id_tamanho int(11);
alter table tmp_produtos_replicacao modify column id_cor int(11);



-------------------



-- atualizando id's de referência dos tamanhos
update tmp_produtos_replicacao as tmp
left join tbl_tamanho as tam on tam.id_empreendimento = 203 and tam.nome_tamanho = tmp.nome_tamanho
set tmp.id_tamanho = tam.id;

-- atualizando id's de referência das cores
update tmp_produtos_replicacao as tmp
left join tbl_cor_produto as cor on cor.id_empreendimento = 203 and cor.nome_cor = tmp.nome_cor
set tmp.id_cor = cor.id;

-- cadastrando os produtos
insert into tbl_produtos (codigo_barra, nome, id_fabricante, id_categoria, id_tamanho, id_cor, cod_ncm, cod_forma_aquisicao, cod_origem_mercadoria, cod_tipo_tributacao_ipi, dsc_unidade_medida, id_empreendimento)
select codigo_barra, nome, id_fabricante, id_categoria, id_tamanho, id_cor, cod_ncm, cod_forma_aquisicao, cod_origem_mercadoria, cod_tipo_tributacao_ipi, dsc_unidade_medida, 203
from tmp_produtos_replicacao;

insert into tbl_produto_empreendimento
select null, id, id_empreendimento
from tbl_produtos
where id_empreendimento = 203;

**Comment by LEANDROCOELHO84** [comment]
empreendimento criado e produtos importados retornando, porem com valores zerados
