### ISSUE TITLE
Relatorio de Fabricante

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#707]
Realizar o ajuste no relatorio de fabricantes a fim de rankear as fabricas e detalhar as vendas do período selecionado conforme informacoes e modelo do relatorio passadas ao Rafael

**Comment by filipecoelho** [comment]
@mtrystao favor anexar o relatório modelo no chamado para que possamos analisar e implementá-lo

**Comment by mtrystao** [comment]
[Curva A,B e C Hage 021.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46cb81883583c388c3cbff46e47eb0bc284122337956f2693cc7f33ab0487e021b4d44be445e0945f4fdd87ef0b53a228a540cbbd16c5e75946f19abaa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4f371e01118cfc5e37a19a5985.xlsx)

**Comment by mtrystao** [comment]
modelo de relatorio foi anexo ao chamado, qualquer duvida, favor, comunicar

**Comment by rafaelqw** [comment]
Alterações WEB
js/angular-controller/rel-vendas-fabricante-controller.js
rel_vendas_fabricante.php

Alterações API
controller/RelatorioController.php
dao/RelatorioDao.php
index.php
