### ISSUE TITLE
Lançamentos Financeiros - Modal

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#708]
Vc realiza um lançamento financeiro completo em cheque por exemplo e na sequencia vai realizar um Outro nao esta limpando o Modal e com isso aparece o cliente anterior, e se vc escolher a mesma forma de pagamento ja aparece a qtde de lançamentos inseridas anteriormente, para que funcione corretamente e necessário que vc atualize a pagina F5 ai sim limpa o Modal e vc consegue realizar o novo Lançamento Financeiro, isso acontece nos 02 ambientes Hage e Clientes

**Comment by filipecoelho** [comment]
ALTERAÇÕES WEB:
- js/angular-controller/lancamentos-controller.js

**Comment by LEANDROCOELHO84** [comment]
realizado teste 
[x] - js/angular-controller/lancamentos-controller.js
