### ISSUE TITLE
Falha orçamento nao limpa o Modal

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#710]
Passo para identificar a falha
1- Lance um Orçamento para um cliente qualquer
2- Clique em voltar ao PDV
3- Lance uma nova venda
4- Insira os produtos no carrinho
5- clique em Receber e lance a forma de pgto
6- Conclua a venda
7- Veja na sequencia que a venda foi lançada como Orçamento e nao como Venda, mesmo tendo havido recebimento de valor
8- Ao olhar no Extrato do Cliente sera possível identificar que entrou o pgto mas nao a saída dos produtos

**Comment by mtrystao** [comment]
![falha modal orcamento.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46ee95962b83c3a480edbe4fe452e297284b227d3d0be1673295f127b54778154d555ca9470e5e4cf8a8dc7da5b06e70825b5dedd06c5e26943516bea4905dee5fee7fd616cfe3fe9846d2ea3d2fe68e8f473916061f81f65b31a78b06.jpg)

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js
