### ISSUE TITLE
Divisão de pagamento em boleto bancário

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#711]
- [ ] Incluir mecanismo de cálculo de parcelas em Boleto Bancário
  - calcular as datas baseado na quantidade de parcelas e na periodicidade informada
  - calcular o valor das parcelas baseado na quantidade parcelas
  - considerar arredondamento apenas na última parcela

**Comment by filipecoelho** [comment]
Considerar o uso do mesmo combobox de periodicidade da criação de O.S.

**Comment by filipecoelho** [comment]
Tempo estimado: 6h

**Comment by mtrystao** [comment]
Nao esta sendo feito a divisao do valor total pelo numero de parcelas inseridas no lancamento

![parcelamento.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46f8958820878fa882ecb157ab1fbcd6395428792c07b7692ac7b67eb91323550e0a18af470a5f4cfbaf892aa7b76e22825b19f1c32f0e2a92624cf5f2d75dad0ba821834584b3be8c49c0ee3c27e5838e492c53.jpg)

**Comment by jheizerwandel** [comment]
Arquivo alterado 
 pdv.php

**Comment by mtrystao** [comment]
nao esta aparecendo o campo periodicidade

![lancamento.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e4959420838eac81fdb001e81fe086264c22703d46f96925d3e579e7167a04095c48fe41505812fcf8882af4e43477984019af80330b2b9b645bf9fa9015ad00bd2a8a4a87b0b58c4ac1e03c21e58e9d02.jpg)

**Comment by filipecoelho** [comment]
a melhoria foi implementada apenas no PDV inicialmente
