### ISSUE TITLE
Strong Suplementos - Subir produtos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#713]
É necessario subir os produtos da Hage Suplementos para o novo empreendimento que esta criado no ambiente de clientes, referente ao chamado 698 e tb agendar o treinamento com o cliente para ele comece a usar o sistema(11) 94032-9460

**Comment by mtrystao** [comment]
Boa noite!!
Rafa, estou vendo os produtos que vc subiu para a Strong e esta estranho
Os produtos estao repetidos, nao tem codigo de barras, produtos que existem na Hage nao estao nesse empreendimento
Ex: Ther Curse, Flip Belt, Cinturao etc
Por favor, queira verificar o quanto antes essa base, temos que liberar o ambiente para o cliente

**Comment by filipecoelho** [comment]
@mtrystao os produtos já estão importados e o ambiente está disponível, como ficou a implantação deste cliente?

**Comment by mtrystao** [comment]
estou aguardando a resposta da Gilmara para que o treinamento seja realizado amanha as 15h00, assim que a cliente confirmar comunico a todos para que o Rafa possa se programar

**Comment by LEANDROCOELHO84** [comment]
produtos 
284807	797776066544	THE CURSE - GREEN APPLE  ---- RETORNANDO CORRETAMENTE
286002		                THE FLIP BELT VERDE LIMAO - NÃO RETORNA COD. BARRA -PQ NÃO TEM
46447	7894112600370	CINTURÃO - P	ACESSÓRIOS - RETORNANDO CORRETAMENTE
produtos importados retornando da mesma forma que esta no banco da HAGE.
