### ISSUE TITLE
Lançamento financeiro fundo de reserva

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#715]
o valor de fundo de reserva (TROCO) esta sendo considerado como despesa e todo dia é incrementado um valor adicional a Despesa Paga para fornecedor, essa informacao nao esta correta pq o valor nao sai da loja para algum fornecedor como pgto, mas sim é uma reserva que fica na loja
e possível ver essa informacao através das lojas da Hage onde todos os dias é aberto o caixa com um valor especifico (R$ 200,00 na maioria das vezes) e qdo vc olha para o Dashboard indicador Total pago a Fornecedores esta com valor, mas as lojas da Hage nao fazem pagto a fornecedores, todos os pagtos sao concentrados no deposito

**Comment by filipecoelho** [comment]
aplicar atualização do financeiro no ambiente da hage

**Comment by filipecoelho** [comment]
- [ ] @rafaelqw atualizar os 2 ambientes
- [ ] @LEANDROCOELHO84 testar o chamado
