### ISSUE TITLE
Bloquear botão Deletar produtos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#721]
Favor, bloquear o perfil CAIXA em todos os empreendimento da Hage Suplementos para que ele nao possa deletar produtos através da tela de produtos

**Comment by rafaelqw** [comment]
Só precisava subir o arquivo para produção da Hage

**Comment by LEANDROCOELHO84** [comment]
teste realizado com usuários no qual não tem mais a opção de de excluir vendas.
