### ISSUE TITLE
Ocultar Valor de Custo Mod Transferencia

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#722]
Favor, ocultar o valor de custo do perfil CAIXA nos empreendimentos da Hage no modulo de Transferencia e Envio de mercadoria, os vendedores estao tendo acesso ao valor de custo dos produtos e com isso dando descontos maiores do que o permitido e questionando uma serie coisas para o Moamar

OBS: ESSA SITUACAO ACONTECE NO MOMENTO EM QUE VC VAI RECEBER MERCADORIA

**Comment by rafaelqw** [comment]
Alterações WEB:

- pedido_transferencia.php
- js/angular-controller/pedido_transferencia-controller.js

**Comment by LEANDROCOELHO84** [comment]
teste realizado tudo não apresenta mais o valor do custo para perfil caixa.
