### ISSUE TITLE
Criar chave de configuração para controle de data de validade

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#725]
Precisamos criar uma chave de configuração para que o usuario escolha a forma como deseja controlar a venda de produtos por data de validade no momento de lançar a venda no PDV
1- FIFO
2- Combo Box indicando as datas de validade existente por produto
3- Sem controle de data de validade (Default)

**Comment by filipecoelho** [comment]
Tempo estimado: 24h

**Comment by filipecoelho** [comment]
Previsão de entrega: 22/01/2018

**Comment by jheizerwandel** [comment]
ALTERAÇÕES DB
	ALTER TABLE `tbl_produtos`
		ADD COLUMN `flg_controlar_validade` INT(1) NULL DEFAULT '0' AFTER `flg_controlar_lote`;

ARQUIVOS ALTERADOS WEB
	modified:   js/angular-controller/pdv-controller.js
	modified:   js/angular-controller/produtos-controller.js
	modified:   pdv.php
	modified:   produtos.php

ARQUIVOS ALTERADOS API
	modified:   controller/ProdutoController.php
	modified:   controller/VendaController.php
	modified:   dao/EstoqueDao.php
	modified:   dao/ProdutoDao.php
	modified:   model/ProdutoTO.php
