### ISSUE TITLE
Criar empreendimento Food House

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#727]
Criar empreendimento Food House De Santa Bárbara D'Oeste
cliente indicacao da Posi

**Comment by filipecoelho** [comment]
Procedimento de criação de empreendimentos p/ POSI:
- Criar empreendimento no sistema (processo normal)
- Conceder permissão aos usuários (Especialistas e )
- Criar usuário ```VENDEDOR PADRÃO``` e criar chave de configuração ```id_vendedor_padrao```
- Criar ```CONTA BANCARIA PADRÃO```
- Criar ```MAQUINETA PADRÃO``` e criar chave de configuração ```id_maquineta_padrao```
- Criar ```DEPOSITO PADRÃO``` e configura-lo como padrão na tela de configurações
- Criar ```CAIXA PADRÃO``` e criar chave de configuração ```id_caixa_padrao```

**Comment by LEANDROCOELHO84** [comment]
<ul>
<li>Criar empreendimento no sistema (processo normal) - OK</li>
<li>Conceder permissão aos usuários (Help Desk POSI e Tecnicos POSI) - OK</li>
<li>Criar usuário <code>VENDEDOR PADRÃO</code> com perfil de caixa e criar chave de configuração <code>id_vendedor_padrao</code> - OK</li>
<li>Criar conta bancária <code>CONTA BANCARIA PADRÃO</code> - OK</li>
<li>Criar maquineta <code>MAQUINETA PADRÃO</code> e criar chave de configuração <code>id_maquineta_padrao</code> - OK</li>
<li>Criar deposito <code>ESTOQUE PADRÃO</code> e configura-lo como padrão na tela de configurações - OK</li>
<li>Criar caixa <code>CAIXA PADRÃO</code> e criar chave de configuração <code>id_caixa_padrao</code> - OK</li>
</ul>

**Comment by LEANDROCOELHO84** [comment]
empreendimento criado 
configuraçãoes ok
