### ISSUE TITLE
Incluir campo de marcação de produto de venda obrigatório

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#730]
- [x] Criar flag (flg_venda_obrigatoria) na aba de Informações Complementares

**Comment by filipecoelho** [comment]
Tempo estimado: 1h

**Comment by LEANDROCOELHO84** [comment]
Alterações DB
ALTER TABLE `weblinia_clientes`.`tbl_produtos` 
ADD COLUMN `flg_venda_obrigatoria` INT NULL AFTER `flg_unidade_fracao`;

webliniaerp-web

-  js/angular-controller/estoque-controller.js
- js/angular-controller/pdv-controller.js
- js/angular-controller/pedido_transferencia_recebido-controller.js
- js/angular-controller/produtos-controller.js
- js/angular-controller/rel-vendas-fabricante-controller.js
- json-echo.php
- lancamentos.php
- produtos.php

webliniaerp-api

-  controller/ProdutoController.php
-  dao/ProdutoDao.php
-  model/ProdutoTO.php
