### ISSUE TITLE
Ajustes no relatório de vendas por produto

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#731]
- [x] Incluir coluna do vendedor que fez a venda do produto no relatório de vendas por produto diário (Invalido)
- [x] Implementar relatório detalhado de vendas de itens de cozinha (por período) (usar campo criado no chamado #730)
- [x] Incluir totais de venda por itens obrigatórios
- [x] Incluir indicador de controle de vendas de itens de cozinha
  - Total faturado
  - Total de custo
  - Total de vendas por item, com % referente o faturamento

**Comment by filipecoelho** [comment]
Tempo estimado: 15h

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/relatorio_vendas_produtos-controller.js
- rel_vendas_produto.php
