### ISSUE TITLE
Implementar indicador de vendas Hora a Hora, diário

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#733]
- consolidar informações no relatorio de vendas por dia

**Comment by filipecoelho** [comment]
Tempo estimado: 8h

**Comment by mtrystao** [comment]
O Objetivo desses indicadores é que posamos apresentar o 
HMM - Hora de Maior Movimento e o 
DMM - Dia de Maior Movimento

**Comment by lukasqw** [comment]
Não consigo visualizar todas venda dentro do período escolhido , as vezes aparece uma venda, mas o restante não.
