### ISSUE TITLE
Efetuar ajustes na importação de XML de fornecedor

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#734]
- [x] possibilitar cadastrar um fornecedor pela própria tela de entrada
- [x] possibilitar a vinculação de produtos não encontrados com produtos existentes (de-para)
- [x] possibilitar o cadastro de um produto manualmente (campos básicos)
- [x] possibilitar a geração de lançamentos financeiros através da tag duplicatas da NF-e ou manualmente
- [x] possibilitar a distinção de natureza de operação por item

**Comment by filipecoelho** [comment]
Tempo estimado: 20h

**Comment by mtrystao** [comment]
![Importacao XML melhoria 2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46c1998a2c9097a88ce8b0039c70dcd424432b7b2616aa2a30d7a164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff5898f453f1b041c80f75531a09a49c95be406.jpg)

**Comment by rafaelqw** [comment]
Alterações API:
- controller/EstoqueEntradaController.php
- dao/MovimentacaoCaixaDao.php
- dao/PagamentoFornecedorDao.php
- model/PagamentoFornecedorTO.php
