### ISSUE TITLE
Implementar mecanismo de controle de insumos por peso

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#735]
Ajustar o controle de estoque para que possa ser possível trabalhar com casas decimais, o que irá permitir o controle e baixa de insumos por litro ou peso

**Comment by filipecoelho** [comment]
Tempo estimado: 96h

**Comment by filipecoelho** [comment]
- [ ] Incluir opção p/ controle de estoque por Fração ou Unidade no cadastro do produto
- [ ] Alterar campo qtd_item da tabela de estoque p/ DOUBLE
- [ ] Ajustar o campo de Qtd de Estoque em todas as telas para usar casas decimais (4 casas) ou valor inteiro
- [ ] Fazer testes de inclusão de estoque com as duas opções e verificar se está gravando corretamente no banco de dados
  - se não tiver, validar se em algum lugar do sistema o valor da Qtd em estoque é arredondado para valor inteiro

**Comment by rafaelqw** [comment]
Alterações BD
- ALTER TABLE `weblinia_clientes`.`tbl_estoque` 
CHANGE COLUMN `qtd_item` `qtd_item` DOUBLE NULL DEFAULT NULL ;

**Comment by rafaelqw** [comment]
- Alterações WEB

pdv.php
grade.php
estoque.php
produtos.php
dashboard.php
inventario.php
baixa_estoque.php
controle-mesas.php
produtos-optimized.php
pedido_transferencia.php
rel_vendas_produto.php
rel_analitico_estoque.php
rel_vendas_fabricante.php
rel_vendas_produto_mes.php
rel_total_produto_estoque.php
pedido_transferencia_recebido.php
js/angular-controller/pdv-controller.js
js/angular-controller/grade-controller.js
js/angular-controller/estoque-controller.js
js/angular-controller/produtos-controller.js
js/angular-controller/dashboard-controller.js
js/angular-controller/inventario-controller.js
js/angular-controller/baixa_estoque-controller.js
js/angular-controller/produtos_optimized-controller.js
js/angular-controller/rel-vendas-fabricante-controller.js
js/angular-controller/relatorio_vendas_produtos-controller.js
js/angular-controller/relatorio_vendas_produtos-mes-controller.js
js/angular-controller/relatorio-total-produto-estoque-controller.js


- Alterações API

controller/ProdutoController.php
dao/EstoqueDao.php
dao/ProdutoDao.php
dao/RelatorioDao.php
model/ProdutoTO.php

**Comment by filipecoelho** [comment]
- [ ] @rafaelqw atualizar os 2 ambientes
- [ ] @LEANDROCOELHO84 testar o chamado

**Comment by LEANDROCOELHO84** [comment]
- [ ] @LEANDRODROCOELHO84
Alterações WEB

- [ ]pdv.php
- [ ]grade.php
- [ ]estoque.php
- [ ]produtos.php
- [ ]dashboard.php
- [ ]inventario.php
- [ ]baixa_estoque.php
- [ ]controle-mesas.php
- [ ]produtos-optimized.php
- [ ]pedido_transferencia.php
- [ ]rel_vendas_produto.php
- [ ]rel_analitico_estoque.php
- [ ]rel_vendas_fabricante.php
- [ ]rel_vendas_produto_mes.php
- [ ]rel_total_produto_estoque.php
- [ ]pedido_transferencia_recebido.php

Alterações API

- [ ] controller/ProdutoController.php
- [ ] dao/EstoqueDao.php
- [ ] dao/ProdutoDao.php
- [ ] dao/RelatorioDao.php
- [ ] model/ProdutoTO.php
