### ISSUE TITLE
Efetuar ajustes na tela de lançamentos financeiros

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#736]
- [x] Possibilidade de edição dos lançamentos
- [x] Possibilidade de incluir juros e multas, somando-se os valores
- [x] Possibilidade de incluir data de competência, data de vencimento e data de pagamento

**Comment by filipecoelho** [comment]
Tempo estimado: 48h

**Comment by rafaelqw** [comment]
Alterações BD:
- ALTER TABLE `weblinia_clientes`.`tbl_pagamentos_venda` 
ADD COLUMN `dta_venda` DATE NULL AFTER `url_boleto`,
ADD COLUMN `dta_competencia` DATE NULL AFTER `dta_venda`,
ADD COLUMN `vlr_juros` DOUBLE NULL AFTER `dta_competencia`,
ADD COLUMN `vlr_multa` DOUBLE NULL AFTER `vlr_juros`;
- ALTER TABLE `weblinia_clientes`.`tbl_pagamentos_fornecedores` 
ADD COLUMN `dta_venda` DATE NULL AFTER `flg_caixa_fechado`,
ADD COLUMN `dta_competencia` DATE NULL AFTER `dta_venda`,
ADD COLUMN `vlr_juros` DOUBLE NULL AFTER `dta_competencia`,
ADD COLUMN `vlr_multa` DOUBLE NULL AFTER `vlr_juros`;
