### ISSUE TITLE
Implementar ajustes no Controle de Mesas p/ Garagem 299

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#739]
- [x] Adaptar sistema para que seja possível trabalhar apenas com comandas (sem mesa)
- [x] Imprimir papel apenas com número da comanda para o cliente utilizar no processo de atendimento
- [x] Disponibilizar campo de filtro
  - por cliente
  - por número de comanda
- [x] Disponibilizar opção para reimpressão de comanda eletrônica, caso o cliente perca

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js

**Comment by filipecoelho** [comment]
Alterações WEB:
- js/instascan.min.js
- js/angular-controller/controle-mesas_controller.js
- controle-mesas.php

Alterações API:
- controller/MesaController.php
- dao/MesaDao.php
- index.php
