### ISSUE TITLE
Implementar alerta de pagamento pendente

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#741]
Criar e exibir chave de configuração apenas para usuarios 222, 498

**Comment by rafaelqw** [comment]
- [ ] agenda.php
- [ ] agendamento-consulta.php
- [ ] baixa_estoque.php
- [ ] base_tributaria.php
- [ ] caixas.php
- [ ] categorias.php
- [ ] clientes.php
- [ ] contas.php
- [ ] controle-atendimento.php
- [ ] controle-mesas.php
- [ ] controle_nfe.php
- [ ] controle_protese.php
- [ ] depositos.php
- [ ] desejos_clientes.php
- [ ] devolucao.php
- [ ] empreendimento_config.php
- [ ] empreendimentos.php
- [ ] especializacao_ncm.php
- [ ] estoque.php
- [ ] extrato.php
- [ ] fabricantes.php
- [ ] faixa_desconto.php
- [ ] faixa_desconto_permitido.php
- [ ] ficha-paciente.php
- [ ] fornecedores.php
- [ ] grade.php
- [ ] grupo_comissao.php
- [ ] importadores.php
- [ ] inventario.php
- [ ] lancamentos.php
- [ ] lista_pedidos_personalizados.php
- [ ] mapa.php
- [ ] maquinetas.php
- [ ] nota-fiscal-servico.php
- [ ] nota-fiscal.php
- [ ] notas-fiscais.php
- [ ] operacao.php
- [ ] ordem-servico.php
- [ ] ordem_producao.php
- [ ] pdv.php
- [ ] pedido-personalizado.php
- [ ] pedido_transferencia.php
- [ ] pedido_transferencia_recebido.php
- [ ] pedidos_fornecedores.php
- [ ] perfis.php
- [ ] plano_contas.php
- [ ] procedimentos.php
- [ ] produtos-optimized.php
- [ ] produtos.php
- [ ] regime_especial.php
- [ ] regra_servico.php
- [ ] regra_tributos.php
- [ ] rel-movimentacao-estoque.php
- [ ] rel-vendas-categoria.php
- [ ] rel_analitico_estoque.php
- [ ] rel_caixas.php
- [ ] rel_consolidado_caixa.php
- [ ] rel_contas_pagar.php
- [ ] rel_curvas_abc.php
- [ ] rel_fechamento_mensal.php
- [ ] rel_movimentacao_caixa.php
- [ ] rel_movimentacao_caixa_periodo.php
- [ ] rel_pagamentos.php
- [ ] rel_pagamentos_fornecedor.php
- [ ] rel_produtos_estoque_minimo.php
- [ ] rel_produtos_vencer.php
- [ ] rel_produtos_vencidos.php
- [ ] rel_saldo_devedor_cliente.php
- [ ] rel_sangria.php
- [ ] rel_total_produto_estoque.php
- [ ] rel_total_vendas_cliente.php
- [ ] rel_total_vendas_vendedor.php
- [ ] rel_vendas_cliente.php
- [ ] rel_vendas_deposito.php
- [ ] rel_vendas_fabricante.php
- [ ] rel_vendas_periodo.php
- [ ] rel_vendas_produto.php
- [ ] rel_vendas_produto_mes.php
- [ ] rel_vendas_vendedor.php
- [ ] rel_vendas_vendedor_dia_dia.php
- [ ] relatorio-diario-clinica.php
- [ ] separar_venda.php
- [ ] situacao_especial.php
- [ ] vendas.php
- [ ] zera-estoque.php
- [ ] zoneamento.php

**Comment by rafaelqw** [comment]
Teste realizado! Tudo ok!

**Comment by filipecoelho** [comment]
ALTERAÇÕES WEB:
- js/app.js
- dashboard.php
