### ISSUE TITLE
Criar indicador no Dashboard Comissão de Vendedor

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#742]
Precisamos de um indicador no Dashboard que traga o valor acumulado de comissão a ser pago aos vendedores e que esse valor seja debitado tb do faturamento da loja e assim um indicador a Previsão de Lucro do empreendimento

**Comment by mtrystao** [comment]
![comissao vendedor.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46eb9b972a9190a880a9a946aa59f5902654653f6b14b1247a80e03cfd18395459094fa445090a12ffffdb2baeb16a708b5d0abf83655866da2f53fde6d640e258f075c95d8fa4bd8346c1ed3c20e78b86483d1f07198ded10.jpg)

**Comment by mtrystao** [comment]
favor, inserir tb no Dashboard o valor a ser pago de comisas para cada vendedor

**Comment by filipecoelho** [comment]
Tempo estimado: 16h

**Comment by filipecoelho** [comment]
Previsão de entrega: 05/02/2018

**Comment by filipecoelho** [comment]
Alterações WEB:
- dashboard.php
- js/angular-controller/dashboard-controller.js
- js/angular-controller/relatorio-total-vendas-vendedor-controller.js
