### ISSUE TITLE
Impressao de comprovante de Pgto

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#743]
Nao esta sendo possivel imprimir comprovante de pgto na Hage Suplementos, imagem foi enviada no grupo do Telegram da Equipe

**Comment by LEANDROCOELHO84** [comment]
a informação passada é que nunca ouve impressão de comprovante de pagamento no PDV,
existe sim  a funcão no modulos> lancamentos_financeiro/ações/imprimir


![comprovante de pagamento.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46eb9b9733908cbf8ee7ab46e459f5d4394720722401ad3f7fc7af6aaf50740b0a0c0abe4b4a5a42aaf8812ff7e36a738c0e0be5d63b5f75c73c43feb0850da313f871d51bdaebe5c01982fa3737e683854e3b1f001e81f95f31a5914ac04abb.png)

![impressao pagamentos pdv.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46e1998a318790ba8ee6ff53a55af1992c48337c3a44b32f66c7af6aaf50740b0a0c0abe4b4a5a42aaf8812ff7e36a738c0e0be5d63b5f75c73c43feb0850da313f871d51bdaebe5c01982fa3737e683854e3b1f001e81f85e3ca8904ecb4abb.jpg)

**Comment by LEANDROCOELHO84** [comment]
Alterações WEB

- pdv.php
- js/angular-controller/pdv-controller.js
