### ISSUE TITLE
Implementar pergunta para inclusão de CPF no PDV

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#746]
- [x] Quando o caixa estiver configurado para emitir Cupom Fiscal eletrônico (SAT), perguntar se o cliente deseja incluir o CPF na nota
- [x] Implementar mecanismo de habilitação do emissor de CF-e SAT no PDV

**Comment by filipecoelho** [comment]
Será necessário atualização em massa de todos os clientes que utilizam o programa webliniaerp-fiscal-client.jar

**Comment by rafaelqw** [comment]
Alterações API:
- controller/VendaController.php
- dao/PessoaFisicaDao.php
- model/VendaTO.php
