### ISSUE TITLE
Problema com saldo devedor

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#747]
O cliente não aguarda a conclusão do fechamento da venda, com isso algumas vendas não são registrados os pagamentos e o cliente acaba ficando com saldo devedor.

**Comment by LEANDROCOELHO84** [comment]
teste realizado
erro ocorre quando o cliente fecha ou atualiza a pagina no momento do aguarde  deixando o cliente com saldo devedor.

**Comment by filipecoelho** [comment]
O problema está ocorrendo porque não está configurado pra dar baixa automática em cartão de crédito e o cliente está ficando com saldo devedor, mesmo com lançamento financeiro pendente.
Ou seja, questão de configuração.
