### ISSUE TITLE
Perfil Caixa esta podendo deletar produto na HAGE

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#752]
O Perfil de Caixa esta podendo deletar produtos e nao estao conseguindo editar produtos o chamado foi atendido errado, o correto seria ocultar o botão para deletar e deixar liberar o botão para editar (sem alterar preço e estoque)

**Comment by rafaelqw** [comment]
Alterações WEB:
- produtos.php
