### ISSUE TITLE
Configurar Regra Padrao empreendimentos HAGE

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#753]
Emp	Regra	Status
Hage 00	                 1	2	
Hage 01	               20	6	
Hage 02	               28	3	
Hage 03	               30	1	
Hage 04	               22	5	
Hage 05	               32	4	
Hage 06	               26	8	
Hage 07	               31	9	
Hage 08	               25	10

**Comment by rafaelqw** [comment]
Procedimento Realizado!
