### ISSUE TITLE
Criar chaves de configurações

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#755]
Incluir na tela de configurações, os seguintes campos:
- [x] Vendedor Padrão (id_vendedor_padrao)
- [x] Maquineta Padrão (id_maquineta_padrao)
- [x] Caixa Padrão (id_caixa_padrao)

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
