### ISSUE TITLE
Incluir campo troco no CF-e SAT

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#756]

**Comment by filipecoelho** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js

Alterações API:
- controller/NfeController.php
- controller/VendaController.php
- dao/VendaDao.php
- model/VendaTO.php

Alterações BD:
```ALTER TABLE tbl_vendas 
ADD COLUMN vlr_total_venda DOUBLE NULL AFTER venda_bonificada,
ADD COLUMN vlr_troco DOUBLE NULL AFTER vlr_total_venda;```

**Comment by LEANDROCOELHO84** [comment]
teste sera realizado em produção
