### ISSUE TITLE
Resolver problema de lentidão no carregamento da tela de Lançamentos Financeiros

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#757]

**Comment by filipecoelho** [comment]
Alterações WEB:
- js/angular-controller/lancamentos-controller.js
- js/app.js

**Comment by rafaelqw** [comment]
- Alterações BD:
ALTER TABLE `weblinia_clientes`.`tbl_pagamentos_venda` 
ADD COLUMN `dta_venda` DATE NULL AFTER `url_boleto`,
ADD COLUMN `dta_competencia` DATE NULL AFTER `dta_venda`,
ADD COLUMN `vlr_juros` DOUBLE NULL AFTER `dta_competencia`,
ADD COLUMN `vlr_multa` DOUBLE NULL AFTER `vlr_juros`;
