### ISSUE TITLE
Cadastro Rapido inserir Combo Box Indicacao

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#758]
Inserir no cadastro rapido um combo box onde seja possivel selecionar opcoes pre determinadas de como o cliente chegou ate a Hage Suplementos (temos isso fixo na tela de cadastro deve-se unificar essa condição, precisa ser feito o ajuste)

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/clientes-controller.js
- js/angular-controller/pdv-controller.js
- pdv.php
