### ISSUE TITLE
Falha modulo Transferencia de Produtos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#761]
Esta acontecendo uma falha no modulo de transferencia de produtos aparentemente qdo o pedido é muito grande ex pedido 6708 da Hage 01, a loja faz o pedido, o deposito responde e qdo clica em salvar nao indica de qual deposito esta saindo os produtos (apenas para alguns produtos)
Os produtos nao sao movimentados do estoque como pode ser confirmado através do relatorio de movimentação de estoque
Anexo segue foto evidenciando essa situação

**Comment by mtrystao** [comment]
![falha transf de produtos.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46ee95962b83c3bd9de8b150a21df4916956357c2d11b72463c7af6aaf50740b0a0c0abe4b4a5a42aaf8812ff7e36a738c0e0be5d63b5f75c73c43feb0850da313f871d51bdaebe5c01982fa3737e68c854e3b1f011b88f65537a79c4dca4abb.jpg)

**Comment by LEANDROCOELHO84** [comment]
Alterações WEB

- js/angular-controller/pedido_transferencia-controller.js
- js/angular-controller/pedido_transferencia_recebido-controller.js

Alterações API

- controller/TransferenciaEstoqueController.php
- util/rel_templates/comprovante_venda.php
