### ISSUE TITLE
Envio de Mercadoria zerando a qtde após salva

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#763]
Qdo vc realiza o envio de produtos para uma Loja e apenas Salva para poder continuar mais tarde, ao clicar no botão Editar para continuar o envio o sistema esta zerando a qtde de todos os produtos ja inseridos anteriormente

**Comment by LEANDROCOELHO84** [comment]
verificado em ambiente de teste e esta retornando corretamento a informação salva

**Comment by LEANDROCOELHO84** [comment]
- Alterações WEB:
  - js/angular-controller/pedido_transferencia_recebido-controller.js
