### ISSUE TITLE
Ajustes no Controle de Mesas p/ atender Akemi Açai

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#767]
Com o fechamento da contratação do sistema com um novo cliente (Akemi Açai & Hamburgueria), o chamado foi reaberto e deve considerar os seguintes pontos:

- [x] Incluir opção p/ selecionar cor de uma categoria (cadastro de produtos)
- [x] Incluir opção p/ adicionar produtos no carrinho através de grade (chave de configuração) de itens (1º categorias, 2º produtos da categoria)
- [x] Incluir opção p/ adicionais de um produto (cadastro de produto)
- [x] Implementar opção de incluir adicionais de um produto e estes adicionais serem impressos na ordem de produção da cozinha

Para o item 1 e 2, usar: https://github.com/buberdds/angular-bootstrap-colorpicker

**Comment by filipecoelho** [comment]
- Alterações de BD:
```
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS tbl_adicionais_item_ordem_producao (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_item_ordem_producao INT(11) NULL DEFAULT NULL,
  id_produto_adicional INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

ALTER TABLE tbl_categorias 
ADD COLUMN hex_cor_box VARCHAR(100) NULL DEFAULT NULL AFTER id_ref,
ADD COLUMN hex_cor_letra VARCHAR(100) NULL DEFAULT NULL AFTER hex_cor_box;

CREATE TABLE IF NOT EXISTS tbl_produto_adicional (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_produto INT(11) NULL DEFAULT NULL,
  id_adicional INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_produto (id_produto ASC, id_adicional ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
```

**Comment by filipecoelho** [comment]
Alterações WEB:
  - ```bower_components/angular-bootstrap-colorpicker/.bower.json```
  - ```bower_components/angular-bootstrap-colorpicker/.gitignore```
  - ```bower_components/angular-bootstrap-colorpicker/.jshintrc```
  - ```bower_components/angular-bootstrap-colorpicker/.travis.yml```
  - ```bower_components/angular-bootstrap-colorpicker/CHANGELOG.md```
  - ```bower_components/angular-bootstrap-colorpicker/MIT-LICENSE.txt```
  - ```bower_components/angular-bootstrap-colorpicker/README.md```
  - ```bower_components/angular-bootstrap-colorpicker/bower.json```
  - ```bower_components/angular-bootstrap-colorpicker/css/colorpicker.css```
  - ```bower_components/angular-bootstrap-colorpicker/css/colorpicker.min.css```
  - ```bower_components/angular-bootstrap-colorpicker/gulpfile.js```
  - ```bower_components/angular-bootstrap-colorpicker/img/alpha.png```
  - ```bower_components/angular-bootstrap-colorpicker/img/hue.png```
  - ```bower_components/angular-bootstrap-colorpicker/img/saturation.png```
  - ```bower_components/angular-bootstrap-colorpicker/js/bootstrap-colorpicker-module.js```
  - ```bower_components/angular-bootstrap-colorpicker/js/bootstrap-colorpicker-module.min.js```
  - ```bower_components/angular-bootstrap-colorpicker/less/colorpicker.less```
  - ```bower_components/angular-bootstrap-colorpicker/package.json```
  - ```categorias.php```
  - ```controle-mesas.php```
  - ```empreendimento_config.php```
  - ```js/angular-controller/categorias-controller.js```
  - ```js/angular-controller/controle-mesas_controller.js```
  - ```js/angular-controller/empreendimento_config-controller.js```
  - ```js/angular-controller/pdv-controller.js```
  - ```js/angular-controller/produtos-controller.js```
  - ```produtos.php```

**Comment by filipecoelho** [comment]
Alterações API:
  - ```controller/CategoriaController.php```
  - ```controller/MesaController.php```
  - ```controller/OrdemProducaoController.php```
  - ```controller/ProdutoController.php```
  - ```dao/AdicionalItemOrdemProducaoDao.php```
  - ```dao/CategoriaDao.php```
  - ```dao/ItemVendaDao.php```
  - ```dao/ItensOrdemProducaoDao.php```
  - ```dao/OrdemProducaoDao.php```
  - ```dao/ProdutoDao.php```
  - ```index.php```
  - ```model/AdicionalItemOrdemProducaoTO.php```
  - ```model/CategoriaTO.php```

**Comment by filipecoelho** [comment]
- [ ] @rafaelqw atualizar os 2 ambientes
- [ ] @LEANDROCOELHO84 testar o chamado

**Comment by LEANDROCOELHO84** [comment]
- [x] @LEANDROCOELHO84 testar o chamado
![CONTROLE DE MESAS.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589dcdf7735718200097c45b/125516c66e82c728ace21e0d46cbbbb417b0ac85aaa99b66e470d5a70875653f6b14b1247a80e03cfd18395459094fa445090a12ffffdb2baeb16a708b5d0abf83655866da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3c20e388874c3618051e8fed10.png)
