### ISSUE TITLE
Remover console.log das paginas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#769]
Varrer todas as paginas e remover todos os console.log dos controllers do JS

**Comment by LEANDROCOELHO84** [comment]
Alterações WEB:
- js/angular-controller/pedido_transferencia_recebido-controller.js
- js/angular-controller/agendamento_consulta2-controller.js
- js/angular-controller/agendamentofornecedor-controller.js
- js/angular-controller/agendamento_consulta-controller.js
- js/angular-controller/baixa_estoque-controller.js
- js/angular-controller/bko-pdv-controller.js
- js/angular-controller/carrinho-controller.js
- js/angular-controller/caixas-controller.js
- js/angular-controller/cliente-controller.js
- js/angular-controller/contas-correntes_controller.js
- js/angular-controller/controle-mesas_controller.js
- js/angular-controller/controle_atendimento-controller.js
- js/angular-controller/deshboard-controller.js
- js/angular-controller/depositos-controller.js
- js/angular-controller/devolucao-controller.js
- js/angular-controller/emprendimento-controller.js
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/extrato-controller.js
- js/angular-controller/faixa-desconto-controller.js
- js/angular-controller/faixa_desconto_permitido-controller.js
- js/angular-controller/fornecedores-controller.js
- js/angular-controller/grade-controller.js
- js/angular-controller/inventario-controller.js
- js/angular-controller/nota_fiscal_servico-controller.js
- js/angular-controller/operacao-controller.js
- js/angular-controller/pdv-controller.js
- js/angular-controller/pdv_estoque-controller.js
- js/angular-controller/pdv_simple-controller.js
- js/angular-controller/pedido-personalizado-controller.js
- js/angular-controller/pedido_venda-controller.js
- js/angular-controller/pedidos_fornecedores-controller.js
- js/angular-controller/perfis-controller.js
- js/angular-controller/produtos_optimized-controller.js
- js/angular-controller/rel-movimentacao-estoque-controller.js
- js/angular-controller/rel-vendas-fabricante-controller.js
- js/angular-controller/rel_caixas-controller.js
- js/angular-controller/rel_movimentacao_caixa-controller.js
- js/angular-controller/rel_pagamentos-controller.js
- js/angular-controller/relatorio-analitico-estoque-controller.js
- js/angular-controller/relatorio-sangria.js
- js/angular-controller/relatorio-vendas-cliente-controller.js
- js/angular-controller/relatorio_vendas_periodo-controller.js
- js/angular-controller/relatorio_vendas_produtos-controller.js
- js/angular-controller/separar_venda-controller.js
- js/angular-controller/setup_caixa-controller.js
- js/angular-controller/teste.js

**Comment by LEANDROCOELHO84** [comment]
DONE
