### ISSUE TITLE
Criar layout de relatório p/ OS em PDF

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#770]

**Comment by mtrystao** [comment]
Nao identifiquei o local onde achar a OS em PDF

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by filipecoelho** [comment]
Na dependência de finalização do chamado #623

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!

**Comment by mtrystao** [comment]
em acoes>> visualizar comprovante da OS esta apresentando 500 Internal Server Error

**Comment by rafaelqw** [comment]
Alterações API:
- util/rel_templates/comprovante_ordem_servico.php

**Comment by mtrystao** [comment]
nao esta apresentando o comprovante da OS

**Comment by Kenzo13** [comment]
testado e ok
