### ISSUE TITLE
Falha cupom referente ao desconto

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#771]
empreendimento: hage 04
venda: 75834
situacao: foram vendidas 03 barrinhas a R$ 6,00 cada totalizando R$ 18,00, porem, foi dado desconto de R$ 1,00 por barra totalizando R$ 15,00 no cupom consta desconto de R$ 2,00 e nao de R$ 3,00 que foi o valor do desconto correto

**Comment by rafaelqw** [comment]
Alterações API:
- util/rel_templates/comprovante_venda.php
