### ISSUE TITLE
Incluir função de cancelamento de CF-e-SAT

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#773]

**Comment by filipecoelho** [comment]
- [ ] ciar funcionalidade no PDV
- [ ] enviar solicitação p/ Client Fiscal
- [ ] receber a solicitação no Client Fiscal e tratar os dados
- [ ] enviar requisição p/ API One do Bematech Fiscal Manager
- [ ] guardar retorno de sucesso no BD

**Comment by rafaelqw** [comment]
Alterações WEB:
- pdv.php
- js/angular-controller/pdv-controller.js

Alterações API: 
- controller/LancamentosFinanceirosController.php
- controller/NotaFiscalController.php
- dao/NotaFiscalDao.php
- dao/VendaDao.php
- index.php

**Comment by filipecoelho** [comment]
Pra testar basta atualizar a versão do weblinierp-fiscal-client.jar e testar o processo de cancelamento
