### ISSUE TITLE
Ajustes no controle de mesas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#780]
- [x] incluir controle de cartões físicos
- [x] ao abrir uma comanda, vincular o cartão à comanda
- [x] no Controle de Mesas, possibilitar a pesquisa pelo número do cartão magnético p/ incluir itens na comanda

**Comment by rafaelqw** [comment]
Alterações BD:

´´´
CREATE TABLE tbl_comanda (
  id INT NOT NULL AUTO_INCREMENT,
  num_comanda VARCHAR(45) NULL,
  id_empreendimento INT NULL,
  PRIMARY KEY (id));
´´´
