### ISSUE TITLE
Relatorio Contas a Receber

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#784]
Favor, inserir no relatorio de contas a receber o total de cada tipo de recebimento e seu percentual referente ao Total de Recebimento

Dinheiro:          R$    800,00  -  80%
Debito:             R$    100,00  -  10%
Credito:            R$    100,00  -  10%
Total Recebido R$ 1.000,00  -  100%

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/rel_pagamentos-controller.js
- rel_pagamentos.php

**Comment by mtrystao** [comment]
Relatorio apresentando os percentuais perfeitamente
