### ISSUE TITLE
Relatorio Vendas por Produto

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#789]
Favor, ordenar o relatorio vendas por produto por:

1- Fabricante
2- Ordem Alfabetica
3- Inserir linha com os totais Produto, Custo, Total vendido e Total Lucro

**Comment by filipecoelho** [comment]
@Kenzo13 validar se isso já esta implementado

**Comment by lukasqw** [comment]
A lista não está em ordem alfabética e também não ordena por fabricante .

**Comment by Kenzo13** [comment]
Alterações API
- ProdutoDao.php

**Comment by LEANDROCOELHO84** [comment]
relatório esta funcionando conforme solicitado.

Obs. antes de subir ajustar mascara do filtro de datas

**Comment by Kenzo13** [comment]
testado e ok

**Comment by mtrystao** [comment]
a lista de produtos esta em ordem alfabetica mas nao esta ordenada por fabricante e nao consta o total de lucro do periodo

**Comment by Kenzo13** [comment]
Campo de faturamento no final do relatório está em branco.

**Comment by mtrystao** [comment]
a lista de produtos esta em ordem alfabetica mas nao esta ordenada por fabricante e nao consta o total de lucro do periodo, os campos de data de inicio e fim estao em padrao americano

**Comment by mtrystao** [comment]
chamado atendido conforme orientacao da Espeto Carioca

**Comment by mtrystao** [comment]
testado e ok
