### ISSUE TITLE
Ajustes no módulo financeiro

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#790]
- [x] Exibir totais consolidados anterior e do período selecionado
- [x] Permitir movimentar valor entre contas bancarias

**Comment by filipecoelho** [comment]
Ponto 1: @jheizerwandel 
Ponto 2: @filipecoelho
Ponto 3: @rafaelqw

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/lancamentos-controller.js
- lancamentos.php

Alterações API:
- controller/LancamentosFinanceirosController.php
- controller/PagamentoClienteController.php
- controller/PagamentoFornecedorController.php
- dao/LancamentosFinanceirosDao.php
- dao/PagamentoFornecedorDao.php
- index.php

**Comment by filipecoelho** [comment]
Os dois itens estão funcionando, porém ao fazer um filtro por conta bancária, o saldo anterior não está aplicando esse campo de filtro

**Comment by filipecoelho** [comment]
@filipecoelho Rafael olha isso amanhã, ok?
