### ISSUE TITLE
Corrigir pesquisa CPF/CNPJ PDV e Devolucao de produtos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#794]
- [x] No PDV os Campos para Busca por Cliente através do CPF/CNPJ, nao estao funcionando, pois, a coluna nome aparece em branco
- [x] Em Devolucao do Produtos o campo pesquisa Cliente nao esta realizando a busca através do numero do CPF ou CNPJ

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/devolucao-controller.js
