### ISSUE TITLE
Relatorio Produtos em Estoque

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#795]
- [x] Incluir um ponto para seleção onde o usuario possa incluir no relatorio os produtos zerados no deposito selecionado

- [ ] No relatorio Produtos em Estoque precisamos inserir o cabeçalho das colunas qdo exportamos o relatorio

- [ ] Poder selecionar todos os depósitos e assim o relatorio apareceria com as insformacoes dos produtos e nas demais colunas traria qto cada deposito possui de cada produto
ID	Cód. Barras	Produto	Fabricante	Categoria	Tamanho	Sabor/Cor	R$ Custo	R$ Varejo	R$ Subtotal Estoque 1   Estoque 2   Estoque 3   Estoque 4 (comparativo de produtos em todos os Depósitos existentes) e assim por diante

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/relatorio-total-produto-estoque-controller.js
- rel_total_produto_estoque.php

Alterações API:
- controller/RelatorioController.php
- dao/RelatorioDao.php
- index.php

**Comment by lukasqw** [comment]
Quando ativado a opção de "Mostrar sem estoque" não aparece nenhum produto sem estoque  no relatório

**Comment by rafaelqw** [comment]
Os pontos tratados estão funcionando perfeitamente, porém foi identificado um outro erro que não foi identificado no primeiro teste, os valores de totais não estavam sendo atualizados após os filtros
