### ISSUE TITLE
Extrato e Lançamento Financeiro

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#796]
ao alterar o Status de um Lançamento Financeiro para pago esta deletando ou ocultando o lançamento correspondente no Extrato do cliente com isso o cliente esta ficando com Saldo Devedor
Ex. Cliente Gilmara empreendimento Hage 00

**Comment by rafaelqw** [comment]
Alterações API:
- controller/LancamentosFinanceirosController.php
