### ISSUE TITLE
Relatório de Fechamento Mensal

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#798]
o Relatorio de Fechamento Mensal nao esta funcionando, precisamos ver o que esta acontecendo e também validar todo o processo de funcionamento desse relatorio, desde a entrada dos produtos via NF-e até a venda e assim garantir a confiabilidade das informacoes

**Comment by filipecoelho** [comment]
Como não houve interação entre @mtrystao p/ repassar o que de fato acontece, o chamado está sendo reprogramado!

**Comment by lukasqw** [comment]
O relatório não traz os produtos que foram dado entrada no estoque no período escolhido, traz todos os valores zerado, apenas as vendas desses produtos estão vindo corretamente, por estar faltando esses valores o relatório não funciona corretamente.

**Comment by filipecoelho** [comment]
@lukasqw Os valores de compra são computados quando se faz entrada no estoque pela tela de entrada de nota fiscal

**Comment by lukasqw** [comment]
Alterações API:

- Dao/RelatorioDao.php

**Comment by lukasqw** [comment]
No fechamento mensal não esta aparecendo o valor de custo dos produtos que foram dados entrada no estoque

**Comment by mtrystao** [comment]
@lukasqw nao esta aparecendo tb a qtde que foi dado entrada tb no mes

**Comment by rafaelqw** [comment]
Alterações API:
- controller/EstoqueEntradaController.php
