### ISSUE TITLE
Habilitar o botao Exportar Clientes na Hage

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#802]
Favor, habilitar o botão exportar clientes na tela Clientes/Usuarios no ambiente da Hage os empreendimentos nao possuem esse botão

**Comment by mtrystao** [comment]
![exportar clientes.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46ed8c8a2c9097a89da9bc4fad58fe802c55653f6b14b1247a80e03cfd18395459094fa445090a12ffffdb2baeb16a708b5d0abf83655866da2f53fde6d640e258f075c95d8fa4bd8246c1ed3c22ee888d473a180d198ded10.jpg)

**Comment by filipecoelho** [comment]
@Kenzo13 validar se isso já está funcionando

**Comment by mtrystao** [comment]
Botao exportar clientes esta apresentando falha conforme imagem

**Comment by mtrystao** [comment]
[exportar clientes 2.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46ed8c8a2c9097a89da9bc4fad58fe802c5567216b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e58286483d16041a8cfd5a27ed.pdf)
