### ISSUE TITLE
Exibir CPF/CNPJ quando o cliente não tiver nome

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#804]

**Comment by rafaelqw** [comment]
Alterações WEB:
- lancamentos.php
- nota-fiscal.php
- pdv.php
- pedido_transferencia.php
- pedido_transferencia_recebido.php
- rel_saldo_devedor_cliente.php
- rel_total_vendas_cliente.php
- vendas.php

Alterações API:
- dao/LancamentosFinanceirosDao.php
- dao/RelatorioDao.php
- dao/UsuarioDao.php

**Comment by Kenzo13** [comment]
Faltou a correção na tabela de extrato do modulo clientes/usuários

**Comment by rafaelqw** [comment]
Alterações WEB:
- extrato.php
