### ISSUE TITLE
relatorio de fechamento de caixa

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#807]
o relatorio de fechamento de caixa nao esta apresentando a informaçao do valor referente a pagamento avulso em dinheiro conforme imagem em anexo da Hage 05

**Comment by mtrystao** [comment]
![pagamento.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46f8959d228f86a79be6fd0fe64de29b234324676b5ee17e2683b270eb437e075c591cac495f0944fdf88879f4be3b62964e49bc8f3900299f7744eeaa880dbe06b0218e4e8dbeb58a4bc3ea3a25e199c2.jpg)

**Comment by rafaelqw** [comment]
Chamado Inválido!
