### ISSUE TITLE
Mundo do Corpo - Lançamentos Financeiros

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#808]
Lancamentos financeiros
 • Nao esta limpando o campo Fornecedor
 • Nao esta limpando os campos para os lancamentos realizados em Boleto
 • Corrigir a Query que esta apresentando os valores totais de Receita e Despesa (Saldo Anterior)

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/lancamentos-controller.js
