### ISSUE TITLE
Mundo do Corpo - PDV

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#809]
PDV
 • Impressao de Pagamento Avulso referente chamado 775

**Comment by Kenzo13** [comment]
Segundo instruções de Filipe Coelho, este chamado vai ser enviado para a próxima semana.

**Comment by Kenzo13** [comment]
Este chamado se refere a uma melhoria no layout do client de pagamento avulso.

**Comment by filipecoelho** [comment]
Alterações WEB:
- pdv.php
- js/angular-controller/pdv-controller.js

Alterações CLIENT:
- webliniaerp-fiscal-client.jar
