### ISSUE TITLE
Mundo do Corpo - Relatorio de Vendas por Vendedor Diario

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#810]
Relatorio Vendas por Vendedor Diario
 • Alterar o campo atual de total para Sub Total Pagina
 • Inserir um campo abaixo chamado Total Geral
 • Exportar todas as paginas do Relatorio utilizando o Plugin utilizado na tela de Clientes

**Comment by rafaelqw** [comment]
Alterações WEB: 
- rel_vendas_vendedor_dia_dia.php
- js/angular-controller/rel-diario-vendedor-controller.js

Alterações API:
- controller/RelatorioController.php
- modified:   dao/RelatorioDao.php
