### ISSUE TITLE
Mundo do Corpo - Relatorio de Contas a Pagar

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#811]
Relatorio Contas a Pagar
 • Inserir o total a Pagar no Periodo
 • Ordenar por Ordem de Data da Data Mais Recente para a Mais Antiga
Descarta os Valores Referentes a Movimentacao de Caixa, pois, nao sao Pagamentos realizados

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/relatorio-contas-pagar.js

Alterações API:
- dao/PagamentoFornecedorDao.php
