### ISSUE TITLE
Movimentacao de Caixa misturando datas

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#813]
no ambiente da Hage esta misturando as movimentações de caixaEx: dias 20 e 21 com o usuario PC

**Comment by mtrystao** [comment]
![mov caixa errado.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e59b8c638182a097e8ff46b64ff19026046b313916ac217586f76ae5002e57095e46a8100d0947faab8923a1e03c718b5d59bfd96a4d68d47f40f2ecdd42e64bef62994597b7b5804dc5e93427e28f8a4a3a1c061e9bb2.jpg)

**Comment by Kenzo13** [comment]
Não foi possível evidenciar o problema
