### ISSUE TITLE
Corrigir problema ao emitir CF-e-SAT

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#819]
Ocorre que quando é cadastrado um cliente sem CPF, ou 000.000.000-00 ou CPF inválido, o emissor envia esta informação para o CF-e e ao tentar emitir pelo Bematech API One, é retornado falha de CPF.

Pra tratar é necessário validar se há a informação correta do CPF, caso contrário, não enviá-lo para o Bematech API One.

**Comment by rafaelqw** [comment]
Alterações WEB:
- pdv.php
- js/angular-controller/pdv-controller.js
Alterações API:
- dao/VendaDao.php
