### ISSUE TITLE
Incluir 4ª tabela de preços

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#820]
- Incluir tabela Intermediário 2 no sistema de preços

**Comment by filipecoelho** [comment]
- Alterações WEB:
  - js/angular-controller/empreendimento_config-controller.js
  - js/angular-controller/pdv-controller.js
  - js/angular-controller/produtos-controller.js
  - produtos.php
- Alterações API:
  - controller/ProdutoController.php
  - dao/EstoqueDao.php
  - dao/PrecoProdutoDao.php
  - dao/ProdutoDao.php
  - model/PrecoProdutoTO.php
  - model/ProdutoTO.php

**Comment by mtrystao** [comment]
Verificar as seguintes situações
1- configuracao do perfil nao esta aparecendo a intermediario 2 para eu poder associar a um perfil
2- Em modulos> tella de produtos> nao esta aparecendo a coluna com a 4a tabela intermediario 02, apenas quando edito o produto

**Comment by filipecoelho** [comment]
Problemas corrigidos!

**Comment by mtrystao** [comment]
p perfil 4a tabela esta associado ao usuario marcio tristao, quando estou no PDV e insiro o produto produto 4a tabela que deveria estar com o valor de 16,00 aparece o valor de 20,00 que seria o valor do varejo, isso é, nao esta respeitando o valor da 4a tabela

**Comment by filipecoelho** [comment]
Problemas corrigidos!
