### ISSUE TITLE
Relatorio Produtos a Vencer

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#822]
Incluir mais um periodo para consulta de prazo para produtos a vencer
atualmente temos
30,90 e 120, cliente deseja poder consultar prazo de 180 dias

**Comment by rafaelqw** [comment]
Alterações WEB:
- rel_produtos_vencer.php

**Comment by mtrystao** [comment]
Relatorio indicando os produtos com vencimento até 180 dias
