### ISSUE TITLE
Ajustes p/ integração c/ sistemas/sites externos

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#826]
- [x] Incluir campo de fotos p/ categorias
- [x] Incluir campo de + de 1 foto p/ produtos

**Comment by rafaelqw** [comment]
Alterações BD:
```
CREATE TABLE `weblinia_clientes`.`tbl_produtos_fotos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NULL,
  `pth_imagem` VARCHAR(255) NULL,
  `num_ordem` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));
```

Alterações WEB:
- produtos.php
- categorias.php
- js/angular-controller/categorias-controller.js
- js/angular-controller/produtos-controller.js
- css/custom.css

Alterações API
- index.php
- dao/CategoriaDao.php
- dao/FotosProdutoDao.php
- model/CategoriaTO.php
- model/FotosProdutoTO.php
- controller/ProdutoController.php
- controller/CategoriaController.php
