### ISSUE TITLE
Problemas com transferência de produtos

### ISSUE THREAD

**Issue by rafaelqw** [WebliniaERP/webliniaerp-web#827]
- Clicando em  "salvar" antes e depois "salvar e enviar" ele salva como se fosse que estivesse clicado apenas em "salvar"

**Comment by filipecoelho** [comment]
@rafaelqw como ficou esse chamado?

**Comment by rafaelqw** [comment]
Chamado corrigido!

**Comment by rafaelqw** [comment]
@filipecoelho Chamado corrigido!

**Comment by mtrystao** [comment]
Processo Enviar Produto, 
1- escolho os produtos e clico em Salvar ao voltar para Editar o Envio nao aparece o botão da lixeira caso eu queira excluir o produto inserido incialmente
2- Ao clicar em Salvar e Enviar o processo é concluído e direcionado para o empreendimento corretamente

**Comment by filipecoelho** [comment]
Tempo: 30m

**Comment by jheizerwandel** [comment]
1- escolho os produtos e clico em Salvar ao voltar para Editar o Envio não aparece o botão da lixeira caso eu queira excluir o produto inserido inicialmente.

sobre esse problema : depois que a transferência inicia uma movimentação não pode (quando digo que não pode é em relação ao que foi discutido e feito no sistema) ,  para tratar esse item vai ser necessário construir  uma  funcionalidade de cancelamento , onde os produtos vão ser retornados para o estoque e etc
