### ISSUE TITLE
exclusão de usuario nao funciona

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#829]
nao esta sendo possivel deletar usuario mesmo o usuario desejado nao possuindo nenhuma venda associada o que deveria funcionar, pois, caso eu delete o usuario nenhuma informação sera perdida

**Comment by rafaelqw** [comment]
Alterações BD:
- ```ALTER TABLE tbl_usuarios ADD COLUMN flg_excluido INT '0';```

Alterações WEB:
- js/angular-controller/clientes-controller.js
- js/angular-controller/pdv-controller.js
- js/angular-controller/lancamentos-controller.js

Alterações API:
- dao/ClienteDao.php

**Comment by lukasqw** [comment]
Esta funciona corretamente.
