### ISSUE TITLE
Criar mecanismo de lançamento de posição de estoque e registo de desperdício

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#831]

**Comment by rafaelqw** [comment]
Alterações BD:
- ```CREATE TABLE tbl_posicao_estoque ( id INT NOT NULL AUTO_INCREMENT, dta_posicao_estoque TIMESAMP CURRENT_TIMESAMP, dta_inicial DATETIME NULL, dta_final DATETIME NULL, id_usuario_responsavel INT NULL, id_deposito INT NULL, id_empreendimento INT NULL, PRIMARY KEY (id));```
- ```CREATE TABLE tbl_posicao_estoque_item ( id INT NOT NULL AUTO_INCREMENT, id_posicao_estoque INT NULL, id_produto INT NULL, qtd_estoque_inicial DOUBLE NULL, qtd_compras_periodo DOUBLE NULL, qtd_vendas_periodo DOUBLE NULL, qtd_desperdicios_periodo DOUBLE NULL, qtd_sobra_periodo DOUBLE NULL,`PRIMARY KEY (id));```
- ```INSERT INTO tbl_modulo (id_modulo, nme_modulo, tlt_modulo, url_modulo, icn_modulo, id_modulo_pai, psc_menu_modulo, vsv_menu_modulo) VALUES (NULL, 'Posição de Estoque', 'Posição de Estoque', 'posicao_estoque.php', 'fa-table', '55', '0', NULL);```

Alterações WEB:
- js/angular-controller/posicao_estoque-controller.js
- posicao_estoque.php
- estoque.php

Alterações API:
- index.php
- controller/PosicaoEstoqueController.php
- dao/MovimentacaoEstoqueDao.php
- dao/ItemPosicaoEstoqueDao.php
- dao/PosicaoEstoqueDao.php
- model/ItemPosicaoEstoqueTO.php
- model/PosicaoEstoqueTO.php

**Comment by mtrystao** [comment]
Lançamento de posição de estoque ok!
preciso saber como lançar desperdício para refazer teste no chamado

**Comment by mtrystao** [comment]
Filipe Weblinia, [15 de abr de 2018 21:50:17]:
Desperdício tá saindo negativo ?

Marcio Tristao, [15 de abr de 2018 21:50:19]:
so nao ficou claro pra mimi como funciona esse calculo, pois, foi dado baixa manual e o numero do Saldo fica maior que o Estoque inicial e a diferenca é negativo na mesma quantidade

sim esta negativo

Filipe Weblinia, [15 de abr de 2018 21:50:36]:
Tinha que ficar positivo

Tá com problema no Back

Rafael amanhã cedo prioridade corrigir isso

Marcio Tristao, [15 de abr de 2018 21:52:30]:
vou registrar no chamado
