### ISSUE TITLE
Criar mecanismo de bloqueio de qtd de solicitação/envio de produtos via transferencia

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#832]
- [x] Incluir campo de qtd múltipla p/ solicitação de produtos via transferencia de estoque na tela de cadastro de produtos
- [x] validar campo de qtd solicitada/enviada no processo de transferencia baseado no múltiplo informado no cadastro do produto
  - Exemplo.:
    - Calzone de Calabreza, uma receita rende 50 calzones, sendo que cada lote é armazenado em um pacote de 50 unidades.
    -  A idéia é que o usuario só peça múltiplos de 50, ou seja, se precisar de 186 unidades, ele só poderá pedir 200 unidades na transferencia, pois serão enviados 4 pacotes de 50 unidades.

**Comment by rafaelqw** [comment]
Alterações BD:

```ALTER TABLE tbl_produtos 
ADD COLUMN qtd_multiplo_transferencia INT NULL;```

Alterações WEB:
- js/angular-controller/pedido_transferencia-controller.js
- js/angular-controller/pedido_transferencia_recebido-controller.js
- js/angular-controller/produtos-controller.js
- pedido_transferencia.php
- pedido_transferencia_recebido.php
- produtos.php

Alteraçoes API: 
- controller/ProdutoController.php
- dao/ProdutoDao.php
- model/ProdutoTO.php

**Comment by mtrystao** [comment]
teste feito com o produto ETIQUETA REFLETIVA DUT LOGO ""A"" 20", existem 100 unidades, multiplos de 25, ate esse ponto na tela do produto tudo certo

fiz o pedido de 10 considerando múltiplos de 25 o estoque deveria ter 250 unidades, qtde superior ao estoque existente que sao 100 unidades ou 4unidades múltiplos de 25

no momento de responder a solicitação deve aparecer na tela alguma indicação fazendo a relacao solicitada a quantidade existente para que fique claro para o usuario qual a quantidade solicitada e a disponível, essa informação nao esta evidente da forma como esta hoje que é somente ao clicar em Salvar que aparece que o envio é múltiplos de 25

so consegu responder ao pedido qdo inseri 100 unidades o que seria 25*4, esse mecanismo nao ficou funcional ou entendível para mim

**Comment by filipecoelho** [comment]
@rafaelqw não esta funcionando a validação!
