### ISSUE TITLE
Criar mecanismo de planejamento de faturamento e despesas p/ plano de contas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#833]

**Comment by jheizerwandel** [comment]
CREATE TABLE IF NOT EXISTS `tbl_planejamento_plano_conta` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_empreendimento` int(11) NOT NULL DEFAULT '0',
  `dta_inicial` varchar(10) DEFAULT NULL,
  `dta_final` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `tbl_item_planejamento_plano_conta` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_planejamento_plano_conta` int(11) DEFAULT NULL,
  `id_plano_conta` int(11) DEFAULT NULL,
  `mes` varchar(10) DEFAULT NULL,
  `valor` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_planejamento_plano_conta_id_plano_conta_mes` (`id_planejamento_plano_conta`,`id_plano_conta`,`mes`),
  CONSTRAINT `FK_tbl_planejamento_plano_conta_tbl_item` FOREIGN KEY (`id_planejamento_plano_conta`) REFERENCES `tbl_planejamento_plano_conta` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2094 DEFAULT CHARSET=utf8;

**Comment by jheizerwandel** [comment]
PS : TESTEM ISSO COM ATENÇÃO,  FOI MEXIDO EM BASTANTE COISA , PRINCIPALMENTE NA FUNÇÃO QUE TRÁS OS LANÇAMENTOS E TBM NO BANCO

**Comment by lukasqw** [comment]
Segue resumo do teste:
 No relatório DRE
- [ ] A coluna "valor" deve se chamar "realizadas". 
- [ ] Na coluna "diferença" o valor que deve ser exibido tem que seguir a regra : (previstos - realizadas).
Toda a tabela deve seguir essa regra:
- [ ] As linhas dos tipos Resumo (TOP) e Soma (SUM) precisa aparecer em negrito
- [ ] Os valores precisam ter o símbolo da moeda (R$)
- [ ] Os valores do tipo Receita (REVENUE) precisam aparecer em azul
- [ ] Os valores do tipo Despesa (EXPENSE) precisam aparecer em vermelho
- [ ] Os valores dos tipos Resumo (TOP) e Soma (SUM), precisam aparecer:
- quando for negativo em VERMELHO
- quando for positivo em VERDE
- quando for zerado em PRETO
