### ISSUE TITLE
Corrigir problema nos Lançamentos Financeiros

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#849]
- [x] Está ficando com a mensagem de carregando, precisa deixar uma mensagem que é necessário selecionar um periodo p/ efetuar o filtro.
- [x] Ao filtrar por conta, não está zerando o saldo anterior
- [x] Adicionar Promessa de Pagamento no combobox de formas de pagamento

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/lancamentos-controller.js
- lancamentos.php

Alterações API:
- controller/LancamentosFinanceirosController.php
- dao/LancamentosFinanceirosDao.php
- index.php
