### ISSUE TITLE
Implementar tela de pré-fechamento de caixa

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#853]
- Essa tela deve apresentar os valores consolidados pelo PDV (WebliniaERP ou POSI ou outro) e;
- Deve ser possível apontar os valores corrigidos
- Ao finalizar o fechamento do caixa, os valores consolidados são enviados p/ o financeiro.
- Os valores do caixa só vão p/ o financeiro quando ocorrer o fechamento.

**Comment by filipecoelho** [comment]
- [ ] Criar chave de configuração p/ ativar Fechamento de Caixa por Borderô
- [ ] Criar tabela de borderôs (tbl_bordero_fechamento_caixa)
  - id
  - num_sequencial
  - flg_origem_informacao
  - id_fita
  - id_movimentacao_caixa
  - dta_criacao
  - flg_status_bordero
  - id_motivo_cancelamento
  - id_operador_lancamento
  - id_gerente_validacao
  - id_usuario_conferencia
  - dta_conferencia
  - id_externo
  - guid_externo
  - pth_arquivo_referencia
- [ ] Criar tabela de registros do borderô (tbl_lancamentos_bordero_fechamento_caixa)
  - id
  - id_bordero
  - id_forma_pagamento
  - id_maquineta
  - id_bandeira
  - vlr_lancamento_sistema
  - vlr_lancamento_operador
  - vlr_lancamento_conferencista
- [ ] Criar nova tela de Relatório de Resumo de Caixa
  - Exibir relatórios baseados no id_fita
  - Expandir o relatório e exibir os borderos relacionados
  - Expandir o bordero e exibir as colunas:
    - Forma de Pagamento
    - Maquineta (Cartão de Crédito/Débito/Voucher)
    - Bandeira (Cartão de Crédito/Débito/Voucher)
    - Valor (PDV)
    - Valor (Operador)
    - Valor (Conferência)
- [ ] Customizar rotina de fechamento de caixa para não transferir os valores da movimentação ao salvar a conferência do borderô
- [ ] Ao salvar o borderô, gravar os valores na tabela de lançamentos financeiros, de acordo com as formas de pagamento

**Comment by filipecoelho** [comment]
Alterações BD:
	```
		INSERT INTO tbl_configuracao SELECT NULL, 'flg_modo_fechamento_caixa', '1', id AS id_empreendimento FROM tbl_empreendimento;

		CREATE TABLE `tbl_bordero_fechamento_caixa` (
			`id` int(11) NOT NULL AUTO_INCREMENT,
			`id_empreendimento` int(11) NOT NULL,
			`num_sequencial` int(11) NOT NULL,
			`flg_origem_informacao` bit(1) DEFAULT NULL,
			`id_fita` int(11) NOT NULL,
			`id_abertura_caixa` int(11) NOT NULL,
			`dta_criacao` datetime DEFAULT NULL,
			`flg_status_bordero` bit(1) DEFAULT NULL,
			`id_motivo_cancelamento` int(11) NOT NULL,
			`id_operador_lancamento` int(11) NOT NULL,
			`id_gerente_validacao` int(11) DEFAULT NULL,
			`id_usuario_conferencia` int(11) NOT NULL,
			`dta_conferencia` datetime DEFAULT NULL,
			`id_externo` int(11) NOT NULL,
			`guid_externo` varchar(255) DEFAULT NULL,
			`pth_arquivo_referencia` varchar(255) DEFAULT NULL,
			`dta_registro` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (`id`)
		) ENGINE=InnoDB;

		CREATE TABLE `tbl_lancamentos_bordero_fechamento_caixa` (
			`id` int(11) NOT NULL AUTO_INCREMENT,
			`id_bordero` int(11) NOT NULL,
			`id_forma_pagamento` int(11) NOT NULL,
			`id_maquineta` int(11) NOT NULL,
			`id_bandeira` int(11) NOT NULL,
			`vlr_lancamento_sistema` DOUBLE DEFAULT NULL,
			`vlr_lancamento_operador` DOUBLE DEFAULT NULL,
			`vlr_lancamento_conferencista` DOUBLE DEFAULT NULL,
			`id_lancamento_entrada` int(11) DEFAULT NULL,
			PRIMARY KEY (`id`)
		) ENGINE=InnoDB;
	```

Alterações API:
	model/BorderoFechamentoCaixaTO.php
	model/LancamentoBorderoFechamentoCaixaTO.php
	dao/AberturaCaixaDao.php
	dao/MovimentacaoCaixaDao.php
	dao/PagamentoClienteDao.php
	dao/BorderoFechamentoCaixaDAO.php
	controller/BorderoFechamentoCaixaController.php
	index.php

Alterações WEB:
	js/angular-controller/relatorio-consolidado-caixa-bordero.controller.js
	js/angular-controller/empreendimento_config-controller.js
	relatorio-consolidado-caixa-bordero.php
	empreendimento_config.php

Endpoint da API:
	POST http://api.webliniaerp.com.br/bordero
	
Possíveis respostas da API:

	Status Code: 406
	Messagem de Erro: 'Nenhum caixa aberto para o operador [{id_operador}] e fita [{id_fita}]'
	Situação: O sistema não conseguiu encontrar nenhum movimento/caixa registrado para o operador e fita

	Status Code: 406
	Messagem de Erro: 'Nenhum operador encontrado com o id_externo [{id_operador}]'
	Situação: O sistema não conseguiu encontrar nenhum operador (usuário) cadastrado com o id_externo (ID USUARIO POSI)

	Status Code: 406
	Messagem de Erro: 'Nenhum gerente encontrado com o id_externo [{id_gerente}]'
	Situação: O sistema não conseguiu encontrar nenhum gerente (usuário) cadastrado com o id_externo (ID USUARIO POSI)

	Status Code: 500
	Messagem de Erro: 'Erro ao gravar o borderô'
	Situação: O sistema encontrou alguma falha não tratada ao tentar gravar o borderô

	Status Code: 500
	Mensagem de Erro: 'Erro ao salvar o lançamento [{id_tipo_operacao_bordero}] no valor de [{valor_lancamento}]'
	Situação: O sistema não conseguiu gravar o lançamento do borderô na tabela de lancamentos
	
	Status Code: 500
	Mensagem de Erro: 'Erro ao gravar o lançamento de entrada no fluxo de caixa'
	Situação: O sistema não conseguiu gravar o lançamento de entrada na tabela de lançamentos financeiros/fluxo de caixa

	Status Code: 201
	Messagem de Erro: 'Borderô salvo com sucesso!'
	Situação: Borderô salvou com sucesso no banco de dados

**Comment by filipecoelho** [comment]
Segue modelos de estrutura de dados que devem ser passadas para a API p/ efetuar os testes:

[modelo-bordero.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550338e01befa51300278352/125516c66e82c728ace21e0d46e59b9e268e8ce48de6ad47a14fffd665043761260ea62864c7b96aea147d50575b1ff9175b5916fcf18e7da6b73d71d80e03eac3714d36976345f3e5db55ea43a82a994e82bcbd8f4fc1e9382ce58f8e4d3b1b1755.txt)

[modelo-fechamento-bordero.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550338e01befa51300278352/125516c66e82c728ace21e0d46e59b9e268e8ce489ecbc4ba550f59a3d496a712616a72e628aa164fd52690e050a1de853524d41faaf8823a2e76926895a59edd96a0974c73c10feea8a18ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b061988fa5437a49849cd51e406.txt)

**Comment by rafaelqw** [comment]
Alterações BD:
- ```ALTER TABLE tbl_bordero_fechamento_caixa ADD COLUMN id_conta_bancaria_destino INT NULL DEFAULT NULL AFTER dta_registro;```

Alterações WEB:
- js/angular-controller/relatorio-consolidado-caixa-bordero.controller.js 
- relatorio-consolidado-caixa-bordero.php

Alterações API:
- controller/BorderoFechamentoCaixaController.php
- dao/BorderoFechamentoCaixaDAO.php
- index.php
- model/BorderoFechamentoCaixaTO.php
