### ISSUE TITLE
Implementar mecanismos de detalhamento de um lançamento financeiro

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#854]
- O sistema deve permitir o detalhamento de um lançamento financeiro em sub-itens;
- Ao passo que eu lançar um sub-item, apenas os sub-itens devem ser considerados no DRE.

**Comment by mtrystao** [comment]
O campo detalhar esta funcionando, é possivel selecionar varios itens em Plano de Contas e inserir o desmembramento de valores, contudo, o sistema esta permitindo que o valor total do desmembramento seja maior que o valor total, acredito que isso nao deveria ser permitido, pois, o Total e o Desmembramento deveriam ser iguais

**Comment by filipecoelho** [comment]
@mtrystao De fato! Não deveria permitir.

**Comment by jheizerwandel** [comment]
modified:   controller/PagamentoFornecedorController.php
 modified:   dao/PagamentoFornecedorDao.php
 modified:   dao/RelatorioDao.php
 modified:   model/PagamentoFornecedorTO.php

criar campo id_pagamento_detalhamento na tabela  tbl_pagamentos_fornecedores

**Comment by rafaelqw** [comment]
Ao tentar fazer 2 lançamentos de despesa, sendo o primeiro com a forma de pagamento Boleto e 3 parcelas e o segundo seria com forma de pagamento Cheque e 8 parcelas, ao salvar a segunda tentativa fica salvando porque da erro no front...
![DeepinScreenshot_select-area_20180426104837.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56f173464edfec1300fab418/125516c66e82c728ace21e0d46cc919f338b8d9a8cfbba46aa4ef89b3d7934762501a03f3d84f12dbe7d29515e574ea8435e5e44f8f18a2cb4aa2e30c80351b882294d7ed43817fab98a1bee54ec238d1d85bebbdc4cc1e93c77b583885d220c4749d7ab0268f9d31e8a4afc59e0445fa5163467e1733679419d19722f792a.png)

**Comment by lukasqw** [comment]
Ao tentar salvar o valor do detalhamento ocorre esse erro:
![erro_detalhamento.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae749428898760011a91ea0/125516c66e82c728ace21e0d46ed86882cbd87ac9be8b34ba550f59a3d49653f6b14b1247a80e03cfd18395459094fa445090a12ffffdb2baeb16a708b5d0abf83655866da2f53fde6d640e258f075c95d8fa4bd8346c1ed3f20e68a8e4d36180d1a8eed10.png)

**Comment by rafaelqw** [comment]
Testes realizados com sucesso!
