### ISSUE TITLE
Adicionar campo p/ upload do PDF na entrada da nota

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#857]
- [x] Guardar o PDF no servidor
- [x] Guardar o XML no servidor

**Comment by rafaelqw** [comment]
- ```ALTER TABLE tbl_estoque_entrada 
ADD COLUMN pth_pdf VARCHAR(100) NULL;```

Alterações WEB:
- estoque.php
- js/angular-controller/estoque-controller.js

Alterações API:
- controller/EstoqueEntradaController.php
- dao/EstoqueEntradaDao.php
- model/EstoqueEntradaTO.php

**Comment by mtrystao** [comment]
@filipecoelho dessa forma nao tenho como validar se a NF-e foi importada mesmo ou mesmo se a NF-e importada foi a que eu desejei

**Comment by filipecoelho** [comment]
@mtrystao pelo visto não foi, pois não ta gravando no BD
