### ISSUE TITLE
Incluir novo tipo de produto

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#858]
incluir a opção de tipo de produto Materia Prima

**Comment by filipecoelho** [comment]
Alterações BD:
- ```ALTER TABLE `tbl_produtos` ADD `flg_materia_prima` INT  NULL  DEFAULT NULL```

Alterações API:
- model/ProdutoTO.php
- dao/ProdutoDao.php
- controller/ProdutoController.php

Alterações WEB:
- produtos.php
- js/angular-controller/produtos-controller.js

**Comment by mtrystao** [comment]
Esta dando erro no momento de abrir o PDV: version https://git-lfs.github.com/spec/v1 oid sha256:204a16d06d913b156377aa75be2efd0cae83a2b6079cc88e78aab0889f9caa35 size 156783

**Comment by filipecoelho** [comment]
@mtrystao testar novamente, depois ter atualizado os arquivos!

**Comment by mtrystao** [comment]
Nao estou conseguindo abrir o caixa
