### ISSUE TITLE
Saldo Devedor - Errado

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#865]
Na CLF os clientes que pagam com Cartao de Credito e solicitam emissao de Cupom Fiscal estao ficando com Saldo Devedor, os lançamentos aparecem em todos os locais do sistema, porem, nao no extrato do cliente nao consta a baixa do valor correspondente e assim o cliente fica com saldo devedor

**Comment by mtrystao** [comment]
![2018-04-08 10.05.08.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46bac4cb7bcfd3fdc2b9e703f50dbec47c08772b6b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984ec1e23c20e5888e463c19031f80f65b27ed.jpg)
![2018-04-08 10.05.17.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46bac4cb7bcfd3fdc2b9e703f50dbec47c0876246b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e5888e463c19031f80fb5c27ed.jpg)
![2018-04-08 10.05.25.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46bac4cb7bcfd3fdc2b9e703f50dbec47c0875266b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984ec1e23c20e5888e463c19031089fc5e27ed.jpg)
![2018-04-08 10.05.31.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46bac4cb7bcfd3fdc2b9e703f50dbec47c0874226b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984ec1e23c20e5888e463c19031089fc5d27ed.jpg)
![2018-04-08 10.05.38.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46bac4cb7bcfd3fdc2b9e703f50dbec47c08742b6b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e5888e463c19031f80fb5f27ed.jpg)

**Comment by filipecoelho** [comment]
Foram realizados testes e não foi evidenciado o problema.
O teste realizado considerou uma venda para um novo cliente, com a forma de pagamento Cartão de Crédito e posteriormente emitindo-se o Cupom Fiscal SAT.
Como pode-se verificar nos prints abaixo.
Marcando o chamado como INVALIDO!
![Captura de Tela 2018-05-25 às 17.16.16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550338e01befa51300278352/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227149f37e3dd7b668beee9b124f5e49b2405e4145faeb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da59fe41e04857a311316ae272317945920c38.png)
![Captura de Tela 2018-05-25 às 17.16.11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550338e01befa51300278352/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227149f37e3dd7b668beee9b124f5e49b2405e4145fdeb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da5af741e04857a311316ae272317945960c38.png)
