### ISSUE TITLE
Troca de Vendedor PDV

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#866]
Conforme conversado com a Cris em 18/01 se faz necessário incluir no inicio da venda uma pergunta para trocar o vendedor, pois, apenas pelo botão existente na barra elas podem deixar passar

**Comment by filipecoelho** [comment]
Tempo estimado: 1,5h

**Comment by jheizerwandel** [comment]
modified:   pdv.php
modified:   js/angular-controller/pdv-controller.js
modified:   empreendimento_config.php
modified:   js/angular-controller/empreendimento_config-controller.js

**Comment by lukasqw** [comment]
Modal exibido para trocar de vendedor possui o titulo errado "sangria".
