### ISSUE TITLE
Aviso de produto sem estoque PDV

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#869]
favor verificar pois não esta funcionando a function com a borda vermelha para produtos que não estão com estoque no PDV

**Comment by filipecoelho** [comment]
Tempo estimado: 1h

**Comment by jheizerwandel** [comment]
Esta funcionando normalmente para os empreendimentos que não controlam estoque
![pdv.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5db068c9c1a140091db86/125516c66e82c728ace21e0d46f8908c61cec1b99de6b546a749b2ce6b137175785cf72a7583b07ebd122356095f4fad400a0d4cfbeb9539e4e76224d50152a7842f4d7ed43c16a6b9871dba08bf248b468cb7b98f5e8d.png)

**Comment by filipecoelho** [comment]
O problema ocorre normalmente quando tem muitos produtos no carrinho.
Volta e meia, e não é sempre.
Precisamos encontrar um meio em que isso não ocorra.
