### ISSUE TITLE
Criar empreendimento X-Force - Vila Andrade

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#873]
Favor, criar o empreendimento X-Force - Vila Andrade e COPIAR para esse empreendimento os produtos da X3 Loja Física

**Comment by mtrystao** [comment]
Cliente deseja realizar o treinamento para uso do sistema na próxima 4a feira dia 18-04 para ja começar a trabalhar

**Comment by filipecoelho** [comment]
@mtrystao ambiente replicado!
@rafaelqw agendado treinamento c/ cliente amanhã as 10h.
