### ISSUE TITLE
Cod de barras Body style

### ISSUE THREAD

**Issue by LEANDROCOELHO84** [WebliniaERP/webliniaerp-web#878]
resolver problema cod. de barras Body Style

planilha de produtos foi enviada pelo sistema com 12 numeros  e na etiqueta dos produtos tem 13 numeros  foi enviado no grupo algumas etiquetas de produtos para uma solução

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php 
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/pdv-controller.js
