### ISSUE TITLE
Problema ao validar se o caixa está aberto.

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#881]
Existe uma função que valida se o caixa está aberto toda vez que é feito uma operação no PDV a fim de garantir que não ocorra algum problema de registrar uma movimentação sem abertura de caixa.
No entanto essa validação está mantendo bloqueado o botão de finalizar a venda e com isso o usuário acaba tendo que recarregar a página pra conseguir registrar novamente.
Basicamente precisa desbloquear o botão toda vez que essa função retornar false para que o usuário tente novamente.

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/pdv-controller.js

**Comment by lukasqw** [comment]
sera necessário forçar o erro para realizar o teste.

**Comment by filipecoelho** [comment]
@lukasqw Acontece aleatoriamente com o Junior da Hulk, o que vai acontecer é que ele não vai mais ter o problema
