### ISSUE TITLE
Lentidao no módulo de OS

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#886]
Joao Hidro Agro e o Sergio da Pro Reflex estao reclamando de lentidao no modulo de OS

**Comment by filipecoelho** [comment]
Alterações BD:
- ```ALTER TABLE `tbl_nota_fiscal` ADD CONSTRAINT `fk_tbl_nota_fiscal_tbl_atendimento` FOREIGN KEY (`cod_ordem_servico`) REFERENCES `tbl_atendimento` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;```
