### ISSUE TITLE
Divergencia entre Qtde de Vendas realizadas, Fechamento de Caixa e Valores Recebidos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#888]
na Hage 06 empreendimento 26
a qtde de vendas que aparecem na tela de vendas esta diferente da movimentacao de caixa e os recebimentos tb estao errados

Esto anexando as imagens para validacao

**Comment by mtrystao** [comment]
![hemerson 02-05 -1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e09197269090a681a9ef11e90da5d46417653f6b14b1247a80e03cfd18395459094fa445090a12ffffdb2baeb16a708b5d0abf83655866da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3f20e5828b4b3c1d021189ed10.jpg)
![hemerson 02-05 -02.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e09197269090a681a9ef11e90da5d4641675316546b3397f8fe62bab0021435a5918ad495c0e11aafa8f79a6be3b268a5d0aec833f5773d42103eee9dc4be05ce36ade0d97bcae8b4bcae93827e289864b3a17001980fc4f78.jpg)

**Comment by filipecoelho** [comment]
@lukasqw analisar e identificar como essa situação está ocorrendo

**Comment by lukasqw** [comment]
Foram abertos dois caixa no dia:

![caixa1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae749428898760011a91ea0/125516c66e82c728ace21e0d46eb95933b83d2ebc3abaf51ab57f5973d047d317c52a57a28d1e22db9112d035f5749fa41595e45aeab812cb4aa2e32db025fb28c341521842f1bbeba8315be04b8278e4c87b6b88c4ec3ef2f68.png)
![movimentaçãocaixa.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae749428898760011a91ea0/125516c66e82c728ace21e0d46e59b8c2a8f86a79be81c84079eff97284f3f726b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984ec1e23c20e58c8a4c3c1e00118dfe5e27ed.png)

Se compararmos os valores dos dois caixas com as vendas do dia esta batendo tudo corretamente.
