### ISSUE TITLE
Falha no momento de lancar recebimento de venda

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#889]
Empreendimento Hage 00 - 01
Venda: 88345
Forma de Pgto: Debito
Valor da compra: R$ 540,00
Vendedor: Allisson

Para essa venda foi lancado o pgto corretamente mas o sistema nao acatou o lancamento

**Comment by filipecoelho** [comment]
já foi identificado e já resolvido
