### ISSUE TITLE
Criar novo empreendimento p/ Dona Ana

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#890]
Nome do empreendimento: D.A. - Interlagos
Dados da empresa: (não colocar agora, apenas p/ informação)
D.A. Interlagos Comércio de Alimentos Ltda. ME
Av. Sarg. Geraldo Santana, 1491 - Q10T
Jd. Taquaral
04674-225
São Paulo - SP
CNPJ: 30.273.045/0001-09
I.E.: 119.347.985.113

**Comment by lukasqw** [comment]
Empreendimento criado.

Acesso liberado para os usuários : 
- RODRIGO RABELLO.
- ANA TADA.
- NATALIA RICO
