### ISSUE TITLE
Criar 02 novos empreendimento Dalls Suplementos Loja 01 e Loja 02

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#891]
precisamos criar 02 novos empreendimentos para a Dalls como produtos replicados e todas as informacoes adicionais para amanha ate as 08h00, quando terei uma conferencia com o Carlos para ja colocarmos para funcionar, a expectativia é que ate o inicio do proximo mes tenhamos ao todo 08 lojas filiais da Dalls

**Comment by lukasqw** [comment]
@mtrystao é para replicar os produtos ou compartilhar eles

**Comment by mtrystao** [comment]
@lukasqw pode compartilhar os produtos

**Comment by filipecoelho** [comment]
@lukasqw compartilhar os produtos na segunda no primeiro horário para que o @mtrystao consiga fazer o treinamento com o cliente.
