### ISSUE TITLE
Erro Falta PDV Hage

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#895]
Hage 01 informa que em varios momentos apos o sistema ficar inativo por algum tempo ai cai a conexao da sessao do navegador e assim que o usuario se loga e tenta lancar uma venda o sistema gera a Mensagem de Erro Fatal e duplica a venda onde a venda com o numero antigo nao recebe o pagamento e somente na venda com numeracao seguinte que recebe o pagamento

**Comment by filipecoelho** [comment]
já foi identificado e resolvido junto com o chamado #889
