### ISSUE TITLE
Código de barras arredondando no PDV

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#898]

**Comment by filipecoelho** [comment]
Tempo estimado: 30m

**Comment by jheizerwandel** [comment]
me de um exemplo

**Comment by mtrystao** [comment]
![arrendamento.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e98688268c87a882ecb157ab1fbcd6395428792c07b7692ac7b67eb91323550e0a18af470a5f4cfbaf892aa7b76e22825b19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3be8f45c5ed3a23e78a8b482c53.jpg)

**Comment by mtrystao** [comment]
ambiente de teste venda: 2213216, codigo de barras correto:  7899767024083, codigo de barras que aparece no PDV  7899767024080

**Comment by jheizerwandel** [comment]
Ateração API
		modified:   dao/EstoqueDao.php
	    modified:   dao/ProdutoDao.php ( OBS: não tem relação com o chamado, mas vai corrigir um erro que achei )

**Comment by mtrystao** [comment]
![arredondadmento 1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e9868826868ca78be8bb4ea153e49b6917653f6b14b1247a80e03cfd18395459094fa445090a12ffffdb2baeb16a708b5d0abf83655866da2f53fde6d640e258f075c95d8fa4bd8246c1ed3f23e38a8d493a16001180ed10.jpg)
![arredondamento 3.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e9868826868ca78be8b246aa49ffd47a046b313916ac217586f76ae5002e57095e46a8100d0947faab8923a1e03c718b5d59bfd96a4d68d47f40f2ecdd42e64bef62994597b7b5804dc5ea3b21e689894b361805199bb2.jpg)
![arredondamento2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e9868826868ca78be8b246aa49ffc66b0a65633b0ba92e7391a172fd172d075e574afd140e5c42aef9812cf0b63d718b0e59e5d67f4366846c4ff8e7df46f554f832815d87b4b68b49c2ee3924e58d8b473b16020ac4.jpg)

**Comment by jheizerwandel** [comment]
Ai tem que abrir outro chamado,pq o problema do chamado foi resolvido , mas vou da a solução para os pessoal ai saberem resolver,  pq eles/eu  estão usando uma função de forma errada em alguns casos , então vou passar a solução para os pequenos jedais  saberem resolver  ... 
na função que retorna os dados eles usam a função "parse_arr_values" para tipar os valores numéricos e os demais de forma correta,  essa função entente o código de barra como  um numero , e não pode por questões técnicas relacionadas ao tamanho suportado por um INTEIRO, ai da essa merda .... 
jeito errado : parse_arr_values($select->fetchAll(PDO::FETCH_ASSOC),'all');
jeito certo : parse_arr_values($select->fetchAll(PDO::FETCH_ASSOC),'all', null, array('codigo_barra','cod_ncm')); 
O ultimo parâmetro (array('codigo_barra','cod_ncm')) é um array , onde vc passa os campos que vc quer que a função ignore ...

**Comment by mtrystao** [comment]
a situacao de arredondamento continua acontecendo no momento de emitir a NF-e
a body style precisa emitir NF-e amanha sem falta e essa falha ira prejudicar a emissao das notas

![arredondamento.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e9868826868ca78be8b246aa49ffd665043761260ea62864c7b96aea147d50575b1ff9175b5916fcf18e7da6b73d71d80e03eac3714d36976345f3e5db55ea43a82a994e8dbcbd8f4ec6e13b22e78c8747381d1755.jpg)

**Comment by filipecoelho** [comment]
o problema está relacionado ao PDV, abrindo outro chamado para tratar em outras telas
