### ISSUE TITLE
Proceder c/ implantação do sistema c/ cliente

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#903]
Já foi disponibilizado o chamado #878 que impedia o prosseguimento da implantação do sistema c/ cliente.
Agora precisamos dar andamento

**Comment by mtrystao** [comment]
Agendado com o cliente para 4a feira as 08h00 a implantacao In Loco

**Comment by mtrystao** [comment]
Favor, baixar e subir para a FOCCUS o certificado digital da Body Style, cliente precisa comecar a emitir NF-e amanha 5a feira dia 17-05


![WhatsApp Image 2018-05-16 at 08.25.06.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46df9c9b3791a2b99fa9964ea55af5d47b16762b6454f66621d3a329ab022b59415d4bb2415e4d58eeb9cb74fce36f34985619e8d73b5e7cc26c44fabb844dbf09bd768b4e84b7eed844c7fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e7495ca5163066e47e336e0a.jpeg)
![WhatsApp Image 2018-05-16 at 08.25.27.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46df9c9b3791a2b99fa9964ea55af5d47b16762b6454f66621d3a329ab022b59415d4bb2435f4d58eeb9cb74fce36f34985619e8d73b5e7cc26c44fabb844dbf09bd768b4e84b7eed844c7fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e7495ca5163066e4713e6e0a.jpeg)
![WhatsApp Image 2018-05-16 at 08.25.55.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46df9c9b3791a2b99fa9964ea55af5d47b16762b6454f66621d3a329ab022b59415d4bb2445d4d58eeb9cb74fce36f34985619e8d73b5e7cc26c44fabb844dbf09bd768b4e84b7eed844c7fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e7495ca5163066e47e366e0a.jpeg)
![WhatsApp Image 2018-05-16 at 08.26.19.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46df9c9b3791a2b99fa9964ea55af5d47b16762b6454f66621d3a329ab022b59415d48b240514d58eeb9cb74fce36f34985619e8d73b5e7cc26c44fabb844dbf09bd768b4e84b7eed844c7fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e7495ca5163066e4713e6e0a.jpeg)
