### ISSUE TITLE
Validar fechamento de caixa c/ cliente

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#904]
O cliente estava registrando vendas usando a forma de pagamento Voucher, que ainda não estava 100% funcional.
Foi implementado o chamado #272 que corrige os problemas de utilização dessa funcionalidade e agora precisa validar se é possível fechar o caixa normalmente.

**Comment by mtrystao** [comment]
"<h1>500 Internal Server Error</h1><h3>SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 (42000)</h3><pre>#0 /home/webliniaerp/public_html/api/dao/MaquinetaDao.php(34): PDOStatement->execute()
#1 /home/webliniaerp/public_html/api/dao/MovimentacaoCaixaDao.php(569): MaquinetaDao->getMaquineta(NULL)
#2 /home/webliniaerp/public_html/api/controller/MovimentacaoCaixaController.php(233): MovimentacaoCaixaDao->fechamentoCaixa('395395', '1000', NULL)
#3 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(201): MovimentacaoCaixaController::fechamentoCaixa('395395', '1000', NULL)
#4 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(141): flight\core\Dispatcher::invokeMethod(Array, Array)
#5 /home/webliniaerp/public_html/api/util/flight/Engine.php(303): flight\core\Dispatcher::execute(Array, Array)
#6 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(188): flight\Engine->_start()
#7 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(141): flight\core\Dispatcher::invokeMethod(Array, Array)
#8 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#9 /home/webliniaerp/public_html/api/util/flight/Engine.php(63): flight\core\Dispatcher->run('start', Array)
#10 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(188): flight\Engine->__call('start', Array)
#11 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(188): flight\Engine->start()
#12 /home/webliniaerp/public_html/api/util/flight/Flight.php(43): flight\core\Dispatcher::invokeMethod(Array, Array)
#13 /home/webliniaerp/public_html/api/index.php(790): Flight::__callStatic('start', Array)
#14 /home/webliniaerp/public_html/api/index.php(790): Flight::start()
#15 {main}</pre>"

**Comment by filipecoelho** [comment]
O problema persiste, deve-se fazer novos testes para validar se estamos gravando as informações corretas no banco de dados.
Ao analisar o movimento do caixa, o cliente usou a forma de pagamento VOUCHER e esta deveria apontar no banco de dados qual maquineta, bandeira e taxa foi usada para o pagamento, no entanto, ao olhar o registro de pagamento na tabela (tbl_pagamentos_venda) o registro estava apenas com a forma de pagamento (id_forma_pagamento = 10) e os campos id_maquineta, id_bandeira e txa_maquineta estavam nulos (NULL), o que indica que não estamos gravando esses dados na hora de finalizar o pagamento da venda ou pagamento avulso.
Estou migrando o chamado p/ problema e colocando na fila para tratamento urgente!

**Comment by filipecoelho** [comment]
Será tratado pelo chamado #272
