### ISSUE TITLE
Produtos em Estoque Reletorio

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#91]
1- Nao esta funcionando o Filtro para busca de produtos
2- Inserir combo box para poder selecionar o fabricante
3- Alterar a forma que a pagina esta carregando, pois, ao selecionar o relatorio Produtos em Estoque esta carregando a soma de todos os produtos em estoque e na sequencia podemos selecionar o deposito desejado, o ideal é que ao selecionar o relatorio a pagina seja carregada somente apos selecionar o deposito desejado

**Comment by mtrystao** [comment]
Agora possuímos o valor de custo de cada item em estoque e tb a qtde de unidades, favor, incluir uma coluna contendo o valor total do produto em estoque, isso é, custo x qtde

**Comment by BreynerDeveloper** [comment]
Ponto - 1 ok
Ponto -2
Ponto -3
Ponto -4

**Comment by rafaelqw** [comment]
Corrigir a linha de Total do Relatorio

**Comment by filipecoelho** [comment]
Ao fazer consulta por fabricante está funcionando, porém as demais formas de consulta pararam de funcionar.

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
