### ISSUE TITLE
Travamento ao finalizar venda

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#917]
Cliente relata que tentou finalizar a venda (itens abaixo) e ficou carregando por alguns minutos e depois atualizou a pagina (F5) e havia salvado apenas uma parte dos itens.
Cliente relata que isso ocorre normalmente após finalizar uma venda e tentar fazer outra.
Abaixo segue link dos itens da venda completa para simular:
http://www.webliniaerp.com.br/api/relPDF?template=comprovante_venda&dados%5Bjson%5D=%7B%22id_venda%22%3A2207138%2C%22id_empreendimento%22%3A111%2C%22pagamento_fulso%22%3Afalse%2C%22id_controle_pagamento%22%3Anull%2C%22id_cliente%22%3A47250%7D

**Comment by lukasqw** [comment]
Não consegui replicar o problema.
