### ISSUE TITLE
Tratar disponibilidade de estoque de insumos de produtos compostos ao finalizar a venda pelo PDV

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#920]
Não está sendo feito a validação do estoque dos insumos de produtos compostos quando tenta finalizar uma venda pelo PDV e acaba gerando uma exceção na linha 528 do arquivo VendaController.php, onde aponta que o produto em questão não possui estoque para ser feito a baixa do estoque.

**Comment by rafaelqw** [comment]
Alterações API:
- controller/VendaController.php
- dao/EstoqueDao.php
