### ISSUE TITLE
Selecionar item ao pressionar ENTER na listagem do modal

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#922]
Cliente solicita que no campo de QTD das telas Nova Entrada de Estoque, Inventário e Solicitação/Envio de Transferência seja possível selecionar o item ao digitar a quantidade e pressionar a tecla ENTER

**Comment by rafaelqw** [comment]
Alterações WEB:
- estoque.php 
- inventario.php 
- pedido_transferencia.php 
- pedido_transferencia_recebido.php

**Comment by mtrystao** [comment]
inseri a qtde e bati ENTER marcou o item como selecionado para ele nao aparece na tela de tras com a qtde inserida

![selcionar prod.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46fb9196208b8ca78efbff53b652f4d665043761260ea62864c7b96aea147d50575b1ff9175b5916fcf18e7da6b73d71d80e03eac3714d36976345f3e5db55ea43a82a994e8cbcbd8f4ec6e13b20ee8f8a4d3a1c1755.jpg)

**Comment by filipecoelho** [comment]
Testei e está funcionando normalmente
