### ISSUE TITLE
movimentacao de caixa faltando informacao

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#924]
no dia 09-05 o caixa do vendedor Adailton da Hage descartou o pagamento realizado para a venda de numero: 89447, porem, o valor da venda esta no relatorio de vendas por vendedor e na tela de vendas

**Comment by mtrystao** [comment]
![2018-05-10 19.12.13.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46bac4cb7bcfd3fcc2b8ef03f504bec57b0876206b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e58e86463e18061188ff5d27ed.jpg)
![2018-05-10 19.12.43.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46bac4cb7bcfd3fcc2b8ef03f504bec57b0873206b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984ec0e23c20e58e86463e18061189f65427ed.jpg)
![2018-05-10 19.12.51.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46bac4cb7bcfd3fcc2b8ef03f504bec57b0872226b48e13b628ae92dbc56395b4d5a48fa40505b15a9af8a2df4b63477dc5c0aecd03f0d7cc12f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e58e86463e18061189f65427ed.jpg)

**Comment by rafaelqw** [comment]
Chamado Inválido!

**Comment by mtrystao** [comment]
Rafa, na verdade o chamado nao foi inválida, pq temos que de alguma forma identificar que uma venda foi realizada sem recebimento e o sistema nao pode finalizar a venda, acredito que deva aparecer alguma indicacao ou alerta mas tem que indicar que uma venda no modo loja esta sem recebimento

Imagine que se essa situacao se torna mais recorrente, vamos ter problemas na conferencia das movimentacoes diaria, concorda?
