### ISSUE TITLE
Implementar mecanismo de agrupar produtos similares p/ consolidação no Rel. Vendas p/ Produto

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#932]
Alguns produtos possuem variações de tipo na venda e na verdade são um só.
Ex.:
- Calzone Calabresa (ID: 1)
- Cupom Calzone Calabresa (ID: 2)
- Promo Calzono Calabresa (ID: 3)
No Relatório de Vendas por Produto o que importa para o cliente é ver o total vendido do ID 1 e suas variações (2 e 3)

**Comment by rafaelqw** [comment]
Alterações BD:
- ```ALTER TABLE tbl_produtos ADD COLUMN id_produto_pai INT NULL AFTER flg_controlar_estoque;```

Alterações WEB:
- produtos.php
- js/angular-controller/relatorio_vendas_produtos-controller.js 

Alterações API:
- controller/ProdutoController.php
- dao/ProdutoDao.php
- dao/RelatorioDao.php
- model/ProdutoTO.php
