### ISSUE TITLE
Redesenhar Rel. Posição de Estoque

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#933]
- O relatório na verdade não é um apontamento em si, mas o resultado de apontamentos.
- Dessa forma, ele deve deixar de existir como atualmente e deve ser gerado conforme filtros, e os produtos são carregados automaticamente.
(conversar comigo quando for implementar)
- Incluir coluna de indicação de Quebra Total (Col. Desperdícios + Col. Diferença): 
  - Verde: <= 0,30 %
  - Amarelo: > 0,30 % e <= 0,49%
  - Vermelho: > 0,50%

**Comment by rafaelqw** [comment]
- ```INSERT INTO tbl_modulo (nme_modulo, tlt_modulo, url_modulo, icn_modulo, id_modulo_pai, psc_menu_modulo, vsv_menu_modulo) VALUES ('Relatório Posição Estoque', 'Relatório Posição Estoque', 'rel_posicao_estoque.php', 'fa-file-text-o', '3', '21', 1);```
