### ISSUE TITLE
Ocultar produtos compostos das telas de estoque

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#934]
Ocultar produtos compostos das telas abaixo, uma vez que, em tese, o estoque desses produtos é gerado através de processo de ordem de produção
- Nova Entrada (estoque.php)
- Inventário (inventario.php)

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/estoque-controller.js
- js/angular-controller/inventario-controller.js

**Comment by rafaelqw** [comment]
Alterações WEB:
- empreendimento_config.php
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/estoque-controller.js
- js/angular-controller/inventario-controller.js
- js/angular-controller/pedido_transferencia-controller.js
- js/angular-controller/pedido_transferencia_recebido-controller.js
- produtos.php
