### ISSUE TITLE
Incluir botão p/ selecionar todos os produtos de uma vez nas telas de lançamento de estoque

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#935]
Incluir botão p/ selecionar todos os produtos de uma vez nas telas abaixo:
- Nova Entrada (estoque.php)
- Inventário (inventario.php)

**Comment by rafaelqw** [comment]
Alterações WEB:
- estoque.php
- js/angular-controller/estoque-controller.js
