### ISSUE TITLE
Mostrar campo de qtd ao invés de botão nas telas de estoque

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#936]
Quando o estoque do produto não for controlado por validade, exibir diretamente o campo de quantidade para o usuário digitar, uma vez que ele não precisa informar a data de validade dos produtos, sendo desnecessário a abertura de um modal (pop-up) e posterior informação da quantidade e clicar em salvar, o que gera uma demora no lançamento das informações.
- Nova Entrada (estoque.php)
- Inventário (inventario.php)

**Comment by rafaelqw** [comment]
Alterações WEB:
- estoque.php 
- inventario.php 
- js/angular-controller/inventario-controller.js

**Comment by lukasqw** [comment]
Na pagina inventario o campo de qtd dos produtos com validade não esta calculando a soma total deles corretamente.

**Comment by rafaelqw** [comment]
Problema Corrigido, atualizar os mesmos arquivos!
