### ISSUE TITLE
Criar indicador de Quebra de Estoque

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#938]
Baseado no Relatório de Posição de Estoque, deve exibir valores da seguinte forma:
Verde: <= 0,30 %
Amarelo: > 0,30 % e <= 0,49%
Vermelho: > 0,50%

**Comment by rafaelqw** [comment]
Alterações WEB:
- dashboard.php
- js/angular-controller/dashboard-controller.js

**Comment by lukasqw** [comment]
Toda vez que clica no botão de filtrar o valor muda no indicador

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/dashboard-controller.js
