### ISSUE TITLE
Criar indicador de vendas hora a hora semanal

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#939]
Criar indicador de vendas hora a hora semanal, conforme imagem abaixo:
![Captura de Tela 2018-05-14 às 11.01.50.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/550338e01befa51300278352/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227149f37e3dd4b768beee9b124f5e4fb241594141fceb9539e6f4632adf0f4fffdb7f5a72903c19a8e9d749bc07e8208348d3b6bd8b4d92ba3522f5979d0d6f405147d4a61760e28b41da59f141e04857a210366bef7f377f46900c38.png)

**Comment by rafaelqw** [comment]
Alterações WEB:
- dashboard.php
- js/angular-controller/dashboard-controller.js

**Comment by Kenzo13** [comment]
Quando você escolhe o filtro "valor" acima do gráfico e depois volta para o filtro "quantidade" ele apresenta informações não compatíveis com o relatório hora a hora, surgem vendas que nem foram feitas naquele determinado período.

**Comment by rafaelqw** [comment]
Alterações WEB:
- dashboard.php
- js/angular-controller/dashboard-controller.js
