### ISSUE TITLE
Transferencia de produtos Hage Suplementos

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#940]
O Moamar utiliza somente o celular para realizar o processo de envio de produtos para as outras lojas, ele esta sentindo muita dificuldade em realizar esse processo devido a falta da barra de rolagem horizontal, por favor, queiram verificar a possibilidade de disponiblizar essa barra nessa semena, pois, ele liga direto varias vezes durante o dia para que eu faca essa atividade para ele, devido a dificuldade

**Comment by rafaelqw** [comment]
Alterações WEB:
- pedido_transferencia.php
- pedido_transferencia_recebido.php
