### ISSUE TITLE
Incluir identificação de transferência entre contas nos lançamentos financeiros

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#944]
cliente deseja visualizar de forma rápida se o lançamento de uma conta é transferência de outra conta

**Comment by rafaelqw** [comment]
Alterações BD:
- ```ALTER TABLE tbl_pagamentos_fornecedores ADD COLUMN flg_transferencia_financeiro INT NULL DEFAULT 0 AFTER id_pagamento_detalhamento;```
