### ISSUE TITLE
Alterar layout de informações do Rel. Movimentação de Caixa

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#946]
- [x] Cliente deseja visualizar os totais por forma de pagamento primeiro, depois os lançamentos venda a venda
- [x] Cliente deseja visualizar de forma detalhada os cartões de crédito, débito e voucher
  - Forma de Pagamento / Maquineta / Bandeira

**Comment by filipecoelho** [comment]
Alterações WEB:
- rel_movimentacao_caixa.php
- js/angular-controller/rel_movimentacao_caixa-controller.js

**Comment by filipecoelho** [comment]
Alterações API:
- dao/MovimentacaoCaixaDao.php

**Comment by lukasqw** [comment]
- [ ] No relatório não esta exibindo o detalhamento do voucher
