### ISSUE TITLE
Dar baixa em lançamentos pelo Rel. Contas a Receber

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#949]
Baseado em um filtro no relatório:
- [x] Cliente deseja ter opção de selecionar os lançamentos que quer dar baixa
- [x] Cliente deseja ter opção de selecionar todos os lançamentos que quer dar baixa
- [x] Cliente deseja marcar que deseja baixar os lançamentos selecionados
- [x] Cliente deseja já efetuar a transferência entre as contas BOLSA BANCO e BANCO p/ movimentar os valores

**Comment by rafaelqw** [comment]
Alterações WEB:
- js/angular-controller/rel_pagamentos-controller.js
- rel_pagamentos.php

**Comment by Kenzo13** [comment]
Ao tentar fazer transferência com o botão "marcar todos" ,o sistema seleciona as vendas mesmo elas tendo sido pagas. O ideal seria verificar se as vendas já foram pagas para disponibilizar a seleção.

**Comment by rafaelqw** [comment]
Problemas corrigido, apenas atualizar o:
- js/angular-controller/rel_pagamentos-controller.js
