### ISSUE TITLE
Código de barras arredondando na emissão NF-e

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#952]
Verificar arredondamento na emissão de NF-e:

![arredondamento.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55d5e85ef2ace70e00b01057/125516c66e82c728ace21e0d46e9868826868ca78be8b246aa49ffd665043761260ea62864c7b96aea147d50575b1ff9175b5916fcf18e7da6b73d71d80e03eac3714d36976345f3e5db55ea43a82a994e8dbcbd8f4ec6e13b22e78c8747381d1755.jpg)

**Comment by rafaelqw** [comment]
Alterações API:
- dao/ItemVendaDao.php
