### ISSUE TITLE
Ocultar valores do controle de mesas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#956]
Adicionar chave de configuração pra controlar exibição de valores na tela do controle de mesas.

**Comment by rafaelqw** [comment]
Alterações BD:
- ```INSERT INTO tbl_funcionalidade (id_modulo, cod_funcionalidade, nme_funcionalidade, dsc_funcionalidade) VALUES ('67', 'ver_valores_controle_mesa', 'Ver valores no controle de mesas', 'Ver valores no controle de mesa');```

Alterações WEB:
- controle-mesas.php
