### ISSUE TITLE
Consultar cliente pelo ID Externo no controle de mesas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#957]
- [x] permitir consulta de cliente pelo campo ID externo
- [x] ao selecionar um cliente que tem ID Externo já vincular o cartão que contém o mesmo número

**Comment by rafaelqw** [comment]
Alterações WEB:
- clientes.php
- controle-mesas.php
- js/angular-controller/controle-mesas_controller.js

**Comment by lukasqw** [comment]
- [ ] Não esta vinculando automaticamente o cartão ao cliente.
