### ISSUE TITLE
Criar metodo para bloquear comanda com motivo

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#967]
Everton cliente Shark Lounge solicita que seja criado uma forma de bloquear uma comanda e inserir o motivo do bloqueio, pois, caso tentem utilizar a comanda o sistema ira apresentar a informacao de que a comanda esta bloqueada e tb apresentar o motivo

Ele teve uma situacao hoje onde o cliente foi embora e levou a comanda e nao pagou as compras realizadas

Cliente ficou de nos enviar o numero das comandas que precisam ser bloqueadas via banco de dados

**Comment by rafaelqw** [comment]
Alterações BD:

- ```ALTER TABLE weblinia_clientes.tbl_comanda ADD COLUMN flg_excluido INT NULL DEFAULT 0 AFTER id_empreendimento, ADD COLUMN flg_bloqueado INT NULL DEFAULT 0 AFTER flg_excluido, ADD COLUMN obs_motivo_bloqueio VARCHAR(255) NULL AFTER flg_bloqueado;```

Alterações WEB:
- js/angular-controller/controle-mesas_controller.js

Alterações API:
- controller/RelatorioController.php
- dao/RelatorioDao.php
