### ISSUE TITLE
Vitrine

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#968]
No ambiente da Hage a Vitrine nao esta trazendo nenhum produto mesmo a configuracao estando feita corretamente

**Comment by lukasqw** [comment]
Se um produto for compartilhado entre dois empreendimentos  e adicionarmos estoque no empreendimento 1 na query de pesquisa da vitrine do empreendimento 2 traz o produto sem ele ter estoque

**Comment by filipecoelho** [comment]
Alterações WEB:
- js/angular-controller/vitrine-controller.js
- vitrine.php
