### ISSUE TITLE
Tratar qtd de caracteres na justificativa do cancelamento de NF-e

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#973]
A SEFAZ obriga ter no mínimo 15 caracteres.
Ao tentar emitir uma nota com menos é retornado um erro que inclusive não é exibido para o usuário.
Neste caso o ideal é tratar no front e não deixar passar sem essa validação.

**Comment by lukasqw** [comment]
Alterações WEB:
 - js/angular-controller/notas_fiscais-controller.js

**Comment by mtrystao** [comment]
chamado validado

**Comment by rafaelqw** [comment]
Testes realizados, tudo ok!
