### ISSUE TITLE
Campos adicionais para controle de Estoque

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#981]
Favor, inserir na aba Estoque um campo para que seja possivel inserir a localizacao do produto Ex: Rua: 03 - Prateleira: 02 - Piso: Superior, essa informacao devera aparecer tambem quando olharmos na tela de produto na coluna estoque, assim poderemos identificar a localizacao do produto

**Comment by filipecoelho** [comment]
@mtrystao Já pensou como vai ser a baixa de estoque dessa forma ?

**Comment by mtrystao** [comment]
acredito que a baixa deva continuar exatamente da mesma a informacao da localizacao seria meramente informativa, mas é uma ideia

**Comment by filipecoelho** [comment]
@mtrystao Não tem como criar Campos pra controlar o estoque por rua, prateleira e piso sem considerar a baixa do estoque ....
Isso só funciona em centro de armazenamento onde as vendas não interferem no controle do estoque.
Pra funcionar, a manipulação do estoque deveria ser apenas via processo de transferência ou separação.

**Comment by mtrystao** [comment]
Entao, seria algo do tipo o vendedor faz a venda, vai para separacao la o cara insere qtde que sera retirado de cada localizacao e finaliza o processo, nesse momento é concluido a baixa no estoque de cada localizacao, o que acha?

**Comment by filipecoelho** [comment]
@mtrystao O modelo correto é ter uma área de separação de estoque, onde esse usuário tem mais tempo pra usar o sistema e incluir os dados: de qual depósito, de qual validade, lote, rua, prateleira e piso...

**Comment by mtrystao** [comment]
ok!! perfeito, acredito que falamos a mesma coisa mas por exemplo data de validade pode ser um campo adicional, é possivel realizarmos esse processo e que ele seja habilitado ou nao no empreendimento

**Comment by mtrystao** [comment]
estou considerando essa condicao atraves do que haviamos conversado e que vc achou interessante la na X3

**Comment by filipecoelho** [comment]
Está sendo tratado no chamado #1274
