### ISSUE TITLE
Favor criar novo empreendimento Hage 09 - CENESP

### ISSUE THREAD

**Issue by mtrystao** [WebliniaERP/webliniaerp-web#983]
A Hage esta assumindo uma loja dentro do Centro Empresarial de Sao Paulo, favor, criar um novo empreendimento e compartilhar os produtos do Deposito incluindo, valores, informacoes fiscais e demais informacoes dos produtos

**Comment by mtrystao** [comment]
Empreendimento deve ser criado no ambiente da Hage

**Comment by lukasqw** [comment]
Empreendimento criado e produtos compartilhado
