### ISSUE TITLE
Corrigir problema com campo cEAN e cEANTrib c/ FocusNFe

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#992]
Não está sendo possível enviar o campo cEAN individualmente, apenas em conjunto com cEANTrib, porém não há documentação para o campo na FocusNFe

**Comment by rafaelqw** [comment]
Alterações API:
- controller/NfeController.php

**Comment by lukasqw** [comment]
Fiz a transmissão de uma nota sem nenhum erro mas no momento de atualizar a situação fica atualizando e no console da erro.
